### DISCUSSION TITLE
Composite and reusable actions

### DISCUSSION THREAD

**Discussion by amin-nas** [EnsembleUI/ensemble#60] [Ideas]
## Background
There are use cases where I need to chain multiple actions of different types, and then trigger that set of actions on more than one event. E.g. run the action group on screen load and also when user presses a button.

## Use case
As an app developer, I want to be able to create a reusable composite action globally and call it throughout my app.

## Proposed syntax
```
# new section where I can define action groups to be reused
Actions:   

  # name the action
  myCustomAction:
    action : ...


# use the action by passing it to events
View:
   onLoad: myCustomAction

  Column:
    children:
        - Button:
            onTap: myCustomAction
```
