### ISSUE TITLE
labelStyle broken for dropdown and checkbox

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1043]
```yaml
        - Dropdown:
            label: Label
            items:
              - Red
              - Blue
              - Green
            styles:
              variant: box
              contentPadding: 16
              labelStyle:
                color: purple
                fontSize: 20
```
