### ISSUE TITLE
Support expanding items of ToggleButton widget

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#1044]
I want to achieve the style as shown in atatched picture, everything is perfect except that i'm not able to figure out how'd the items of ToggleButton widget be expanded (to take full available space)
- there is no `padding` style exposed for this widget as well
- tried `expanded` property but no luck!

```yaml
View:
  header:
    title: ToggleButton

  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - ToggleButton:
            items:
              - Women's Stuff
              - Men's Stuff
            styles:
              borderColor: 0xFFAEAEAE
              spacing: 20
              color: 0xFF101828
              selectedColor: white
              backgroundColor: white
              selectedBackgroundColor: 0xFF5C54E4
            onChange: |-
              ensemble.debug(this.value)
```

![image](https://github.com/EnsembleUI/ensemble/assets/32386713/ed77163a-c362-4400-9e4c-2526391e074a)
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/662f2872-e2f1-4b20-bc37-80ebe1f33887)
