### ISSUE TITLE
API response not available in header

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1053]
```yaml
View:
  onLoad:
    invokeAPI:
      name: getProduct

  header:
    title: ${getProduct.body.title}

  body:
    Column:
      children:
        - Text:
            text: ${getProduct.body.title}
API:
  getProduct:
    method: GET
    uri: https://dummyjson.com/products/1
```
