### ISSUE TITLE
Enhance Flow widget kitchen sink sample to show how to use item-template with Flow widget

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1074]
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/3e901fb8-a0e8-4f52-979b-7f5f2547e650

the above only shows example of Flow when children are hardcoded. That will almost never be the case. Please add an example for Flow widget using item-template. You can use a fake API and manipulate the response in the onResponse. See below - 

```
API:
  getMockData:
    uri: https://dummyjson.com/users/1
    method: GET
    onResponse:
      executeCode:
        body: |-
          //@code
          response.body.data = [........];//your data
```
and then bind the template to the getMockData API
