### ISSUE TITLE
item-template doesn't work with hardcoded values

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#1092]
item-template is complex so the first thing people try to do is to bind to a list of hardcoded values to try out:
```
item-template:
  data: [one, two, three].    // doesn't work - this is what we expect to work
  data: ${[one, two, three}].  // this works because we expect an expression.
  ...
```
We want to fix it so that data doesn't have to be an expression. Currently the code expects that and it won't bind to a hardcoded string.
