### ISSUE TITLE
Regex Error in JS 

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1095]
I'm getting HTML from the server, I just need 2 IDs from it, so wrote a JS function to extract these IDs from the HTML, but it's not working in our editor. tried this in the Chrome console and it is working fine

```js
function extractIds(htmlString) {
    var propertyIdMatch = htmlString.match(/property\/([^\/]+)\/manage/);
    var bookingIdMatch = htmlString.match(/booking=([^"\']+)/);

    var propertyId = propertyIdMatch ? propertyIdMatch[1] : null;
    var bookingId = bookingIdMatch ? bookingIdMatch[1] : null;

    return {
        propertyId: propertyId,
        bookingId: bookingId
    };
  }

var htmlString = '<html><head></head><body>Sharjeel modified the trip. <a data-ios-target="booking:05a1ead9-cf90-4bcf-8e56-0c469ffa7f4e" data-ios-target-v1="internal:booking:05a1ead9-cf90-4bcf-8e56-0c469ffa7f4e" href="https://myplace.co/app/property/831c18d1-3557-4106-9247-932a4a5c416c/manage?booking=05a1ead9-cf90-4bcf-8e56-0c469ffa7f4e">Review</a></body></html>';

var ids = extractIds(htmlString);

console.log('Property ID:', ids.propertyId);
console.log('Booking ID:', ids.bookingId);
```

Getting this error: 
```
Error :  Line: 1029 in YAML and Line: 105 within the code block. Error Message: Error while executing method: htmlString.match(/property\/([^\/]+)\/manage/). Underlying error:FormatException: Illegal RegExp pattern (SyntaxError: Invalid regular expression: /property\([^\]+)\manage/: Unterminated character class)
property\([^\]+)\manage
StackTrace :  null
Line: 1029 in YAML and Line: 105 within the code block. Error Message: Error while executing method: htmlString.match(/property\/([^\/]+)\/manage/). Underlying error:FormatException: Illegal RegExp pattern (SyntaxError: Invalid regular expression: /property\([^\]+)\manage/: Unterminated character class)
property\([^\]+)\manage
```

**Comment by sharjeelyunus** [comment]
https://github.com/EnsembleUI/ensemble_ts_interpreter/blob/master/lib/invokables/invokableregexp.dart
Seeing this it looks like we aren't supporting `match` method right now, only supporting test method.

**Comment by kmahmood74** [comment]
your regex seems to have issues. try - /property\([^)]+\)manage/

**Comment by sharjeelyunus** [comment]
regex is working in chrome console, providing Property Id and Booking id, 
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/1a900c7f-cc17-4cab-a8b4-e44eff326018)

tried this `/property([^)]+)manage/` as well, getting the null values
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/95140585-41f0-4da9-a8f1-8b7cec89268b)

**Comment by sharjeelyunus** [comment]
hey @kmahmood74 we need this regex solution, the workaround only works for some types of messages, mostly it doesn't specially when we have more than 1 link in the html

try this in your browser and then try in studio

```js
function extractBookingId(htmlString) {
  // Define a regular expression pattern to match the booking ID
  var regex = /booking:([a-f0-9-]+)/i;

  // Use the exec method to find the match
  var match = regex.exec(htmlString);

  // Check if a match is found and return the booking ID
  if (match && match[1]) {
    return match[1];
  } else {
    // Return null or handle the case when no match is found
    return null;
  }
}

// Example usage:
var htmlString = '<html><head></head><body>You modified the trip. <a data-ios-target="booking:c1a6dafa-357e-4cda-81a3-b86947a3fdf4" data-ios-target-v1="internal:booking:c1a6dafa-357e-4cda-81a3-b86947a3fdf4" href="https://dev.myplace.co/app/property/1768122a-d6b3-4a7a-bd73-f6b760d1c025/manage?booking=c1a6dafa-357e-4cda-81a3-b86947a3fdf4">Review</a></body></html>';

var bookingId = extractBookingId(htmlString);
console.log("Booking ID:", bookingId);
```

**Comment by amin-nas** [comment]
@sharjeelyunus 
The console throws this error:
> no method found for property=exec
> Code: regex.exec(htmlString)

which means there is no support for `exec`. We do support `match` and `matchAll` so try this:

```yaml
View:
  body:
    Column:
      styles:
        padding: 24
      children:
        - Button:
            label: test
            onTap: |

              var htmlString = '<html><head></head><body>You modified the trip. <a data-ios-target="booking:c1a6dafa-357e-4cda-81a3-b86947a3fdf4" data-ios-target-v1="internal:booking:c1a6dafa-357e-4cda-81a3-b86947a3fdf4" href="https://dev.myplace.co/app/property/1768122a-d6b3-4a7a-bd73-f6b760d1c025/manage?booking=c1a6dafa-357e-4cda-81a3-b86947a3fdf4">Review</a></body></html>';

              var regex = /booking:([a-f0-9-]+)/i;
              var match = htmlString.matchAll(regex);
              console.log(match);

              match.map(function (m) {
                console.log(m.split(":")[1])
              });
```
