### ISSUE TITLE
DataColumn's label is not evaluating expressions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#110]
When using expression for a DataColumn's label, the expression is printed on screen instead of being evaluated.

Sample YAML
```
View:
  Column:
    styles: { gap: 12, padding: 24, scrollable: true }
    children:
      - DataGrid: 
          DataColumns:
            - label: Column 1
              type: text
            - label: "${ 10 > 0 ? 'yes' : 'no'}"
              type: text

          children:
            - DataRow:
                visible: false
                children:
                  - Text:
                      text: cell a 1
                  - Text:
                      text: cell b 1

            - DataRow:
                children:
                  - Text:
                      text: cell a 2
                  - Text:
                      text: "${ 10 > 0 ? 'yes' : 'no'}"
```
