### ISSUE TITLE
Request: Dropdown Widget Styling

### ISSUE THREAD

**Issue by omermahmood** [EnsembleUI/ensemble#1153]
1. Ability to style the font and background of the Dropdown Widget Values
2. Dropdown Widget: Ability to style the border to match the Widget (round edges)

<img width="184" alt="image" src="https://github.com/EnsembleUI/ensemble/assets/18559315/c01f5de0-5ea9-4873-a153-6ab00246006c">

**Comment by amin-nas** [comment]
The requested styling items are added except for for border color.

**Comment by TheNoumanDev** [comment]
# Problem
For dropdown before if we were using the below EDL:
```yaml
- Dropdown:
    styles:              
      borderColor: red
      borderWidth: 4
    items:
      - Item 1
      - Item 2
```
It gives the below result, as `borderColor` was applied on the `border` of the dropdown.
![image](https://github.com/user-attachments/assets/5b97e732-04c2-4711-bc7c-9e6b32198471)

# Fixed Solution
so updated that bug, now styling attributes that start with `dropdown` is styling the list of options that open up, e.g. `dropdownBackgroundColor` and `dropdownBorderColor` and separately, we have `borderColor` and `borderWidth` that style the input box only.

Exampl EDL:
```yaml
Dropdown:
   label: Colors
   floatLabel: true
   items:
       - Red
       - Blue
       - Green
    styles:
       # variant: underline
       # autoComplete: true
       focusedBorderColor: black
       borderRadius: 50
       borderColor: red
       dropdownBorderWidth: 5
       dropdownBorderColor: green
       borderWidth: 5
```
Issue: https://github.com/EnsembleUI/ensemble/issues/1153
