### ISSUE TITLE
TabBar's unexpected padding

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1162]
When I use TabBar with position start, it adds padding on the left side of the TabBar. There should be no padding unless specified by user.

```
        - TabBar:
            styles:
              tabPosition: start
              tabPadding: 0 24
            items:
              - label: Stretch Tab 1
                icon: fiveHundredPx fontAwesome
                widget: 
                  Column:
                    styles: 
                      padding: 30
                      crossAxis: center
                    children:
                      - Text:
                          text: First Tab content
              - label: Stretch Tab 2
                icon:
                  name: home
                  size: 30
                widget: 
                  Column:
                    styles: 
                      padding: 30
                      crossAxis: center
                    children:
                      - Text:
                          text: Second Tab content
```

![Screenshot 2024-01-23 092947](https://github.com/EnsembleUI/ensemble/assets/491202/b9b53d2c-55d4-49cb-8f6e-7f1260ea799d)
