### ISSUE TITLE
footer | Allow transparent background 

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1170]
right now you if you give footer a `backgroundColor: transparent`, it doesn't work, it just shows white color. we should be able to give transparent background to footer

try this:

```yaml
footer:
    styles:
      height: 44
      backgroundColor: transparent
    children:
      - Column:
          styles:
            crossAxis: stretch
            padding: 0 22
          children:
            - Button:
                id: viewCart
                styles:
                  backgroundColor: 0xff65558f
                  borderRadius: 25
                  labelStyle:
                    color: 0xffffffff
                label: View Cart • ${calculateTotalCount(ensemble.storage.foodItems)} items added
```

https://discord.com/channels/1031982848485359626/1199934549375856730
