### ISSUE TITLE
Support Conditional actions

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1172]
A lot of the js code in Ensemble apps is of the following type - 

```
  onLoad: |
    if(ensemble.storage.get('user_auth_token') == null) {
      ensemble.navigateScreen(
        {
          "name":"Guest App Nav", 
          options:
            {replaceCurrentScreen:true, clearAllScreens:true}
        });
    } else if(ensemble.storage.get('registration_completed') == true) {
      ensemble.navigateScreen(
        {
          "name":"App Nav", 
          options:
            {replaceCurrentScreen:true, clearAllScreens:true}
        });
    } else {
      ensemble.navigateScreen(
        {
          "name":"Incomplete App Nav", 
          //inputs: {"selectedIndex": 1},
          options:
            {replaceCurrentScreen:true, clearAllScreens:true}
        });
    }
```
these are conditional actions. Today there is no way to specify these in yaml. As a result, developers end up using code instead. If we allowed conditions in yaml (just like we do have a Conditional widget), it will make much easier to build apps and reduce the amount of code significantly. 

Proposed yaml - 

```
onLoad:
   Conditional:
        conditions:
          - if: ${ensemble.storage.get('user_auth_token') == null}
            navigateScreen:
              name: Guest App Nav
              options:
                replaceCurrentScreen: true
                clearAllScreens: true
          - elseif: ${ensemble.storage.get('registration_completed') == true}
            navigateScreen:
              name: App Nav
              options:
                replaceCurrentScreen: true
                clearAllScreens: true
          - else:
            navigateScreen:
              name: Incomplete App Nav
              options:
                replaceCurrentScreen: true
                clearAllScreens: true    
```
I'll try `Conditional` but since it is already used for widgets, I may have to use `ConditionalAction` which is certainly not my first choice. 
one of the big advantages of doing most things in yaml is that it works very well with the visual development paradigm and has schema validation built in.
