### ISSUE TITLE
Move Firebase Push config into ensemble-config.yaml

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#1176]
Currently to use Push, you have to update main.dart to initialize Firebase with some hardcoded credentials. We need to move it into the config file.

Tasks:
1. Framework will initialize Firebase by reading the 4 config options from ensemble-config:
```
services:
  firebaseNotification:
    apiKey:
    projectId:
    messagingSenderId:
    appId:
```
Note that this config is optional. Some app can use the GoogleService-Info.plist, in which case this will be empty / not specified.

2. Update EnsembleLive (and production Starter apps) to remove the current config

3. Update documentation and add notification permissions.
