### ISSUE TITLE
TabBar should allow customizing label

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1189]
I want to be able to pass all the text related style properties to my TabBar:

```yaml
TabBar:
  styles:
    labelStyle: 
       # I expect same styles available under Text.styles.textStyle
    selectedLabelStyle: 
       # I expect same styles available under Text.styles.textStyle
```

Also, TabBar should follow the default font family set in Theme. It is currently ignored.
