### ISSUE TITLE
Ability to change the language of the UI (i18n)

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1199]
As an app developer, I want to be able to provide multiple languages, and have an action that allows me to switch the language within the UI:

```yaml
Button:
  onTap:
    setLanguage:
      language: es  # change to this. Also provide option of userDefault, which will adhere to user's device/browser default language
      fallback: en  # if es does not exist, fallback to this
      onComplete:
         # expose event so that I can perform an action
      onError:
         # expose event so that I can perform an action
```

Provide same ability in code:
```javascript
ensemble.setLanguage({
   "language": "es",
   "fallback": "en"
);
```
