### ISSUE TITLE
Support consistent styling across menu types

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1221]
As an app dev, I want to be able to style my menu with following styling:

```
styles:
  padding:
  margin:
  borderRadius:
  backgroundColor:
  itemPadding
  itemGap:
  labelIconGap:
  labelStyle:
    # support styles that we can assign to a text
    # allow setting color and selectedColor separately
  iconStyle:
    # support styles that we can assign to an icon
    # allow setting color and selectedColor separately
```

Acceptance criteria:
1. I can assign these props to bottomNavBar, Sidebar, Drawer, and EndDrawer
2. Sidebar continues to support existing styling props of `itemDisplay`
3. BottomNavBar continues to support styling of floating action button
