### ISSUE TITLE
Bug: API and global function with same name breaks global functions

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1223]
### Issue
I have keep both the API and global function same name, this cause global function to throw following error.
```
flutter: Line: 15 in YAML and Line: 1 within the code block. Error Message: type 'APIResponse' is not a subtype of type 'JavascriptFunction?'Code: function apiGlobalFunctionName() {
flutter:   // noop
flutter: }

```

### How to reproduce
Just load the following EDL screen.
```yaml
View: 
  header:
    title: API issue
  body:
    Text:
      text: Hello there
  
API:
  apiGlobalFunctionName:
    uri: https://github.com/

Global: |-
  function apiGlobalFunctionName() {
    // noop
  }
  ```
  
  ### Quick fix
  Have seperate unique name for global function and APIs
    
  ### Additional Information
  here is what breaking.
  https://github.com/EnsembleUI/ensemble_ts_interpreter/blob/3791c4327812413d19041b20acbb155e6c01dcea/lib/parser/newjs_interpreter.dart#L465
