### ISSUE TITLE
Setting a value of a global var inside executeCode action gets lost outside the action

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1226]
Example
1. Hit the `set global array` button. This should set the globalArray to a new array with 3 items.
2. When the `check global array` button is clicked, it shows the length of the globalArray to be still 0 as the new value is lost

```yaml
View:
    header:
      title: Setting Global var in executeCode gets lost
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
          - Text:
              text: Hi there!
          - Button:
              label: set global array
              onTap:
                executeCode:
                  body: |-
                    globalArray = [1,2,3];
          - Button:
              label: check global array
              onTap:
                executeCode:
                  body: |-
                    ensemble.showToast({
                      message: 'Size of globalArray= '+globalArray.length,
                      options: {duration: 3}
                    })

Global: |-
  // Javascript code
  var globalArray = [];
```
