### ISSUE TITLE
dispatchEvent action, the data is not being evaluated

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1227]
In the following example, when the `Tap me` button is clicked, the data is passed as-is i.e. names array with ['${firstName.value}', '${lastName.value}'] instead of the actual values of the firstName and lastName fields

```yaml
        - TextInput:
            id: firstName
        - TextInput:
            id: lastName
        - Button:
            label: tap me
            onTap:
              dispatchEvent:
                onComplete:
                  data:
                    names:
                      - ${firstName.value}
                      - ${lastName.value}
                     ```
