### ISSUE TITLE
Support (a) `ConditionalActions` (b) `Actions that are executed sequentially without waiting`

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1229]
The motivation behind this is to further reduce the need to write code. 

## executeConditionalAction
IS AN Action and can be used like any other action. that allows actions to be executed based on if/elseif/else conditions 
Proposed Yaml. Yes, the name is not perfect but it's descriptive. Also I think it doesn't make any sense for someone to use this action in code as it is much easier to do conditions in code anyway. Not sure if we should even support calling this action in code, doesn't make any sense. I'll still support it for consistency

```yaml
                executeConditionalAction:
                  conditions:
                    - if: ${parseInt(price.value) < 10}
                      showToast:
                        message: Price is less than $10
                        options:
                          duration: 5
                    - elseif: "${parseInt(price.value) > 10}"
                      showToast:
                        message: Price is greater than $10
                        options:
                          duration: 5
                    - else: 
                      showToast:
                        message: Price is $10
                        options:
                          duration: 5     
```
## executeActionGroup
IS AN Action and can be used like any other action. A group of actions that are executed sequentially in order but without waiting for an action to finish. The primary use case for this is calling multiple APIs in succession. This is important for performance and is today done in code due to the absence of `ActionGroup`. 

sample yaml 
```yaml
                executeActionGroup:
                  actions:
                    - invokeAPI:
                        name: callDelayedAPI
                        inputs:
                          num: 1
                    - showToast:
                        message: second action - 2
                        options:
                          duration: 4
                    - executeCode:
                        body: |- 
                          console.log('executed code - 2');
                    - invokeAPI:
                        name: callDelayedAPI
                        inputs:
                          num: 3
                        onResponse: |-
                          console.log('inline onResponse - 3');
                    - invokeAPI:
                        name: callDelayedAPI
                        inputs:
                          num: 4
                    - showToast:
                        message: number 5
                        options:
                          duration: 3
                    - executeCode:
                        body: |- 
                          console.log('executed code - 5');
