### ISSUE TITLE
Importing script to widget does not work

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1244]
I have an app with a script:
https://studio.ensembleui.com/app/AZp61RdS8oGpUJVciZRG/scripts

I want to import the script to a widget:
https://studio.ensembleui.com/app/AZp61RdS8oGpUJVciZRG/widget/bIXNjQbRP8Ev1lBWtudN

```yaml
Import:
  - Common

Widget:
  body:
    Column:
      children:
        - Text:
            text: ${num}
```

Preview breaks:
![image](https://github.com/EnsembleUI/ensemble/assets/491202/66e6df87-0ba3-4de3-a394-f9ffeaa1ea90)
