### ISSUE TITLE
Instance of 'minified:OP' appears when passing data down to custom widgets

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#125]
When a data binding is passed to custom widgets, a text of `Instance of 'minified:OP'` appears before data is available.

```yaml
View:
  onLoad:
    action: invokeAPI
    name: getItems
  Column: 
    children:
      - Text:
          text: ${getItems.body.records[0].fields.value}
      - TestWidget:
          inputs:
            t: ${getItems.body.records[0].fields.value}
       
TestWidget:
  inputs:
    - t
  Text:
    text: ${t}

API:
  getItems:
    uri: 'https://api.airtable.com/v0/app9bdk0nSKfNx2Wc/Items?api_key=keyZNOCUyqnFMVDCk'
    method: 'GET'
```
