### ISSUE TITLE
Add QR Code scanner widget in Ensemble

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1254]
See the QR code scanner used in Ensemble Live (it uses the `qr_code_scanner` package). This needs to be a first class widget in Ensemble so developers may be able to use in their apps.

**Comment by vinothvino42** [comment]
@kmahmood74
Package QRCodeScanner - https://pub.dev/packages/qr_code_scanner

NOTE: It's mentioned that the qr_code_scanner package is in maintenance mode only

**Sample EDL**:
```yaml
View:
  header:
    title: QR Code Scanner

  body:
    Column:
      styles: { gap: 30, margin: 30 }
      children:
        - QRCodeScanner:
            id: qrCodeScannerId
            styles:
              cutOutBottomOffset: 2
              cutOutHeight: 3
              cutOutWidth: 4
            formatsAllowed: [qrcode, rss14, upcA]
            initialCamera: front | back
            onReceived: |
              //@code
              console.log("Format: "+event.data.format);  // qrcode, rss14, upcA, aztec, etc
              console.log("Code: "+event.data.code);
              console.log("Raw Bytes: "+event.data.rawBytes); // Only supported for Android & iOS

        - Flow:
            styles: { gap: 16, mainAxis: center }
            children:
              - Button:
                  label: Flip Camera
                  onTap: |
                    //@code
                    qrCodeScannerId.flipCamera();

              - Button:
                  label: Flash ON/OFF
                  onTap: |
                    //@code
                    qrCodeScannerId.toggleFlash();

              - Button:
                  label: Pause Camera
                  onTap: |
                    //@code
                    qrCodeScannerId.pauseCamera();

              - Button:
                  label: Resume Camera
                  onTap: |
                    //@code
                    qrCodeScannerId.resumeCamera();
```
