### ISSUE TITLE
Scrolling list control

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#126]
As an Ensemble app developer, I want a ListView widget so I can display a scrollable list of widgets arranged vertically.

Properties:
1. children: an array of Ensemble widgets
2. item-template: to build widgets based on data and template
    For this first iteration, Text is the only widget that will work inside a scrolling list
3. onItemTap: action on tapping on each item in the list

Styles:
- width / height
- expanded
- fontFamily / fontSize
- borderColor, borderRadius, borderWidth
- backgroundColor
- shadowColor, shadowOffset, shadowRadius
- separatorColor: Color
- separatorWidth: int. How thick the separator should be
- separatorPadding: Insets (to add space on top right bottom left of the separator)

Behaviors:
- if children and item-template are both defined, layout the children first, then item-template underneath

Other considerations (do it after the main requirements)
- separatorWidget: custom separator widget

**Comment by kmahmood74** [comment]
@amin-nas let's simplify and remove direction: vertical (default), horizontal. List is assumed to be vertical, let it be so we can cover the majority use case and not spend 3x time trying to make it work horizontally. 

Secondly, by scrollable, do you mean infiniteScroll or just regular scroll? Let's keep infiniteScroll as an additional enhancement for now and assume all the data is there to start with

**Comment by amin-nas** [comment]
Updated

**Comment by kmahmood74** [comment]
@amin-nas do we need to height/width as optionals or just ignore that?

**Comment by amin-nas** [comment]
> @amin-nas do we need to height/width as optionals or just ignore that?

They are optional and part of `styles`. When width and height is not specified, I'd expect ListView to take as much as the children need.

**Comment by kmahmood74** [comment]
@Moeez1999 is this done? there is no checkin against it. Did you put the ticket link in your checkin comment?

**Comment by Moeez1999** [comment]
This is done and merged in main also

**Comment by kmahmood74** [comment]
Example - 

```
View:
  header:
    title: "List View"
  onLoad:
    action: invokeAPI
    name: getPeople

  Column:
    #styles: { padding: 16 16 10 16 }
    children:
      - ListView:
          id: listView
          onItemTap:
            action: navigateScreen
            name: List View Detail Page
            inputs:
              doc_type: ${getPeople.body.users[this.selectedItemIndex]}
              
          styles: {expanded: true }
          #sepratorColor: 0xffB2BEB5, sepratorWidth: 4,sepratorPadding: 16 10 20 10, height: 300, backgroundColor: white, borderColor: black , borderRadius: 10, boderWidth: 5, padding: 10  10 4}
          item-template:
            data: ${getPeople.body.users}
            name: users
            template:
              MyRow:
                inputs:
                  p: ${users}
                      
MyRow:
  inputs:
    - p
  Column:
    children:
      - Row:
          styles: 
            gap: 12
            crossAxis: center
            padding: 8 0
          children:
            - Image:
                styles: {  height: 50, borderRadius: 50 }
                source: ${p.image}
            - Column:
                styles: { gap: 2 }
                children:
                  - Text:
                      styles: { fontWeight: bold }
                      text: ${p.firstName} ${p.lastName}
                  - Text:
                      text: ${p.email}
            - Spacer
            - Icon:
                icon: chevron_right
                styles: { size: 20, color: black }
      
      
API:
  getPeople:
    uri:  https://dummyjson.com/users
    method: GET
```
Kitchen Sink link - https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/w0Wmu9ZMP4csk7IELSx3#
