### ISSUE TITLE
DataGrid sorting

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#127]
I want to be able to sort data grid content:

## Must have

1. no sorting applied by default
2. app developer can specify if a column is sortable
3. when a column is clicked on and sorted, an arrow is displayed next to the the column header
  - ↑ for ascending
  - ↓ for descending

```yaml
  DataGrid:
      DataColumns:
        - label: Name
          type: text
          sortable: true
        - label: Email
          type: text
          sortable: true
        - label: Location
          type: text
          sortable: false
```

## Good to have

1. app developer can specify default sorting order to be applied

e.g. if I want to first sort by second column and in descending order, and then by first column in ascending order:

```yaml
  DataGrid:
    sortingOrder:
      - columnIndex: 2
        order: descending
      - columnIndex: 1
        order: ascending
```

2. Allow user to specify icons to use for sorted columns
  - columnSortedAscendingIcon
  - columnSortedDescendingIcon

**Comment by vusters** [comment]
@vinothvino42 DataTable has built-in sort. Can you implement these?

**Comment by vusters** [comment]
let's do the Good to Have, and create another issue for the Must-Have.

**Comment by vinothvino42** [comment]
This is how I done now.

```yaml
View:
  header:
    title: DataGrid
  styles:
    scrollableView: true
  onLoad:
    invokeAPI:
      name: getHotels

  body:
    Column:
      styles:
        gap: 16
        padding: 24
      children:
        - DataGrid:
            id: dataGridId
            sortingOrder:
              - columnIndex: 2
                order: descending
              - columnIndex: 1
                order: descending

            horizontalMargin: 20
            dataRowHeight: 50
            headingRowHeight: 80
            columnSpacing: 20
            dividerThickness: 1
            DataColumns:
              - label: Hotel Name
                type: text
                tooltip: Hotel Name
                onSort:
                  executeCode:
                    body: |
                      //@code
                      var myHotels = getHotels.body.hotels;
                      // console.log("1 Before Sorting: " + myHotels);

                      var sortedArrays = myHotels.sort(function(a, b) {
                        return b.id - a.id;
                      });

                      // console.log("1 After Sorting: " + sortedArrays);
                      getHotels.body.hotels = sortedArrays;

              - label: Location
                type: text
                tooltip: Location
                onSort:
                  executeCode:
                    body: |
                      //@code
                      console.log('Location called');

              - label: Price
                type: number
                tooltip: Price
                onSort:
                  executeCode:
                    body: |
                      //@code
                      console.log('Price called');

            item-template:
              data: ${getHotels.body.hotels}
              name: hotel
              template:
                DataRow:
                  children:
                    - Text:
                        text: ${hotel.name}
                    - Text:
                        style: { font: subtitle }
                        text: ${hotel.location}
                    - Text:
                        text: ${hotel.price}

API:
  getHotels:
    authorization: none
    uri: "https://dc7ghx6kqg.execute-api.us-west-1.amazonaws.com/dev/hotels/search"
    method: "POST"
    parameters:
      loc:
      fromDate:
      toDate:

```

**Comment by vinothvino42** [comment]
@vusters @amin-nas Is this fine for now?
```yaml
View:
  header:
    title: DataGrid
  styles:
    scrollableView: true
  onLoad:
    invokeAPI:
      name: getHotels

  body:
    Column:
      styles:
        gap: 16
        padding: 24
      children:
        - DataGrid:
            id: dataGridId
            sortingOrder:
              - columnIndex: 2
                order: descending
              - columnIndex: 1
                order: descending

            horizontalMargin: 20
            dataRowHeight: 50
            headingRowHeight: 80
            columnSpacing: 20
            dividerThickness: 1
            DataColumns:
              - label: Hotel Name
                type: text
                tooltip: Hotel Name
                onSort:
                  executeCode:
                    body: |
                      //@code
                      var myHotels = getHotels.body.hotels;
                      // console.log("1 Before Sorting: " + myHotels);

                      var sortedArrays = myHotels.sort(function(a, b) {
                        return b.id - a.id;
                      });

                      // console.log("1 After Sorting: " + sortedArrays);
                      getHotels.body.hotels = sortedArrays;

              - label: Location
                type: text
                tooltip: Location
                onSort:
                  executeCode:
                    body: |
                      //@code
                      console.log('Location called');

              - label: Price
                type: number
                tooltip: Price
                onSort:
                  executeCode:
                    body: |
                      //@code
                      console.log('Price called');

            item-template:
              data: ${getHotels.body.hotels}
              name: hotel
              template:
                DataRow:
                  children:
                    - Text:
                        text: ${hotel.name}
                    - Text:
                        style: { font: subtitle }
                        text: ${hotel.location}
                    - Text:
                        text: ${hotel.price}

API:
  getHotels:
    authorization: none
    uri: "https://dc7ghx6kqg.execute-api.us-west-1.amazonaws.com/dev/hotels/search"
    method: "POST"
    parameters:
      loc:
      fromDate:
      toDate:

```

**Comment by vusters** [comment]
don't use Javascript for custom sort. Do it in YAML. See message in team channels

**Comment by vinothvino42** [comment]
New **EDL**
```yaml
DataGrid:
  id: dataGridId
  sorting:
    columnIndex: 1
    order: ascending or descending
  DataColumns:
    - label: Hotel Name
      type: text
      tooltip: Hotel Name
      sortable: true
      sortKey: name

    - label: Location
      type: text
      tooltip: Location
      sortable: true
      sortKey: location

    - label: Price
      type: number
      tooltip: Price
      sortable: false
      sortKey: price
```
