### ISSUE TITLE
Using view backgroundImage with css flag on breaks the view

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1270]
This screen does not render unless you remove `cssStyling: true` from theme.
https://studio.ensembleui.com/app/j6Kx5d3u1t6GzMHiOWAy/screen/jBJj8YhqCjDn9Vo8WNqo

EDL is:
```yaml
View:
  styles:
    backgroundImage:
      source: https://images.pexels.com/photos/19749503/pexels-photo-19749503/free-photo-of-moon-among-clouds-on-pink-sky.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
  body:
    Column:
      children:
        - Text:
            text: test
```
