### ISSUE TITLE
Event of a custom widget should work without a data

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1282]
I want to define an event, but I have no need for passing data, like the following example:

```yaml
View:
    body:
      Column:
        children:
          - CustomWidget:
              inputs:
                label: click me
              events:
                onSelect: |
                  console.log("I was clicked")
CustomWidget:
  inputs:
    - label
  events:
    onSelect:
  body:
    Column:
      onTap:
        dispatchEvent: 
          onSelect:
      styles:
        padding: 16
        backgroundColor: grey
      children:
        - Button:
            label: ${label}
            onTap:
              dispatchEvent:
                onSelect:
```

I get the following error from the above:

```
StackTrace :  TypeError: null: type 'minified:ads' is not a subtype of type 'minified:OV'
    at Object.e (https://studio.ensembleui.com/preview/main.dart.js:5040:19)
    at Object.ds4 (https://studio.ensembleui.com/preview/main.dart.js:5778:18)
    at PU.dXK [as a] (https://studio.ensembleui.com/preview/main.dart.js:5773:3)
    at Object.di3 (https://studio.ensembleui.com/preview/main.dart.js:14491:28)
    at Object.d79 (https://studio.ensembleui.com/preview/main.dart.js:14699:28)
    at Object.aE (https://studio.ensembleui.com/preview/main.dart.js:14566:32)
    at by0.$1 (https://studio.ensembleui.com/preview/main.dart.js:105232:17)
    at SP.kY (https://studio.ensembleui.com/preview/main.dart.js:119557:15)
    at Object.ld (https://studio.ensembleui.com/preview/main.dart.js:21739:23)
    at cAb.$2 (https://studio.ensembleui.com/preview/main.dart.js:102973:8)
TypeError: null: type 'minified:ads' is not a subtype of type 'minified:OV'
```
