### ISSUE TITLE
File upload widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#129]
User can access and upload the device's files via an Ensemble Action (e.g. button click).
Here's a sample action (also see showDialog action for implementation reference):
```yaml
Button:
  label: Select from your Gallery
  onTap:
    action: uploadFiles
    options:
      maxCount: 1              # see below for all options
    onComplete:
      //@code
      # access to the files here, which could be empty
```
When this action is taken, prompt for permission and open the Photo Gallery for selecting files.

These are all the options:
- maxCount: integer (DEFAULT 1). The max number of files allowed.

Items to think about (don't implement yet):
- file type filters
