### ISSUE TITLE
Need a loading state in button

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1296]
Whenever user taps on a button there are usually 2 usecases
1. navigate screen
2. call api => usually followed by navigate screen or any other action

If its a button with api call, it feels like a lag between pressing button and action on response. to solve that we need a loading state which will tell user the action is in loading state. Right now to do this I have created a custom widget which takes inputs and based on that shows loading if the button is in loading state.

Here is an example of Loading Button
LoadingButtonExample: https://studio.ensembleui.com/app/SwwVfRhzrvsumCbDi1rE/screen/9t2oDC0WNaYC9pI98zM0
LoadingButton (Widget): https://studio.ensembleui.com/app/SwwVfRhzrvsumCbDi1rE/widget/KhTDq4Rn1aCWFCGPCS4r

This is already super complex and still unable to meet all the use cases i.e I have right now 3 versions of loading buttons to support my use cases. In this example first click on `continue`, it will show you some users, now click on add button 1 by 1, it will act weird.

It should be as simple as this

```yaml
Button:
  label: Continue
  loadingIndicator:
     Progress:
        #any configuration for Progress widget
  loading: ${getPeople.isLoading} #whether to display or not, could be bound to anything

```
