### ISSUE TITLE
Add the ability to play an audio file as an action

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1303]
App developers should be able to configure playing an audio file (any audio file) as an action in EDL or through javascript. 

- audio files could be specified as a url
- audio files could be specified as assets

**Comment by kmahmood74** [comment]
EDL from @hemish11 in the PR - 

```yaml

View:
  header:
    title: Audio Player
  styles:
    scrollableView: true

  body:
    Column:
      styles:
        gap: 16
        padding: 24
      children:
        - Button:
            label: Play Audio
            onTap:
              playAudio:
                source: "https://file-examples.com/storage/fecea16b5a65ec8d9978112/2017/11/file_example_MP3_700KB.mp3"
                volume: 1 # 0 to 1
                balance: 0 # -1 to 1
                position: 2 # in seconds
                onComplete:
                  executeCode:
                    body: |
                      console.log("Audio Played");

        - Button:
            label: Pause Audio
            onTap:
              pauseAudio:

        - Button:
            label: Stop Audio
            onTap:
              stopAudio:

        - Button:
            label: Resume Audio
            onTap:
              resumeAudio:

        - Button:
            label: Seek Audio at 4 second
            onTap:
              seekAudio:
                position: 2
```
