### ISSUE TITLE
Support all inputTypes for TextInputs that are available in Flutter

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1313]
We are missing the following, please add support for the following, update schema, kitchen sink and documentation

TextInput's `inputType`
1. `number`
We have the `number` inputType but it lacks the options. Add number options as follows. They should take effect only if the input type is number

```yaml
TextInput:
  inputType: number
  inputTypeOptions:
     signed: true | false
     decimal: true | false
```
2. `name`
3. `streetAddress`
4. `none` - doesn't show any keyboard
