### ISSUE TITLE
Date input in disabled state allows user to clear value

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1341]
Date input with `enabled: false` still shows an `x` icon that user can taps and clears the value.

When disabled, the `x` icon should not appear.

```yaml
        - Date:
            initialValue: 2021-01-20
            enabled: false
            showCalendarIcon: false
```
