### ISSUE TITLE
Add support for passing inputs to ViewGroups

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1345]
Today `ViewGroup` is missing a lot of functionality. One main use case is adding support for passing `inputs` when calling (`navigate-view-group`)[https://docs.ensembleui.com/actions/navigate-view-group]

Within the ViewGroup, you should be able to use expressions to dynamically assign properties/evaluate inputs. 

suggested yaml - 

```yaml
navigateViewGroup:
  viewIndex: 1
  inputs:
    foo: bar
```
