### ISSUE TITLE
parameters don't accept JS

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1357]
I have to send the parameters to the api dynamically i.e based on some conditions, for that I've a JS function that takes care of that, but when I pass that function to the parameters it doesn't work.

```yaml
verify:
    inputs:
      - otp
    method: POST
    url: ${env['url_'+ensemble.storage.db]}/api/v3/auth/authenticate-via-phone-number-and-otp
    headers:
      Authorization: Bearer 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b
    parameters: ${getParameters(otp)}
```

```js
function getParameters(otp) {
    var paramerters = {};
    paramerters.phone_number = ensemble.storage.phoneNumber;
    paramerters.otp = otp;
    if (ensemble.storage.MyPlaceBranchData != null) {
      var branchData = ensemble.storage.MyPlaceBranchData;
      if (branchData != null) {
        if (branchData.url_type == 'group_invite_link') {
          paramerters.group_id = branchData.group_id;
        } else if (branchData.url_type == 'property_share_link') {
          paramerters.share_id = branchData.share_id;
        } else if (branchData.url_type == 'user_invite_link') {
          paramerters.invite_id = branchData.share_id;
        }
      }
    }

    return paramerters;
  }
```

This same function works if we send the data to body instead of parameters even though both have same structure.
