### ISSUE TITLE
Firestore Integration: support for creating documents, collections etc in js

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1360]
also includes wrapping types such as FieldValue, Timestamp etc

**Comment by kmahmood74** [comment]
added support for FieldValue operations. https://firebase.google.com/docs/reference/js/v8/firebase.firestore.FieldValue
@TheNoumanDev see methods in EnsembleFieldValue.methods and document. They are identical to the methods that are available in js so use chatgpt to generate and link to the firebase documentation (above link) as well

**Comment by kmahmood74** [comment]
see https://studio.ensembleui.com/app/FtoObiLOPh1Mgp7ceOko/screen/71kVbr62Kz655kV3JDM0 for example

**Comment by kmahmood74** [comment]
cc @amin-nas 
```yaml
  createMatch:
    inputs:
      - competitionId
    type: firestore
    path: sports/soccer/competitions/${competitionId}/matches
    operation: add
    data:
      teams: ["Germany", "Croatia"]
      venue: "Johan Cruyff Arena"
      matchTime: "2022-07-15T18:00:00Z"
      score: { Germany: 2, France: 1 }
      createdAt: ${FieldValue.serverTimestamp()}
```
