### ISSUE TITLE
API Regression

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1361]
### Issue:

The api is getting called multiple times

### Steps to reproduce:
- Use the following EDL 
- Hot Restart the app click the continue button, you'll see onResponse's log multiple time in the console. 

### Things to note:
Might need to hot restart the app multiple time to see the bug.

```yaml
View:
    # Optional - style the screen
    styles:
      scrollableView: true

    # Optional - set the header for the screen
    header:
      title: Home

    # Specify the body of the screen
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
          - Text:
              text: Hi there!
          - LoadingButton:
              inputs:
                isEnabled: true
                isLoading: ${sendOTP.isLoading}
                enabledColor: 0xFFFFFFFF
                disabledColor: 0xFF799290
                stretched: true
                bgColor: 0xFF425C5A
                padding: 24
                backgroundColor: 0xfff2f2ed
              events:
                onTapEvent:
                  invokeAPI:
                    name: sendOTP
                    onResponse:
                      navigateScreen:
                        name: verifyNumber
                    onError:
                      executeCode:
                        body: |
                          //@code
                          ensemble.storage.enable = true;
                        onComplete:
                          showDialog:
                            body:
                              ErrorDialog:
                                inputs:
                                  message: ${response.body.errors[0].message}
                            options:
                              style: none

LoadingButton:
  inputs:
    - isEnabled
    - isLoading
    - enabledColor
    - disabledColor
    - stretched
    - bgColor
    - padding
    - label
    - expanded
    - outline
    - fontSize
    - fontWeight
    - startingIcon
    - iconLibrary
    - iconColor
    - iconSize
    - gap
    - iconName
    - backgroundColor
  events:
    onTapEvent:
      data:

  body:
    Column:
      styles:
        crossAxis: "${stretched == false ? 'start' : 'stretch'}"
        padding: ${padding}
        expanded: "${expanded ? expanded : false}"
        backgroundColor: ${backgroundColor}
      children:
        - Row:
            id: loading
            styles:
              visible: ${isLoading == true}
              expanded: "${expanded ? expanded : false}"
              backgroundColor: "${bgColor ? bgColor : 0xFF425C5A}"
              width: 80
              height: 44
              padding: 8
              borderRadius: 12
              mainAxis: center
              crossAxis: center
            children:
              - Progress:
                  display: circular
                  styles:
                    color: "${enabledColor ? enabledColor : 0xFFFFFFFF}"
                    size: 20
        - Conditional:
            conditions:
              - if: ${startingIcon}
                Button:
                  id: continue
                  submitForm: true
                  label: "${label ? label : 'Continue'}"
                  enabled: ${isEnabled}
                  gap: ${gap}
                  startingIcon:
                    name: "${iconName}"
                    library: "${iconLibrary ? iconLibrary : default}"
                    color: "${iconColor ? iconColor : 0xff524e43}"
                    size: "${iconSize ? iconSize : 25}"
                  styles:
                    visible: ${!isLoading}
                    outline: "${outline ? outline : false}"
                    expanded: "${expanded ? expanded : false}"
                    borderRadius: 16
                    backgroundColor: "${bgColor ? bgColor : 0xFF425C5A}"
                    height: 44
                    labelStyle:
                      color: "${isEnabled ? (enabledColor ? enabledColor : 0xFFFFFFFF) : (disabledColor ? disabledColor : 0xFF799290)}"
                      fontSize: "${fontSize ? fontSize : 13}"
                      fontWeight: w500
                  onTap:
                    dispatchEvent:
                      onTapEvent:
                        data:
              - else:
                Button:
                  id: continue
                  submitForm: true
                  label: "${label ? label : 'Continue'}"
                  enabled: ${isEnabled}
                  styles:
                    visible: ${!isLoading}
                    outline: "${outline ? outline : false}"
                    expanded: "${expanded ? expanded : false}"
                    borderRadius: 16
                    backgroundColor: "${bgColor ? bgColor : 0xFF425C5A}"
                    height: 44
                    labelStyle:
                      color: "${isEnabled ? (enabledColor ? enabledColor : 0xFFFFFFFF) : (disabledColor ? disabledColor : 0xFF799290)}"
                      fontSize: "${fontSize ? fontSize : 13}"
                      fontWeight: w500
                  onTap:
                    dispatchEvent:
                      onTapEvent:
                        data:


API:
  sendOTP:
    method: GET
    url: https://randomuser.me/api/?results=6
    onResponse: |
      console.log(response.body);
      
```
