### ISSUE TITLE
Cannot select widgets for testing when the WeeklyScheduler is in the view

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1382]
- In screen where WeeklyScheduler is displayed, the switch above it is not reachable.

![image](https://github.com/EnsembleUI/ensemble/assets/491202/f079b766-4819-489c-885d-c15c456512ed)

**Comment by kmahmood74** [comment]
already communicated with @amin-nas 

All you need to do is to remove scrollable: true from the Column under Schema i.e. 
```yaml
Schema:
  onLoad:
    invokeAPI:
      name: getTime
      onResponse:
        invokeAPI:
          name: getSchedule
          onResponse: |
            //@code
            response.body.data.scheduleInfo[0].schedule.map(function(range) {
              wifiScheduler.addSelectedRange(range.begin, range.end);
            });
            wifiScheduler.refresh();

  Column:
    styles: { **scrollable: true**, padding: 16, mainAxisSize: max, backgroundColor: 0xffeaeaea }
```
remove the scrollable: true

semantics break when there are multiple nested scrollable columns. I don't think you need scroll on this anyway as the outside page scrolls already.
