### ISSUE TITLE
App-wide theming for primary and screen loading colors

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1390]
I want to be able to set following properties in a theme (e.g. light/dark theme) so that when user switches the theme, the style changes:

1. primary
2. loadingScreenBackgroundColor
3. loadingScreenIndicatorColor

## example

```yaml
Light:
  Styles:
    App:
      primary: blue
      loadingScreenBackgroundColor: white
      loadingScreenIndicatorColor: 0xFFDEDEDE

Dark:
  Styles:
    App:
      primary: blue
      loadingScreenBackgroundColor: black
      loadingScreenIndicatorColor: 0xFF202020
```
