### ISSUE TITLE
Ability to get device's wifi signal strength

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1392]
As an app developer, I want to get the current wifi connection details, including signal strength, so I can show the wifi quality to the user.

### Proposed EDL

```yaml
View:
  onLoad:
    getDeviceWifi:
      id: myWifi
      onReceived: 
         # provide a map of result here
      onError:
      onCompleted:
      options:
        recurring: false # default
        repeatInterval: 
        maxNumberOfTimes:

  body:
    Column:
      item-template:
         data: ${myWifi.data}
         name: w
         template:
           Text:
             text: ${w}
```
