### ISSUE TITLE
Firebase listenForChanges break when pointing to a document

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1399]
Using `listenForChanges` works for collections, but throws this error for documents:

```
FirebaseError: [code=invalid-argument]: Invalid collection reference. Collection references must have an odd number of segments, but sports/soccer/competitions/akmkihra9ruad09ljapsm84b3/tournamentCalendar/19x9mz32ti233f90h6htylf6c/matchStats/62tljlp4jfc8oqqts48lan7ys has 8.
```

Example API call:

```
  getMatcheDetails:
    inputs:
      - competitionId
      - calendarId
      - matchId
    type: firestore
    listenForChanges: true
    path: sports/soccer/competitions/akmkihra9ruad09ljapsm84b3/tournamentCalendar/19x9mz32ti233f90h6htylf6c/matchStats/63erujyeo8li6e3slgnudp79w
```
