### ISSUE TITLE
Blocker: inputs of a customwidget are not available in the widgets onLoad

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1406]
Thanks @amin-nas for finding it. 

Try this yaml, the `console.log(message)` prints null. `message` input is perfectly fine and it shows up fine in text

```
View:
    # Optional - style the screen
    styles:
      scrollableView: true

    # Optional - set the header for the screen
    header:
      title: Home

    # Specify the body of the screen
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
          - Text:
              text: Hi there!
          - MyWidget:
              inputs:
                message: HelloWorld

MyWidget:
  inputs:
    - message
  onLoad:
    executeCode:
      body: |
        console.log(message);
  body:
    Text:
      text: ${message}

```
