### ISSUE TITLE
Translations are not returned in showToast's message

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1408]
Sample screen:
https://studio.ensembleui.com/app/93ifQBH0dyAA5FO50Lri/screen/zmjMyp1I7svJhHJt1AFf

Steps to reproduce:

1. Create a EN translation and add this to it:

```yaml
home:
  greeting: test
```

2. Create a screen:
```yaml
View:
  body:
    Column:
      styles:
        padding: 24
      children:
        - Text:
            styles:
              textStyle:
                fontSize: 30
            text: r@home.greeting
  onLoad:
    showToast:
      message: r@home.greeting
```

3. Message is not returned inside the toast

![image](https://github.com/EnsembleUI/ensemble/assets/491202/2abbc62d-6d3e-4222-911d-436e26e368a4)
