### ISSUE TITLE
Binding a widget inside item-template to an API does not re-render widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1409]
Test screen:
Amin to add

When I have an item-template where the data and the template bind to two different API calls, the inner widget binding does not rer-ender when the API is called again.

e.g. in this example, when `getUserFavorites` is called again, MyCustomWidget does not render again.

```yaml
Column:
  item-template:
    data:  ${getList.body}
    name: item
    template:
      MyCustomWidget:
        inputs:
          id: ${item.id}
          favorites: ${getUserFavorites.body}
 ```
