### ISSUE TITLE
Cannot use multiple classNames on one widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1412]
Test screen:
https://studio.ensembleui.com/app/M9ANAafbHj3nGzhDWk7w/screen/QJCeMBPiyOqr6imZzu11

I want to be able to set multiple classed on one widget:
```yaml
          - Text:
              text: Large and Bold
              className:  fontL fontBold
```
