### ISSUE TITLE
Support margin & padding directions 

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1422]
Support margin & padding directions :

- marginLeft
- marginRight
- marginTop
- marginBottom

<hr>

- paddingLeft
- paddingRight
- paddingTop
- paddingBottom

usecase:
I have these classes
```yaml
.marginLeftXL:
    style:
      margin:  0 0 0 20

.marginTopXL:
    style:
       margin:  20 0 0 0
```
And I want to use them instead of hardcode the margin:
```yaml
Button:
   className:  marginLeftXL marginTopXL
    label: "Example"
```
it will take only marginTopXL instead of combine both
