### ISSUE TITLE
Ability to set sort direction when querying Firestore

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1430]
In this example, I get result in ascending order.  I want to be able to make it in descending order.

```
  getMatches:
    inputs:
      - competitionId
      - calendarId
    type: firestore
    path: sports/soccer/competitions/${competitionId}/tournamentCalendar/${calendarId}/matchStats
    query:
      orderBy:
        - "matchInfo.dateTime"
  ```

**Comment by kmahmood74** [comment]
```
    query:
      orderBy:
        - "matchInfo.dateTime": {descending: true}
      limit: 20
```
