### ISSUE TITLE
Ability to configure text scaling 

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1432]
## Background

Users can increase text size from their device settings. Here's the same page, and how it looks as user changes device setting.

![Frame 1](https://github.com/EnsembleUI/ensemble/assets/491202/f751d357-7771-4d4e-99c3-815dc294bab0)

## Requirements

As an app developer, I want to control text scaling in my app.

In priority order, we should support the following:

0. As we do today, by default, respect user choice and adjust text size based on user preferences.
1. Provide ability to disable text scaling globally. 
```yaml
# in theme
Text:
  textScaling: false
```

2. Provide ability to set min and max scaling factors globally
```yaml
# in theme
Text:
  maxScaleFactor: 1.2 # so that the text never increases more than 20%, even if user settings indicate to increase it by 50%
  minScaleFactor: .8 # so that the text never decreases more than 20%, even if user settings indicate to decrease it by 50%
```
3. Provide ability to override the global setting at widget level. E.g. I want to allow scaling across the accept except for a specific widget.

## Flutter reference

https://api.flutter.dev/flutter/painting/TextScaler-class.html
