### ISSUE TITLE
Action to get network info

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1433]
As an app developer, I want to get the current device connection details, including IP address

https://pub.dev/packages/network_info_plus

### Proposed EDL

```yaml
View:
  onLoad:
    getNetworkInfo:
      onError:
      onCompleted:
         # provide a map of result here
```

**Comment by kmahmood74** [comment]
@amin-nas I think this is more similar to camera or contacts than notifications. With notifications, you just check the permissions but don't do anything with it. Here you need to get some info. It's like camera permissions. 

We don't need checkPermission for this one as just calling the action would return whether the user gave the permission or not. 

Also it's 3 possibilities - 

onError - when there is an error getting the info (check if this is a valid condition @reubensjohn )
onSuccess
onDenied

**Comment by amin-nas** [comment]
@kmahmood74 makes sense - For contacts, we seem to only support `getPhoneContacts` if the docs are up-to-date.

Modeling this after contacts, we could do:

```
View:
  onLoad:
    getNetworkInfo:
      onSuccess:
         # provide a map of result here
       onDenied:
      onError:
```

Assumptions:

- if this is the first time app is triggering this action, user will be prompted to give permission.
- if user has previously granted the permission, onSuccess will automatically be triggered.
- if user has previously denied the permission, I believe the OS will not trigger the pop up again. In this case, we should trigger the onDenied so that the app developer can show proper messaging to user.
