### ISSUE TITLE
BUG: Map widget loads really slow

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1443]
If we use marker widget e.g avatar it take 30-60 sec to load the map avatar

```yaml
markers:
                  data: ${propertyMap.body.results}
                  name: record
                  location: ${formatCoordinates(record.location.coordinates).latitude} ${formatCoordinates(record.location.coordinates).longitude}
                  marker:
                    widget:
                      Avatar:
                        source: ${record.owner.avatar.image.small}
                        name: ${record.owner.first_name} ${record.owner.last_name}
                        variant: rounded
                        nameTextStyle:
                          color: 0xff4b483d
                          fontSize: 12
                          fontWeight: bold
                        styles:
                          height: 44
                          width: 44
                          fit: cover
                          borderRadius: 16
                          borderWidth: 2
                          borderColor: white
                          backgroundColor: 0xfff2f2ed
                          margin: 0 8 0 0
```
