### ISSUE TITLE
Division and multiplication support in inline expressions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#148]
```
View:
  Column:
    styles: { padding: 20 }
    children:
      - Text:
          text: ${100}        # prints 100
      - Text:
          text: ${100 - 10}   # prints 90
      - Text:
          text: ${100 * 2}    # prints ${100 * 2}
      - Text:
          text: ${100 / 2}    # prints  ${100 / 2}
```
