### ISSUE TITLE
Extra Space with Group Avatars

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1483]
while using group-template of avatars, it adds some extra space after the avatars, results in creating unnecessary blank space after the group avatars, there is no property to remove it for now
here is the sample code for that

```yaml
- Row:
                  styles:
                    crossAxis: center
                    visible: ${people.mutual_friends_count != 0}
                    gap: 0
                  children:
                    - Avatar:
                        group-template:
                          data: ${people.mutual_friends}
                          max: 3
                          name: contact
                          offset: 10
                          surplus: 
                            visible: false
                          surplusVisible: false
                          template:
                            name: ${contact.firstName} ${contact.lastName}
                            source: ${contact.avatar.image.small}
                            styles:
                              height: 16
                              borderRadius: 9
                              borderWidth: 2
                              borderColor: 0xffe3e3db
                              fit: cover
                              backgroundColor: white
                            nameTextStyle:
                              color: 0xFF4B483D
                              fontSize: 10
                              fontWeight: w300
                    - Text:
                        text: ${people.mutual_friends_count} mutuals
                        styles:
                          textStyle:
                            color: 0xFF4B483D
                            fontSize: 10
                            fontWeight: w300
```
