### ISSUE TITLE
Stripe Integration Support

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1485]

**Comment by kmahmood74** [comment]
this should be done as a separate module

**Comment by hemish11** [comment]
Heres the EDL:
```yaml
createPaymentMethod:
  email: ${email}  # Email of the customer
  phone: ${phone}  # Phone number of the customer
  city: ${city}
  country: ${country}
  line1: ${line1}
  line2: ${line2}
  postalCode: ${postalCode}
  onSuccess: |-
    //@code
    statusText.text = 'Payment method created successfully: ' + paymentMethod.id;
  onError: |-
    //@code
    statusText.text = 'Error creating payment method: ' + error.message;

# Action to confirm payment
confirmPayment:
  clientSecret: ${clientSecret}  # The client secret received from the backend
  paymentMethodId: ${paymentMethodId}  # ID of the payment method created
  onSuccess: |-
    //@code
    statusText.text = 'Payment confirmed successfully: ' + paymentIntent.id;
  onError: |-
    //@code
    statusText.text = 'Error confirming payment: ' + error.message;

# Action to handle Stripe setup
initializeStripe:
  publishableKey: ${publishableKey}  # Your Stripe publishable key
  onSuccess: |-
    //@code
    statusText.text = 'Stripe initialized successfully';
  onError: |-
    //@code
    statusText.text = 'Error initializing Stripe: ' + error.message;
```
