### ISSUE TITLE
Configurable option for webview in native apps to follow url schemes such as `tel:`, `mailto:` etc

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1489]
New webview option - 

```yaml
WebView:
  allowUrlSchemes:
    - "tel:"
    - "geo:"

```
When allowUrlSchemes is not present, by default the following schemes are permitted. But apps can override the defaults by specifying the allowUrlSchemes. In order to add additional schemes to the default schemes, specify the default schemes and the additional schemes as an array value of allowUrlSchemes
