### ISSUE TITLE
Ability to dismiss toast when view changes

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1493]
Currently, a toast message stays on top of view when user navigates between screens. Example:
https://studio.ensembleui.com/app/63jj6KiQ1jHhXCBPvgSt/screens

I want to be able to set a toast to be specific to the current screen so that if the view changes, the toast is dismissed automatically.

## Use case:
1. User enters a password on a login screen
2. If password is inaccurate a toast message is displayed
3. When user re-enters the password and logs in, user is taken to Home screen
4. I want the toast to be automatically dismissed

## Proposed property

```yaml
showToast:
  options:
    dismissOnNavigate: true # default is false
```

Alternatively, we could also expose an action to dismissToast. Then app developer can decide when to trigger this.

**Comment by hemish11** [comment]
Sample EDL:

```yaml
View:
  title: "Action: navigateScreen"
  styles:
    scrollableView: true

  body:
    Column:
      styles:
        gap: 16
        padding: 24
      children:
        - Button:
            label: Show Success
            onTap:
              showToast:
                message: Success! by default at screen's top right
                options:
                  dismissable: true
                  type: success
                  duration: 3
                styles:
                  backgroundColor: 0xFFEDEDED
                  padding: 16 24

        - Button:
            label: Show Modal
            onTap:
              navigateModalScreen:
                name: Hello Home

        - Button:
            label: Navigate and clear all screen history
            onTap:
              navigateScreen:
                name: Hello Home
                options:
                  clearAllScreens: true
                  closeToasts: true
```
