### ISSUE TITLE
Complex calculation is not returning value

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#150]
```
View:
   Column:
     children:
       - Text:
           text: ${Math.floor(device.width / 2) - ((48 * 2 + 12)/2) }
```
