### ISSUE TITLE
Ability to set theme per language

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1505]
Currently, I can set font family globally and per widget using `fontFamily`. I want to be able to set this value for each language supported by my app, along with a default.

Suggested EDL (feel free to come up with a better approach)

```
MyTheme:
  Styles:
    Text:
       textStyle:
          fontFamily:
             en: Montserrat
             ar: Tajawal
             default: Montserrat
```

Make it backward compatible, i.e. existing way of setting this should continue to work:

```
MyTheme:
  Styles:
    Text:
       textStyle:
          fontFamily: Montserrat
```
