### ISSUE TITLE
firestore: support for aggregate functions like sum() and average()

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1507]
Flutter has added support for aggregate functions in firestore so ensemble should also provide support for it as its the basic function that every developer use.

**Comment by kmahmood74** [comment]
@TheNoumanDev post the sample EDL here. Make sure that is always part of the ticket.

**Comment by TheNoumanDev** [comment]
Sample EDl

```yaml
View:
    header:
      title: Firestore Operations
      styles:
         surfaceTintColor: transparent

    onLoad:
      invokeAPI:
        name: getProjectsFileSum

    body:
      Column:
        styles:
          mainAxis: center
          crossAxis: center
        children:
          - Text:
              text: ${getProjectsFileSum.body['sum']}
              styles:
                textStyle:
                  fontWeight: bold
                alignment: center

API:
  getProjectsFileSum:
    inputs:
      - userId
    type: firestore
    path: users/${userId}/Projects
    aggregate:
      type: sum # that could be average/count
      field: filesCount # field is required for sum/average
```
