### ISSUE TITLE
Conditional widget recreates child on updates, causing UI inconsistency in stateful widgets like TabBar

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1511]
## Description
When using a Conditional widget with a stateful child like TabBar, updates to the condition cause the child to be recreated from scratch. This leads to loss of state and unexpected UI behavior, particularly noticeable with widgets that maintain internal state like TabBar.

## Current Behavior
1. The Conditional widget re-evaluates its condition when data changes (e.g., from a live API update).
2. Upon re-evaluation, it recreates its child widget (TabBar in this case) using `buildWidgetFromDefinition`.
3. The new TabBar instance is created with its default state (e.g., selected index 0).
4. This causes the UI to "jump" to the default tab, even if the user was on a different tab before the update.

## Example code to reproduce. 
```yaml
View:
  styles:
    useSafeArea: true

  header:
    titleText: Tab issue
  

  onLoad: 
    invokeAPI:
      name: getUsers
      

  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - Conditional:
            conditions:
              - if: ${ensemble.storage.data != null}
                widget:
                  TabBar:
                    id: liveTabBar
                    styles:
                      tabAlignment: center
                    items:
                      - label: Hello
                        widget:
                          Event:
                            inputs:
                              data: ${ensemble.storage.data}
                      - label: world
                        widget: 
                          Text:
                            text: world

Event:
  inputs:
    - data
  body:
    Text:
      text: ${data}


API:
  getUsers:
    type: firestore
    path: matches
    onResponse:
      executeCode:
        body: |-
          ensemble.storage.data = response.body.documents[0].data;
    listenForChanges: true
  ``` 
 
More context:-
Derived from ticket: https://github.com/EnsembleUI/ensemble/issues/1468
