### ISSUE TITLE
Support for collapsible Text widget

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1512]
Use Case: sometime text can be long. Showing all of it especially on a mobile device could take up all the space on the device. 
solution: provide the ability to expand and collapse the Text widget

```yaml
        Text:
            id: myText
            text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
              minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat. Duis aute irure dolor in
              reprehenderit in voluptate velit esse cillum dolore eu fugiat
              nulla pariatur. Excepteur sint occaecat cupidatat non proident,
              sunt in culpa qui officia deserunt mollit anim id est laborum.
            styles:
              maxLines: 3 #default: 3
              expandable: true
              expandLabel: keep reading ... #use tokens to translate into different languages 
              collapseLabel: show me less please ...
              expandTextStyle: #full textStyle for the text that is used to expand/collapse
                color: red
                fontSize: 14
```

**Comment by kmahmood74** [comment]
cc @vusters @amin-nas please review EDL.

**Comment by kmahmood74** [comment]
https://github.com/user-attachments/assets/e764fbb9-4c56-4710-a56b-859c53a04389

**Comment by kmahmood74** [comment]
https://github.com/user-attachments/assets/77aab1fb-039f-4b59-b07d-8a22c39c5b26

inside listview, doesn't work in DataGrid for some reason

**Comment by amin-nas** [comment]
@kmahmood74 why have a default for maxLines? I think there is no default for that property as of now

**Comment by kmahmood74** [comment]
The maxLines default is only when expandable == true. Otherwise there is no
default which is the current behavior

**Comment by amin-nas** [comment]
Here's my personal preference - go with what you like

```yaml
Text:
  expandable:
  expandLabel:
  collapseLabel:
  styles:
    expandLabelStyle:
```
