### ISSUE TITLE
Support for Firestore Timestamp

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1514]
I want to create Firestore timestamp so that I can query Firestore documents using the timestamp in the where clause.

Example:
```yaml
  getFutureMatches:
    type: firestore
    path: sports/match
    query:
      where:
        - field: "matchInfo.dateTime" # this is a Firestore timestamp field
          operator: ">"
          value: ${ new Date() }
      limit: 10
```

Example that works in JS:
```javascript
async function run() {
  const currentTime = admin.firestore.Timestamp.fromDate(new Date());
  const query = await db.collection("sports/match")
    .where('matchInfo.dateTime', '>', currentTime)
    .limit(50)
    .get();
  return query;
}
```
