### ISSUE TITLE
`TextInput` with inputType: phone and a mask never passes validation and thus the form can never be submitted

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1518]
```yaml
        - Form:
            children:
              - TextInput:
                  mask: "(###) ###- ####"
                  inputType: phone
                  placeholder: enter phone number
              - Button:
                  label: Validate and Submit
                  submitForm: true
```
will always fail to submit the form as the validation will be false even if the phone number is perfectly fine. The mask is being returned as part of the value which is incorrect. 

Sample page - https://studio.ensembleui.com/app/yBIvic1cHAkydEpPaL0R/screen/PXicL4n7DvLle7UviOr6#
