### ISSUE TITLE
TextInput's cursor is acting weirdly on real device

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1527]
i am trying to edit text in TextInput, so there should be some text in the TextInput beforehand, and when i click on the edit button from the bottom modal, then it is supposed to show the cursor after the text, but it is showing it weirdly, and it shows the cursor first, then it shows the text in the TextInput, what i want is, text should be there first, and cursor should appear after the text, so that user could edit the text easily... it is working fine for studio, but it is not working on ensemble preview.

here is the studio example for that:
https://studio.ensembleui.com/app/fvWvR0DqRko5dpkfI7v4/screen/Sslp51siQdNx0nbz9lqh

recording of this bug: 
https://drive.google.com/file/d/1oRpKJVA7Aj5BbYClVfx-gmgaNkkXhZok/view?usp=drive_link

**Comment by sharjeelyunus** [comment]
This issue is still there.
Steps : 
1. open dialog with TextInput (cursor will be at the end of the field) 
2. Move the cursor to the starting of field and type something => the cursor will move to last position.

CC: @snehmehta

**Comment by kmahmood74** [comment]
this was due to a bad app design where the the storage value that the field was bound to was being modified onKeyPress of the field. That's not right. I already proposed a design that works fine. Why do we need this?

**Comment by kmahmood74** [comment]
you need to set the value when closing the dialog. The app logic is missing that step. 

```yaml
        - Button:
            label: Save
            styles:
              margin: 16 0 0 0
            onTap:
              executeActionGroup:
                actions:
                  - executeCode:
                      body: |
                        ensemble.storage.announcementText = ensemble.storage.announcementText_live;
                  - dismissBottomModal:
         ```
