### ISSUE TITLE
Require Shimmer Effect property in LoadingContainer Widget

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1529]
Use Case:

The LoadingContainer component currently supports a **useShimmer** property, but this property is limited to a single type of shimmer effect, specifically diagonal shimmering. To improve the flexibility and customization of shimmer effects in our application, it would be beneficial to introduce a new property that allows for multiple shimmer effects such as diagonal, horizontal, vertical, etc.

What is Needed:

New Property: Introduce a new property named **shimmerEffect** to the LoadingContainer component. This property should accept a string or an enumeration that allows specifying different types of shimmer effects.

Effect Types: The shimmerEffect property should support multiple shimmer effect types.

**So the current requirements are the following:**

- Multiple Shimmer Effects (Horizontal, Vertical or Diagonal)
- Shimmer Animation Speed to control the speed of shimmer animation

**Comment by kmahmood74** [comment]
also need animation speed, customer specifically asked for that

**Comment by mehsaandev** [comment]
**Yes so the current requirements are the following:**

- Multiple Shimmer Effects (Horizontal, Vertical or Diagonal)
- Shimmer Speed to control the speed of shimmer property

**Comment by hemish11** [comment]
Sample EDL:
```yaml
View:
  header:
    title: LoadingContainer
  styles:
    scrollableView: true
  body:
    Column:
      styles:
        gap: 16
        padding: 20
        crossAxis: center
        mainAxis: center
      children:
        - LoadingContainer:
            id: loadingWidget
            isLoading: ${getBooleanValue()}
            shimmerEffect: horizontal
            shimmerSpeed: 1500
            useShimmer: true
            defaultShimmerPadding: 0 20
            widget: DataLoaded
            loadingWidget: ListViewLoader

        - Button:
            label: Change State
            onTap: |
              //@code
              loadingWidget.isLoading = !loadingWidget.isLoading;

DataLoaded:
  body:
    Text:
      text: Data State
      styles:
        textStyle:
          fontSize: 20

ListViewLoader:
  body:
    Column:
      styles:
        gap: 20
      children:
        - ListTile
        - ListTile
        - ListTile
        - ListTile
        - ListTile

ListTile:
  body:
    Row:
      styles:
        gap: 10
      children:
        - Shape:
            styles:
              height: 70
              width: 70
              borderRadius: 8
              backgroundColor: 0xFFF5F5F7
        - Column:
            styles:
              gap: 10
            children:
              - Shape:
                  styles:
                    height: 18
                    width: 260
                    borderRadius: 7
                    backgroundColor: 0xFFF5F5F7
              - Shape:
                  styles:
                    height: 16
                    width: 200
                    borderRadius: 7
                    backgroundColor: 0xFFF5F5F7

Global: |-

  function getBooleanValue() {
    return false;
  }
```

**Comment by kmahmood74** [comment]
@hemish11 suggest capturing shimmer related settings in a separate object - 

```yaml
- LoadingContainer:
         useShimmer: true
         shimmerOptions:
            shimmerEffect: horizontal
            shimmerSpeed: 1500
            padding: 0 20
```
once it's under it's own settings object, you can rename `defaultShimmerPadding` to just `padding`. Also no reason to call something `default`
