### ISSUE TITLE
State change breaks TextInput editing

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#1540]
Description: 
If the text input is subscribe to changes and user tries to edit the text it jumps text to end. Check the attached video 

Steps to reproduce:-
```yaml
View:
  styles:
    useSafeArea: true

  # Optional - set the header for the screen
  header:
    titleText: Test

  onLoad:
    executeCode:
      body: |
        ensemble.storage.announcementText = 'test';

  # Specify the body of the screen
  body:
    Row:
      styles:
        mainAxis: spaceBetween
        crossAxis: center
        padding: 24
        margin: 24
      children:
        - Text:
            text: ${ensemble.storage.announcementText}
            styles:
              padding: 16
              textStyle:
                fontSize: 16
                fontWeight: w500
                color: 0xFF4B483D
        - Icon:
            name: more_fill
            library: remix
            onTap:
              showBottomModal:
                body:
                  PostActionsSheet:
                styles:
                  backgroundColor: 0xfff2f2ed
                  barrierColor: 0x22000000
                  showDragHandle: false
                options:
                  enableDrag: true
                onDismiss:
                  dismissBottomModal:

PostActionsSheet:
  body:
    Column:
      styles:
        crossAxis: stretch
        mainAxisSize: min
        gap: 16
        padding: 24 16
        backgroundColor: 0xfff2f2ed
        borderRadius: 24 24 0 0
      children:
        - Button:
            label: Edit post
            styles:
              backgroundColor: 0xFFE3E3DB
              height: 44
              borderRadius: 16
              labelStyle:
                color: 0xFF4B483D
                fontSize: 13
                fontWeight: w500
            onTap:
              showBottomModal:
                body:
                  CreateAnnouncementPostModal:
                styles:
                  backgroundColor: 0xfff2f2ed
                  barrierColor: 0x22000000
                  showDragHandle: false
                options:
                  enableDrag: true
                onDismiss:
                  dismissBottomModal:

CreateAnnouncementPostModal:
  onLoad:
    executeCode:
      body: |
        //@code
        announcementTxt.focus();
  body:
    Column:
      styles:
        crossAxis: stretch
        padding: 24 16 40 16
        backgroundColor: 0xfff2f2ed
        borderRadius: 24 24 0 0
        mainAxis: spaceBetween
        mainAxisSize: min
        gap: 24
      children:
        - Row:
            styles:
              crossAxis: center
              gap: 24
            children:
              - Icon:
                  name: close
                  styles:
                    backgroundColor: 0xffe3e3db
                    padding: 12
                    size: 20
                    borderRadius: 16
                    color: 0xff4b483d
                  onTap:
                    dismissBottomModal:
              - Text:
                  text: Edit announcement
                  styles:
                    textStyle:
                      fontSize: 18
                      fontWeight: w700
                      color: 0xFF4B483D

        - TextInput:
            id: announcementTxt
            hintText: Only group admins can post announcements to groups
            value: ${ensemble.storage.announcementText}
            label: What would you like to say?
            multiline: true
            maxLines: 4
            styles:
              borderColor: 0xFFD6D6CE
              borderWidth: 1
              focusedBorderColor: "${ensemble.storage.announcementText.length > 240 ? 'red' : 0xFFD6D6CE}"
              fillColor: 0xFFF9F9F7
              labelStyle:
                fontSize: 13
                fontWeight: w500
                color: 0xFF4B483D
            hintStyle:
              fontSize: 13
              fontWeight: w300
              color: 0xFF858174
            onKeyPress:
              executeCode:
                body: |
                  //@code
                  ensemble.storage.announcementText = this.value;
        - Button:
            label: Save
            styles:
              margin: 16 0 0 0
            onTap:
              dismissBottomModal:

```
Go to this studio app
https://studio.ensembleui.com/app/fvWvR0DqRko5dpkfI7v4/screen/Sslp51siQdNx0nbz9lqh
Move cursor to middle of word and alter (add or remove character)

https://github.com/user-attachments/assets/5fbe5af1-eab3-426d-84e5-39cb4ed41d84
