### ISSUE TITLE
Require Touchable Opacity on tapping Rows and Column

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1546]
- Row and Column Widgets do have onTap to execute an action but when we touch on them, it just calls out the action and doesn't show any touchable response as Button widget does.
- Check the following link in which They created a Widget of TouchableOpacity and this widget can be wrapped around any other widget to make it touchable.
 https://stackoverflow.com/questions/54473908/can-i-get-the-same-effect-in-flutter-as-the-touchableopacity-in-react-native 

Requirements:
![image](https://github.com/user-attachments/assets/aca51b31-117f-4e87-ac6c-357447aebed2)
- When I click on Rows and Column there should be an option of having touch opacity rather than having no UI response and just triggering the action

Proposed Solution:
- Make a TouchableOpacity widget which should have widget attribute and onTap event. and widget Attribute can contain any widget and that widget will behave as Touchable component.

**Comment by vusters** [comment]
Button has ink effect, which manipulate the opacity for different states and can also take a custom child as body. Let me know if this is sufficient or you need the ability to modify the color and the opacity for each state.
```
- Button:
            styles:
              backgroundColor: amber
              borderRadius: 10
              elevation: 10
              elevationBorderRadius: 10
            body:
              Row:
                styles:
                  padding: 5
                children:
                  - Image:
                      source: ${getUsers.body.results[0].picture.medium}
                  - Column:
                      children:
                        - Text:
                            text: My title
                        - Text:
                            text: my subtitle
```
