### ISSUE TITLE
Custom Inline time picker

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1549]
we need a time picker for customer app, where first we have a option to select 'am' or 'pm' then there is time, user can scroll it up or down to select specific time, and the time that is being selected will be displayed on screen with formatting like '4:45 pm', like the one we use to set alarm in real device

here is the screenshot of what exactly we need to built:
https://imgur.com/sqwB6cL

**Comment by kmahmood74** [comment]
@hemish11 any update on this one, it shows in progress?

**Comment by hemish11** [comment]
Sample EDL:
```yaml
View:
  header:
    title: Inline TImePicker
  styles:
    scrollableView: true
  body:
    Column:
      children:
        - InlineTimePicker:
            id: timePicker
            initialTime: "11:44"
            mode: hms
            showHourLabel: false

        - Button:
            label: Get Time
            onTap: |
              //@code
              console.log(timePicker.selectedTime);
```

**Comment by hemish11** [comment]
@kmahmood74 here's the video of it's working:

https://github.com/user-attachments/assets/49af2ca4-0dac-4f48-90bd-ba5def68e560

**Comment by kmahmood74** [comment]
@hemish11 please implement the time picker as clearly described in the description of the ticket. You have implemented a duration widget and not a time widget.

**Comment by kmahmood74** [comment]
assigning to @TheNoumanDev Nouman, the PR that @hemish11 created does not provide the inline time picker, instead it provides a time range widget. Please ignore that PR and implement this ticket from scratch. 

We already have a `Time` widget. 

1. There should be a property on the time widget called `userIOSStyleTimePicker` as a boolean. This should be true by default on iOS and false on all other platforms. User can set it to false to override the default behavior on iOS as well. 
2. When set to true, the `CupertinoDatePicker` with the time mode should appear. 
3. Expose properties such as `use24hFormat` on the actual Time widget and make sure the existing time picker and the cupertino time picker both process these properties

Let me know if you have any questions. Also once you have it ready for testing, check with Ridsa to make sure her use case is covered, use her app to configure it under the calendar as she needs it and then test

@ridsashabbir the time picker will appear like this - 
<img width="332" alt="image" src="https://github.com/user-attachments/assets/a56a941e-b2f6-4d43-8a3f-0ff22d626f8d">

**Comment by TheNoumanDev** [comment]
Hey @kmahmood74! I’ve updated the Time widget as per your request and discussed the use case with Ridsa. However, she has a slightly different requirement:

- We currently have separate widgets for Time and Date, each opening its respective picker when the user clicks on the form field.
- However, according to the image she shared, she wants the Time widget to appear when the user selects a date from the calendar. In this use case, the Time picker should either be triggered as an action.

Do I need to change the implementation of the Time widget? Let me know what you think.

Below is the current implementation based on your initial description.                
![image](https://github.com/user-attachments/assets/863ba3de-b8ed-42a2-a056-1af4630b7897)

**Comment by kmahmood74** [comment]
@ridsashabbir which customer is this needed for? We'll keep date and time separate for now. That's a reasonable interaction.

**Comment by TheNoumanDev** [comment]
Created [PR](https://github.com/EnsembleUI/ensemble/pull/1626)
Example EDL:
```yaml
- Time:
            id: hello
            label: Example 1 - Time picker iOS
            hintText: Select a time
            required: true
            initialValue: '14:44'
            useIOSStyleTimePicker: true         
            # use24hFormat: true 
```
