### ISSUE TITLE
When using margin and padding in classes, Ensemble only applies the last class

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1563]
I have two classes
```yaml
Themes:
  - DefaultTheme:
      default: true

DefaultTheme:
  label: Default theme
  Tokens:
    VerticalSpacing:
      XL: 16
    HorizontalSpacing:
      XL: 16
.ML_XL: # ML stands for (margin left) & XL for HorizontalSpacing.XL
  margin: 0 0 0 ${HorizontalSpacing.XL}

.MT_XL: # MT stands for (margin top) & XL for HorizontalSpacing.XL
  margin: ${VerticalSpacing.XL} 0 0 0
```
when using these classes together ensemble take the last one
example:

```yaml
View:
    styles:
      scrollableView: true
    header:
      title: Home
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
           - Text:
                className: ML_XL MT_XL
                text: Hi

``` 
I can only see the MT_XL result
![image](https://github.com/user-attachments/assets/197d35e1-a322-4c4d-ad1a-ae0e8461f922)

The expected behavior is to merge both classes values so the margin should be like ```margin:${VerticalSpacing.XL} 0 0 ${HorizontalSpacing.XL}```

**Comment by kmahmood74** [comment]
it's working correctly. The last style is overwriting the previous one. 

```yaml
  Styles:
    .ML_XL: # ML stands for (margin left) & XL for HorizontalSpacing.XL
      margin: 0 0 0 ${HorizontalSpacing.XL}

    .MT_XL: # MT stands for (margin top) & XL for HorizontalSpacing.XL
       margin: ${VerticalSpacing.XL} 0 0 0
```
so when you do - 

```yaml
           - Text:
                className: ML_XL MT_XL
```
MT_XL's margin overrides the margin defined by ML_XL. This is working correctly.
