### ISSUE TITLE
Styles from the theme are not applied to the endingIcon of the Button

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1564]
I am trying to style endingIcon for button from Theme
I have multiple classes that change the button appearance and the style depends on the `Tokens` ,
so I need to change the endingIcon color according to the class.
Example:

Theme:

```yaml
Themes:
  - DefaultTheme:
      default: true

DefaultTheme:
  label: Default theme
  Tokens:
    Colors:
      primary: "#0F216B"
      onPrimary: "white"
    FontSizes:
      S: 16
  Styles:
    .primaryButton:
      backgroundColor: ${Colors.primary}
      labelStyle:
        color: ${Colors.onPrimary}
      endingIcon:
        size: ${FontSizes.S}
        color: ${Colors.onPrimary}
```
View:

```yaml
View:
    styles:
      scrollableView: true
      backgroundColor: green
    header:
      title: Home
    
    body:
      Column:
        children:
           - Button:
              className: primaryButton
              label: Hi
              endingIcon:
                library: remix
                name: close_fill

```
endingIcon dosn't take the style from Theme
![image](https://github.com/user-attachments/assets/73492a1d-15d6-4e07-9338-2f28a9a9b2e0)

**Comment by Mohammad-Al-Refai** [comment]
Also didn't show any icons next to the label

**Comment by Mohammad-Al-Refai** [comment]
@kmahmood74 is there any update on this issue

**Comment by kmahmood74** [comment]
hi @Mohammad-Al-Refai this is already supported and works fine. You are missing the `name` under `endingIcon` i.e.

```yaml
Themes:
  - DefaultTheme:
      default: true

DefaultTheme:
  label: Default theme
  Tokens:
    Colors:
      primary: "#0F216B"
      onPrimary: "white"
    FontSizes:
      S: 16
  Styles:
    .primaryButton:
      backgroundColor: ${Colors.primary}
      labelStyle:
        color: ${Colors.onPrimary}
      endingIcon:
        name: star
        size: ${FontSizes.S}
        color: ${Colors.onPrimary}
```
`name` is required as without it platform does not know which icon to use as endingIcon.
