### ISSUE TITLE
View > header: styles is not applied from Theme

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1565]
I am trying to  style View > header  from Theme,
example:
Theme:
```yaml
Themes:
  - DefaultTheme:
      default: true

DefaultTheme:
  label: Default theme
  Tokens:
    Colors:
      primary: "#0F216B"
      background: "#fafafa"


  Styles:
    # Defaults
    View:
      backgroundColor: ${Colors.background}
      header:
        styles:
          color: ${Colors.primary}
          backgroundColor: white
          surfaceTintColor: white
```
View:
```yaml
View:
    styles:
      scrollableView: true
    header:
      title: Home
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
          - Text:
              text: Hi
```
The changes doesn't applied to the header
![image](https://github.com/user-attachments/assets/8874cec0-a628-4b00-98a6-b45130c9d562)

**Comment by kmahmood74** [comment]
currently the only way to style the header in themes is to use classes. For example - 

```yaml
  Styles:
    # Defaults
    .header:
      color: ${Colors.primary}
      backgroundColor: green
      surfaceTintColor: black
```
```yaml
View:
  styles:
    useSafeArea: true

  # Optional - set the header for the screen
  header:
    titleText: Home
    className: header
```
we can keep your ticket open and see when we can get to it. But you shoud not be blocked
