### ISSUE TITLE
unified theming and themes by language code

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1576]
we can potentially enhance it later to do country specific locale based themes such as `en_US` instead of just `en` but for now language code is enough. 

```yaml
Themes:
  - Common
  - PrimaryTheme:
      default: true
  - SecondaryTheme
  - RTLTheme

LocaleThemes:
  en:
    - SecondaryTheme:
        default: true
    - PrimaryTheme
  ur:
    - RTLTheme
    - PrimaryTheme
  ar:
    - RTLTheme
```
logic:
- if locale themes have been specified, find the themes for the current language code. 
- If the currentTheme (if any) is in the list of themes for the language, don't do anything. This is to make sure if the user changes a language dynamically, we don't change the theme on the user as long as the current theme is in the list of allowed themes for that language
- if not, switch the theme to the default for that language

Unifying Flutter and Ensemble Themes
- Existing App/Screen/Widgets etc will continue to be supported outside themes but deprecated
- App and Screen will be included within the Theme definition and will work as-is
- `fontFamily` can be defined at the App level and will be inherited by all text everywhere including button labels, input field labels etc. But can be overwritten at the widget level
- Color will come under App
- `Widgets` tag will be removed (when under Theme) and widgets will be processed directly such as Button, Text etc by the `ThemeLoader`. ThemeLoader will pick the properties that it understands for each widget. 
- inheritance, overwrites, ID and class based styles will continue to work as-is. ID and class based styles overwrite what's defined at the App/Screen/WidgetName level

**Comment by kmahmood74** [comment]
cc @vusters @amin-nas working on the above design. kindly review to see if it meets the needs or needs changes?

**Comment by evshi** [comment]
@kmahmood74 what is the motivation for tying locale and theme together? Is it not enough for for a user to specify the theme and locale separately, but together? e.g. ensemble.setTheme, ensemble.setLocale? On first review, seems like a very narrow solution.

**Comment by kmahmood74** [comment]
> @kmahmood74 what is the motivation for tying locale and theme together? Is it not enough for for a user to specify the theme and locale separately, but together? e.g. ensemble.setTheme, ensemble.setLocale? On first review, seems like a very narrow solution.

The whole `LocaleThemes` section is optional. It is there only for use cases where customers want to define different theme per locale. 

Different locales especially the LTR vs RTL languages have different fontFamilies, fontStyles and sizes that are captured as themes. That's the customer's requirement. The issue with doing this in ensemble code is that you are doing it at runtime which essentially means that you are assigning a wrong theme through configuration and then flipping it in code. 

It is better to do this at the config level so that ensemble can detect the system locale and automatically apply the right theme instead of applying the wrong one first and then flipping it in code. That was the rationale behind it.

**Comment by kmahmood74** [comment]
sample - 

```yaml
# define your app theme here

Themes:
  # - Common
  - PrimaryTheme:
  - SecondaryTheme
  - RTLTheme:
      default: true

LocaleThemes:
  en:
    - SecondaryTheme:
        default: true
    - PrimaryTheme
  ur:
    - RTLTheme:
        default: true
    - SecondaryTheme
  ar:
    - RTLTheme

Common:
  Tokens:
    Colors:
      primary:
        '900': '#1A2A4C'
        '800': '#243B6A'
        '700': '#2F4D89'
        '600': '#0077B8'
        '500': '#0092E0'
        '400': '#33B8FF'
        '300': '#70CDFF'
        '200': '#ADE4FF'
        '100': '#D6F1FF'
        '50': '#EBF5FF'
        'red': red
        'blue': blue
        'green': green
        'black': black
  Styles:
    App:
      textStyle:
        fontFamily: Montserrat
        fontWeight: 'w500'
        fontSize: 80       
      textScale:
        maxFactor: 5
    Colors:
      primary: green

    Transitions:
      page:
        type: bottomToTop
        duration: 4 
    Screen:
      loadingBackgroundColor: blue
      backgroundColor: black
      Header:
        backgroundColor: black 
    Button:
      backgroundColor: ${Colors.green}
      labelStyle:
        fontSize: 80
    # .submitButton:
    #   backgroundColor: green

PrimaryTheme:
  label: Primary Theme
  description: This is the primary theme
  #inheritsFrom: Common
  Styles:
    App:
      fontFamily: Qwitcher Grypen
      # textScale:
      #   maxFactor: 10
    Text:
      textStyle:
        fontSize: 40


    Colors:
      primary: red

    Transitions:
      page:
        type: bottomToTop
        duration: 4 
    Screen:
      loadingBackgroundColor: orange
      backgroundColor: green
      Header:
        backgroundColor: blue 
    Button:
      labelStyle:
        fontSize: 40
    Input:
      labelStyle:
        color: orange
        fontSize: 40
        fontFamily: Roboto
      hintStyle:
        color: red
        fontSize: 30
        fontWeight: bold
        fontFamily: "Dancing Script"

SecondaryTheme:
  label: Seconday Theme
  description: This is the secondary theme
  #inheritsFrom: Common
  Styles:
    App:
      fontFamily: "Dancing Script"
      textScale:
        maxFactor: 10
      textStyle:
        fontWeight: 'w500'
        fontSize: 40
        color: black

    
    Colors:
      primary: black

    Transitions:
      page:
        type: bottomToTop
        duration: 4 
    Screen:
      loadingBackgroundColor: yellow
      backgroundColor: grey
      Header:
        backgroundColor: black 
    # Text:
    #   textStyle:
    #     fontSize: 40
    Button:
      backgroundColor: red
      labelStyle:
        fontSize: 40

    Checkbox:
      borderColor: green
      fillColor: orange
      borderWidth: 50
      labelStyle:
        fontSize: 100
    Input:
      hintStyle:
        fontSize: 90
        fontWeight: bold
        fontFamily: Crimson Pro
      labelStyle:
        fontFamily: Dancing Script

RTLTheme:
  label: Theme for RTL languages such as Urdu, Arabic etc
  description: This is the secondary theme
  #inheritsFrom: Common
  Styles:
    App:
      fontFamily: "Pacifico"
      textScale:
        maxFactor: 10
      textStyle:
        fontWeight: 'w500'
        fontSize: 80
        color: black
      
    Colors:
      primary: brown

    Transitions:
      page:
        type: bottomToTop
        duration: 4 
    Screen:
      loadingBackgroundColor: yellow
      backgroundColor: orange
      Header:
        backgroundColor: yellow 
    # Text:
    #   textStyle:
    #     fontSize: 40

    Button:
      labelStyle:
        fontSize: 80
    #     fontFamily: Crimson Pro
    Checkbox:
      borderColor: red
      fillColor: blue
      borderWidth: 10    
```

**Comment by amin-nas** [comment]
@kmahmood74 this might be a separate ticket but to make sure it is on your radar:

As an app developer, I want to be able to set a default theme for the OS Light appearance and another theme for OS Dark appearance.

I think what you have works as is, and we enhance with another prop:

```yaml
Themes:
  - Common
  - PrimaryTheme:
      default: true
  - DarkTheme:
      defaultForDark: true
```

iOS setting:

![Screenshot 2024-08-23 at 11 09 37 AM](https://github.com/user-attachments/assets/84825748-4176-4a98-8041-d1f1a8f6c32c)
