### ISSUE TITLE
Loading and Disabled state with custom widget support for buttons

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1584]
We can generalize this for all widgets and even generalize the idea of states (any named state) for all widgets but let's keep it simple for now. 

A common requirement is to do the following - 

1. Display the submit button in a disabled state unless user has entered all required input fields and the inputs are valid
2. While waiting for the server response, display the button in a 'loading' state. Many customers needs a unique widget for the loading state just like they do for the disabled state

customer achieve this today by creating custom widgets with much conditional logic to switch between different widgets for different states. It is complex and runs into limitations of custom widgets 

### Proposal - 

Allow users to specify custom widgets for loading and disabled states for buttons. 

proposed EDL:

```yaml
Button:
  isLoading: boolean
  loadingWidget: #any custom widget by name or inline
  disabledWidget: #any custom widget by name or inline
  onTap: #doesn't fire in loading or disabled states
```
You can then do - 
```yaml
Button:
  isLoading: ${myAPI.isLoading} #really simple, that's why I avoided the generic `state` enum
  enabled: true | false #Button in the loading state can be enable or disabled i.e. it can take onTap events if configured
  loadingWidget:
     Row:
       Image:
         ...
```
