### ISSUE TITLE
Generic widget states and ability to define data and widget for each (TBD)

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1586]
### Problem: 
a lot of the app code today is switching between widgets based on some condition. Conditional widgets are powerful but hard to build and maintain

### Proposal: 
a cleaner solution is to provide named states for all widgets and provide the ability to define widget for each state and the ability to switch states. 

#### Pre-defined states:
enabled, disabled
Example:

```yaml
TextInput:
  disabledWidget: MyReadOnlyText
```
See this for buttons - #1584 

#### app defined custom states
This is where it becomes powerful. Allow apps to define any named state on any widget and define a view (widget) for each state

Example:
```yaml
Row:
   id: transactions
   states: 
      noTransactionData: #any named state
          widget: NoTransactionsWidget
      hasTransactions:
         widget: TransactionWidget
      isLoading:
         widget:
           LoadingContainer:
    currentState: "${myAPI.isLoading ? 'isLoading' : (myAPI.body.data.txns != null ? 'hasTransactions': 'noTransactionData'}"
```
The elegance of this design is that it provide a simple state management for widgets and allows you to do things like - 

transactions.currentState
