### ISSUE TITLE
Need support for `tooltip`

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1628]
Need support for a Tooltip widget that allows users to view additional information when hovering or long-pressing on a widget. This would improve the user experience by offering helpful context or explanations for specific elements. Tooltips are essential for enhancing usability, especially in complex interfaces.

something like that.
![image](https://github.com/user-attachments/assets/14387c85-8592-4fe2-9f29-d8e6e8802ff8)

**Comment by TheNoumanDev** [comment]
Default for mobile is: `Tap`
Default for web is: `onHover`

Example EDL:
```yaml
ToolTip:
  message: "This is a tooltip"
  height: 100
  decoration:
    backgroundColor: grey
    borderRadius: 20
    borderColor: red
    borderWidth: 3
  textStyle:
    fontSize: 25
    fontWeight: bold
    color: '#D32F2F'
  child:  
    Text:
      text: I am inside ToolTip.
```
