### ISSUE TITLE
Require a Collapsable Widget 

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1629]
Require Collapsable widget which is called Accodion in Flutter

Following are my requirements Screens:
![image](https://github.com/user-attachments/assets/2be067f1-42ca-4bdb-a14d-05c24aff26f0)
![image](https://github.com/user-attachments/assets/4c4effd9-f52d-479f-9925-f81079290c4f)

Here's the Flutter Package for Accordion
 https://pub.dev/packages/accordion

**Comment by mehsaandev** [comment]
here's the EDL for Collapsable Widget of Ensemble React:

`Collapsible:
            headerStyle:
              headerBg: "#09090f"
              borderColor: "#09090f"
              textColor: "rgb(201, 205, 210)"
              fontSize: 17
            contentStyle:
              contentBg: "#09090f"
            expandIconPosition: "end"
            expandIcon: 
              name: Remove
              color: white
            collapseIconPosition: "end"
            collapseIcon: 
              name: Add
              color: white
            items:
              - key: "1"
                label: Testing Question
                children:
                  Text:
                    text: Testing Answer`

**Comment by TheNoumanDev** [comment]
Example EDL: 
```yaml
- Collapsible:
    isAccordion: true
    headerStyle:
      backgroundColor: red
      borderColor: green
      borderColorOpened: red
      backgroundColorOpened: grey
      borderWidth: 5
      borderRadius: 5
    contentStyle:
      backgroundColor: white
      borderColor: green
      borderWidth: 3
      horizontalPadding: 20
    flipRightIconIfOpen: true
    openAndCloseAnimation: true
    paddingBetweenOpenSections: 10
    paddingBetweenClosedSections: 10
    items:
      - header: 
          Text: 
            text: "Section 1 Heading"
        content: 
          Text: 
            text: "Section 1 Content"
        isOpen: true
        leftIcon:
          Icon: 
            name: code
      - header: 
          Text: 
            text: "Section 2 Heading"
        content: 
          Text: 
            text: "Section 2 Content"
        headerBackgroundColor: red
        contentHorizontalPadding: 40
        contentVerticalPadding: 20
        onOpenSection: 
          executeCode:
            body: |
              console.log('section 2 open');
        onCloseSection: |
          console.log("Section 2 closed");
```

**Comment by amin-nas** [comment]
The proposed EDL is not consistent with how we do other widgets. I suggest following changes:

1. Treat `Collapsable` as one accordion widget, and not a container widget where multiple items can be created. If I want to show multiple accordions, I would choose Column or Row and add children or item-template as I need. Then we dont need props like `paddingBetweenClosedSections`.

2. Follow how we use the property named `widget` and set the schema in a way that app developer gets InteliSense. For example, here is what Calendar widget looks like:

```yaml
        - Calendar:

            todayCell:
              widget:

            disableCell:
              widget:
```

Following that, we should do the following and get rid of `headerStyle` and `contentStyle`. App developer sets those on whatever widget they chose.

```yaml
        - Calendar:

            header:
              widget:

            content:
              widget:
```

cc @kmahmood74 @vusters
