### ISSUE TITLE
Eval and Binding not working on nested styles

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#163]
We only support data evaluation and binding on the first level of a widget's styles. Need to support nested expressions also.
e.g.
```
Column:
  styles:
    backgroundImage:
      source: ${myUrl}background.jpg
      fit: ${fitVariable}
```
Either changes to URL or fitVariable need to reload the backgroundImage.
