### ISSUE TITLE
Require Underline Color same as text Color 

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1631]
Problem:
Underline color always be Black regardless of the Text color.

Requirements:
- Underline color should be same as text color by default
- There should be a `decorationColor` property in case we want different underline color

**Comment by TheNoumanDev** [comment]
Example EDL
```yaml
Text:
  text: View Terms & Conditions
  styles:
    textStyle:
      fontSize: 16
      fontWeight: w600
      # color: red
      # decoration: underline
      # decorationColor: green
      # decorationThickness: 2
```
