### ISSUE TITLE
ViewGroup > items > I can't use Conditional as an item

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1633]
We have a feature and we need to show it for a specific app version and the entry point to the feature is an item in ViewGroup.

```yaml
ViewGroup:
  BottomNavBar:
    reloadView: true
    styles:
      backgroundColor: white
      color: 0xFF667685
      selectedColor: 0xff4393F1
    items:
      - icon:
          name: home_4_line
          library: remix
        label: "r@home"
        page: Home
        selected: "${selectedIndex == 0 ? true : false}"
      - icon:
          name: user_star_line
          library: remix
        label: "r@reviews"
        page: Reviews 
        selected: "${selectedIndex == 1 ? true : false}"
      - Conditional: # here
          conditions:
            - if: "${isFeatureEnabled}"
              icon:
                name: qr_scan_2_line
                library: remix
              label: "r@checkIns"
              page: QRClaims 
              selected: "${selectedIndex == 2 ? true : false}"
      - icon:
          name: list_check
          library: remix
        label: "r@transactions"
        page: Transactions
        selected: "${selectedIndex == 3 ? true : false}"
      - icon:
          name: account_circle_line
          library: remix
        label: "r@profile"
        page: Profile
        selected: "${selectedIndex == 4 ? true : false}"

Global: |-
  // Javascript code
  var isFeatureEnabled = true
```
Ensemble studio logs:
```
Error :  Language Error: Invalid page definition.
Please double check your page syntax.
```
 
![image](https://github.com/user-attachments/assets/fc43114f-68b7-4839-9173-3c3709d6166a)

**Comment by kmahmood74** [comment]
assigning to @TheNoumanDev Nouman, we can just support `visible` for each item in the `ViewGroup` Then the developer can just do - 

```yaml
ViewGroup:
  BottomNavBar:
    reloadView: true
    styles:
      backgroundColor: white
      color: 0xFF667685
      selectedColor: 0xff4393F1
    items:
      - icon:
          name: home_4_line
          library: remix
        label: "r@home"
        page: Home
        selected: "${selectedIndex == 0 ? true : false}"
      - icon:
          name: user_star_line
          library: remix
        label: "r@reviews"
        page: Reviews 
        selected: "${selectedIndex == 1 ? true : false}"
      - icon:
            name: qr_scan_2_line
            library: remix
          label: "r@checkIns"
          page: QRClaims 
          selected: "${selectedIndex == 2 ? true : false}"
          visible: "${isFeatureEnabled}" #<-- this is the change
      - icon:
          name: list_check
          library: remix
        label: "r@transactions"
        page: Transactions
        selected: "${selectedIndex == 3 ? true : false}"
      - icon:
          name: account_circle_line
          library: remix
        label: "r@profile"
        page: Profile
        selected: "${selectedIndex == 4 ? true : false}"
```
just make sure when an item is marked invisible, it does not take any space.
