### ISSUE TITLE
Require Swipe Functionality to ListView Item

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1646]
Requirements:
 - Require a swipe functionality in the ListView in which each item of the list is swipeable and on Swipe left, there should be an option of adding Action Button/Icon by which we can perform any action(e.g. Delete or Edit) on that item of the List
- e.g. images: 
1) Image Before Swipe:
![image](https://github.com/user-attachments/assets/13e560de-58f8-4582-9e89-36668cb9f0ff)

2) Image After Swipe:
![image](https://github.com/user-attachments/assets/43ea5c81-1ec5-4ccc-a125-de6cb654531d)

- After Swipe the Delete Icon is the action Button which will be able to delete that entry on API call.

**Comment by kmahmood74** [comment]
cc @vusters

**Comment by TheNoumanDev** [comment]
PR: https://github.com/EnsembleUI/ensemble/pull/1659

Example EDL:
```yaml
- ListView:
    id: listView
    styles: 
      expanded: true 
      enableSwipe: true # default is false to maintain backward compatability
      swipeAnimationDuration: 200 # miliseconds
      swipeThreshold: 0.2  # (means 20 percent of screen and 1 means 100%)
    swipeWidget:
      FlexRow:
        styles:
          height: ${device.height}
          backgroundColor: black
        children:
          - Icon:
              name: delete
              color: red
              onTap: |
                console.log("hello");
    children:
      - MyRow:
          inputs:
            p: ${users}
      - MyRow:
          inputs:
            p: ${users}
      - MyRow:
          inputs:
            p: ${users}
```
