### ISSUE TITLE
add support for automatically managing cookies when calling APIs

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1649]
Add a `manageCookies` option to each API. default is `false`. Only applicable to native apps. When true, automatically store and set cookies for the domain. Use the `cookie-jar` package. Must not impact the web.
also add `response.cookies` returns a map of all cookies for that domain.

CC: @kmahmood74

**Comment by TheNoumanDev** [comment]
Example EDL:
```yaml
getProducts:
    url: https://postman-echo.com/post
    method: POST
    manageCookies: true  # default is false
    onResponse: |
      console.log(response.body);
      console.log(response.headers['set-cookie']); // just to confirm
      console.log(response.cookies); 
```
