### ISSUE TITLE
need support for property on `Carousel` to disable the swipe action

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1652]
Usecase: when `Carousel` is being used while creating a onBoarding flow, developer doesn't want the use to just swipe through and pass the whole flow rather developer want to make user go through whole flow and let the Carousel swipe items by pressing buttons.

**Comment by TheNoumanDev** [comment]
ticket: https://github.com/EnsembleUI/ensemble/issues/1652

there could be four possible values for `scrollType` which is `bouncing || clamping || neverScrollable || alwaysScrollable` and default for iOS is `bouncing ` and for other is `clamping`.

Example EDL: 
```yaml
Carousel:
  id: carousel
  styles:
    height: 100
    gap: 20
    layout: auto
    borderColor: blue
    padding: 10
    currentIndex: 0
    indicatorType: rectangle
    indicatorPosition: topCenter
    enlargeCenterPage: true
    indicatorWidth: 10
    indicatorHeight: 2
    indicatorColor: green
    autoplay: true
    autoplayInterval: 3
    scrollType: neverScrollable    # it could be bouncing || clamping || neverScrollable || alwaysScrollable
```

cc: @amin-nas
