### ISSUE TITLE
Require multiple Images Upload Support in uploadFiles action

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1663]
Requirements:
- Require Multiple Upload Image Support in uploadFiles action
- Each file should have it's property name
- Upload File should support multipart/form-data 

Sample Postman Request and Response Config:
![image](https://github.com/user-attachments/assets/286ed73d-c8c7-49bd-8177-040f1060306c)

Sample API for testing:
**https://api-proloan.prospertech.io/account/document**
Request Type: **Post**

**Comment by snehmehta** [comment]
Sample EDL

```yaml
View:

  styles:
    scrollableView: true


  header:
    title: Home
  onLoad: |
    ensemble.storage.files = {};

  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:

        - Button:
            label: pick front
            onTap:
              pickFiles:
                id: filePicker
                onComplete: |-
                  ensemble.storage.files.document_front = filePicker.files[0];

        - Button:
            label: pick back
            onTap:
              pickFiles:
                id: filePickerback
                onComplete: |-
                  ensemble.storage.files.document_back = filePickerback.files[0];

        - Button:
            label: pick selfie
            onTap:
              pickFiles:
                id: filePickerselfie
                onComplete: |-
                  ensemble.storage.files.selfie = filePickerselfie.files[0];
                  
        - Button:
            label: Upload files
            onTap:
              uploadFiles:
                files: ${ensemble.storage.files}
                uploadApi: fileUploadApi


API:
  fileUploadApi:
    url: https://api-proloan.prospertech.io/account/document
    method: POST
    

```
