### ISSUE TITLE
Need support for Sign Widget

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1664]
so basically we need a sign widget, like it will be a blank screen and user can draw signature using his finger, also there should be a option to access this sign outside the sign widget, like if user draws the sign and clicks on the save button then we want to save sign in local storage and then we should be able to access it to display it on screen after closing the bottom sheet.
here is a sample of how it will look like

![image](https://github.com/user-attachments/assets/5d7fb245-b106-4395-b02d-dc6468cda7fc)
![image](https://github.com/user-attachments/assets/b3e7500e-70ca-4ead-929c-5d1f7fb8c7a8)

**Comment by kmahmood74** [comment]
1. we already have a Signature widget but it is incomplete and therefore not exposed in the schema. See EnsembleSignature.
2. We need to get the latest one in pubspec.
3. probably make the controller extend EnsembleBoxController?
4. add the ability to get the signature bytes in a way that could be used to send to the server
5. ability to clear the signature
6. styles

**Comment by TheNoumanDev** [comment]
ticket: https://github.com/EnsembleUI/ensemble/pull/1668

Example EDL of usecase defined in ticket:
```yaml
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - Signature:
            styles: 
              penColor: green
              value: ${ensemble.storage.signature}
              penStrokeWidth: 10
              disabled: true
              borderColor: red
              borderWidth: 5
        - Button:
            label: Enter sign
            onTap:
              showBottomSheet:
                body:
                  Column:
                    styles:
                      height: 500
                      padding: 20
                    children:
                      - Signature:
                          id: hello
                          styles: 
                            penColor: green
                            penStrokeWidth: 10
                            height: 300
                            disabled: false
                            strokeCap: round
                            borderColor: red
                            borderWidth: 5
                            borderRadius: 20
                      - Row:
                          styles:
                            mainAxis: spaceBetween
                            padding: 20 10
                          children:
                            - Button:
                                label: Clear
                                onTap: |
                                  hello.clear();
                            - Button:
                                label: Save
                                onTap: |
                                  ensemble.storage.signature = hello.value;
```
