### ISSUE TITLE
borderColor property is not working for TextInput

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1667]
when the input field is empty i want to show red border along with error msg, red border is working in case of focusedBorderColor only, for the normal borderColor, it is not changing the color.
sample use case:

```
- TextInput:
                        id: firstName
                        required: true
                        hintText: First Name
                        label: First Name
                        value: ${ensemble.storage.Chowmill.UserProfile.first_name}
                        textStyle:
                          fontSize: 13
                        styles:
                          expanded: true
                          fillColor: 0xfff9f9f7
                          focusedBorderColor: "${ensemble.storage.ChowmillUpdateFirstName.length == 0 ? 'red' : 0xffe3e3db}"
                          borderColor: "${ensemble.storage.ChowmillUpdateFirstName.length == 0 ? 'red' : 0xffe3e3db}"
                          borderWidth: 1
                          borderRadius: 16
                          labelStyle:
                            fontSize: 14
                        onKeyPress:
                          executeCode:
                            body: |
                              //@code
                              ensemble.storage.ChowmillUpdateFirstName = this.value;
                              ```

**Comment by TheNoumanDev** [comment]
It is already supported, you just need to play with available `borderColors`.
The `TextInput` widget applies border colors based on the state of the input field. Here's the priority order:
```dart
InputBorder? border;
if (!decoration.enabled) {
  border = _hasError ? decoration.errorBorder : decoration.disabledBorder;
} else if (isFocused) {
  border = _hasError ? decoration.focusedErrorBorder : decoration.focusedBorder;
} else {
  border = _hasError ? decoration.errorBorder : decoration.enabledBorder;
}
```
- Disabled State: If the input is disabled, it uses `disabledBorder`. If there's an error, it uses `errorBorder`.
- Focused State: If the input is focused, it uses `focusedBorder`. If there's an error, it uses `focusedErrorBorder`.
- Enabled State: If the input is enabled and not focused, it uses `enabledBorder`. If there's an error, it uses `errorBorder`.
For apply color, just put Color in front of each like for `enabledBorder`, use `enabledBorderColor`
Working solution for your usecase
```yaml
TextInput:
  id: firstName
  required: true
  hintText: First Name
  label: First Name
  value: ${ensemble.storage.Chowmill.UserProfile.first_name}
  textStyle:
    fontSize: 13
  styles:
    fillColor: 0xfff9f9f7
    focusedBorderColor: "${ensemble.storage.ChowmillUpdateFirstName.length == 0 ? 'red' : 0xffe3e3db}"
    enabledBorderColor: "${ensemble.storage.ChowmillUpdateFirstName.length == 0 ? 'red' : 0xffe3e3db}"
    borderWidth: 1
    borderRadius: 16
    labelStyle:
      fontSize: 14
  onKeyPress:
    executeCode:
      body: |
        //@code
        ensemble.storage.ChowmillUpdateFirstName = this.value;
```
