### ISSUE TITLE
Require onTap event on ChartJS widget

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1685]
Requirements:
- Need to navigate to another screen on Tapping the Chart. 
- Currently ChartJS widget doesn't have onTap event, so need onTap widget in ChartJS widget

Alternative Solution I tried which didn't work:
- I wrapped ChartJS widget with Column Widget and used onTap event on column, onTap event was working outside the area of ChartJS and the same onTap of column wasn't working in the area of ChartJS.

**Comment by kmahmood74** [comment]
@TheNoumanDev please check this out. We should provide a `onTap` for ChartJs widget as well that a user can specify any action for. `ChartJs` is a webview embedded inside a native app, so you will need to get the onclick

**Comment by TheNoumanDev** [comment]
Updated Example EDL is: 
```yaml
- ChartJs:
    onTap: 
      executeCode:
        body: | 
          console.log("hi");
    config: |
      {
        "type": "pie",
        "data": {
          "labels": ["Red", "Blue", "Yellow"],
          "datasets": [{
            "data": [300, 50, 100],
            "backgroundColor": [
                "rgb(255, 99, 132)",
                "rgb(54, 162, 235)",
                "rgb(255, 205, 86)"
            ]
          }]
        }
      }
```
Working on Web

https://github.com/user-attachments/assets/3c67e457-ea65-4b46-8f09-fec68f9d5ff8

Working on Emulator:

https://github.com/user-attachments/assets/075ab31d-71f9-45f4-bc0d-356891face05
