### ISSUE TITLE
Refactor Tooltip Implementation to Utilize Native Properties instead.

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1696]
**Current Issue:**
- **Implementation:** Tooltip is currently implemented as a separate widget.
- **Problem:** This approach contradicts Ensemble’s design philosophy, where widgets should not need to be wrapped by another widget solely to provide additional properties.

**Proposed Solution:**
- **Integration:** Introduce native Tooltip properties directly within each Ensemble widget.
- **Properties to Add:**
```
Column:
  styles:
    height: 100
    backgroundColor: red
    tooltip:
      message: "Custom styled tooltip"
      onTriggered: |-
          console.log('Tooltip was triggered');
      styles:
        backgroundColor: "#2196F3"
        triggerMode: longPress
        textStyle:
          fontSize: 16
          color: "#FFFFFF"
          fontWeight: bold
  children:
    - Text:
        text: Styled Tooltip
```
  
CC: @kmahmood74

**Comment by TheNoumanDev** [comment]
Example EDL:
```yaml
Column:
  styles:
    height: 100
    backgroundColor: red
    tooltipMessage: "Custom styled tooltip"
    tooltipStyle:
      backgroundColor: "#2196F3"
      triggerMode: tap
      onTriggered: |-
        console.log('Tooltip was triggered');
      textStyle:
        fontSize: 16
        color: "#FFFFFF"
        fontWeight: bold
  children:
    - Text:
        text: Styled Tooltip
```
