### ISSUE TITLE
require `Swipe-to-Dismiss` action on Slidable widget

### ISSUE THREAD

**Issue by TheNoumanDev** [EnsembleUI/ensemble#1705]
We need to enhance the swipe functionality to require explicit user gestures (e.g., swipe right or swipe up) for confirming actions, reducing unintentional button clicks. Currently, the Slidable widget does not support executing a function upon a complete swipe.

e.g: Robin hood swipe up tp the confirm order

**Comment by TheNoumanDev** [comment]
Example EDL: 
```yaml
View:
  header:
    title: "Slidable with Listview"
  body:
    Column:
      children:
        - ListView:
            id: listView
            styles: { expanded: true }
            item-template:
              data: ${[1,2,3,4,5,6,7,8,9]}
              name: num
              template:
                Slidable:
                  styles:
                    direction: horizontal
                    closeOnScroll: false
                    DragStartBehavior: start
                    useTextDirection: true
                  startDrawer:
                    options:
                      extentRatio: 0.001
                      openThreshold: 0.25
                      motion: behind
                      autoClose: true
                    dismissible:
                      dismissThreshold: 0.5
                      onDismissed:
                        showToast:
                          message: "Item deleted"
                  endDrawer:
                    children:
                      - icon: star
                        label: Favorite
                        backgroundColor: yellow
                        onTap:
                          showToast:
                            message: Added to favorites
                  child:
                    Text:
                      styles:
                        width: ${device.width}
                        height: 50
                      text:
                        This is widget to slide ${num}
```

Working Video
[sliadble.webm](https://github.com/user-attachments/assets/281b11af-d2c7-45ff-9ebd-37e9b31b103b)
