### ISSUE TITLE
Require additional styling properties for Slider widget

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1706]
- I want to use custom indicator, currently we only have 1 indicator style and Icon property doesn't seem to render the icon and replacing with indicator.
- Require tooltip value under the indicator
- Require tooltip min value to be displayed at top left of slider and max value should be visible at top right of the Slider
- Require tooltip styling fulfilling the following figma design:
<img src="https://github.com/user-attachments/assets/23acdf49-ee7b-4175-adbe-1277420c4cc8" alt="Image" width="300">

Suggested Styling Properties for tooltip:
- position
- shape
and maybe require some other background color and color properties as well.

**Comment by amin-nas** [comment]
@mehsaandev current slider does not show the value under it either. If you also need that, please update the requirements.

**Comment by mehsaandev** [comment]
Updated the requirements @amin-nas 
@TheNoumanDev please view the updated requirements in the first comment

**Comment by TheNoumanDev** [comment]
Below is the max level of customization can be offered right now, have created ticket for new properties (https://github.com/EnsembleUI/ensemble/issues/1724). For now, you can create a row where you can put the min/max values separately. 

Example EDL
```yaml
- Slider:
    initialValue: 24
    min: 18
    max: 30
    divisions: 24
    trackStyle:
      shape: circle   # circle/rectangular
      trackHeight: 8
      activeColor: "#F44336"
      inactiveColor: "#FFCDD2"
      secondaryActiveTrackColor: "#FFCDD2"
     disabledActiveTrackColor: "#FFCDD2"
     disabledInactiveTrackColor: "#FFCDD2"
     disabledSecondaryActiveTrackColor: "#FFCDD2"
    tickMarkStyle:
      showTicks: true
      shape:
        rectangle:  # circle/rectangle
          width: 2
          height: 8
      activeColor: black
      inactiveColor: green
      disabledInactiveColor: green
      disabledActiveColor:  green
      offset: 10
    thumbStyle:
      radius: 14
      thumbColor: "#F44336"
      disabledThumbColor: "#F44336"
      elevation: 3
      pressedElevation: 8
      borderWidth: 3
      borderColor: "#FFFFFF"
    overlayStyle:
      color: "#F44336"
      radius: 28
      opacity: 0.12
    valueIndicatorStyle:
      visibility: always # always / onlyForDiscrete / onlyForContinuous / never
      shape: paddle # drop/paddle/rectangular
      color: "#D32F2F"
      textStyle:
        fontSize: 16
        color: "#FFFFFF"
 ```

![image](https://github.com/user-attachments/assets/b8ac145f-b981-47fe-944b-d7d42b9233c5)
