### ISSUE TITLE
Scrollable TabBar: need support for the visible property

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1707]
I want to render tab items dynamically based on my API response, if there is no item for a specific tab then i don't want to render that tab, I need a visible property for it so that I could set the visibility of tab items dynamically

![image](https://github.com/user-attachments/assets/1c4058ce-6147-42ce-b9cf-37d6d78bed1d)

for example: we have the data in this format, for each item coming from the response, we are rendering it inside scrollable tab bar, now, as top picks is empty here, then we don't want to render top ticks as part of scrollable tab bar, and that's how tab bar looks

![image](https://github.com/user-attachments/assets/6db1c661-e52d-4173-857f-bcf18bd6002b)

**Comment by TheNoumanDev** [comment]
Example EDL: 
```yaml
TabBar:
  items:
    - label: Men's Clothing
      widget:
        Column:
          styles:
            gap: 8
            padding: 8 0 0 0
          item-template:
            data: ${getMensClothingProducts.body}
            name: product
            template:
              ProductCard:
                inputs:
                  title: ${product.title}
                  image: ${product.image}
                  price: ${product.price}
                  id: ${product.id}
    - label: Women's Clothing
      visible: ${ 1 != 1 }
      widget:
        Column:
          styles:
            gap: 8
            padding: 8 0 0 0
          item-template:
            data: ${getWomensClothingProducts.body}
            name: product
            template:
              ProductCard:
                inputs:
                  title: ${product.title}
                  image: ${product.image}
                  price: ${product.price}
                  id: ${product.id}
 ```
