### ISSUE TITLE
Action to select files from photo gallery

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#172]
1. User can access the device gallery via Ensemble Action (e.g. button click).
Here's a sample action (also see showDialog action for implementation reference):
```yaml
Button:
  label: Select from your Gallery
  onTap:
    action: selectFromGallery
    options:
      maxCount: 1              # see below for all options
    onComplete:
      //@code
      # access to the files here, which could be empty
```

2. When this action is taken, prompt for permission and open the Photo Gallery for selecting files.

These are all the options:
- maxCount: integer (DEFAULT 1). The max number of files allowed.

Items to think about (don't implement yet):
- file type filters
