### ISSUE TITLE
Chat widget enhancement - LLM thinking state

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1737]
I want the be able to configure a widget that is displayed when a message is sent to LLM and I am awaiting a response.

```yaml
    Chat:
      showLoading: true # default value
      loadingWidget:
        # allow me to create a custom widget here
 ```

By default, `showLoading` is true and should display a loading indicator that matches the app's primary color.

**Comment by TheNoumanDev** [comment]
Example EDL:
```yaml
Chat:
   showLoading: true # default value
   loadingWidget: # Define Any widget here to show, default is circle indicator if `showLoading` is true.
      Image:
          source: https://cdn.pixabay.com/animation/2022/07/29/03/42/03-42-11-849_512.gif
```
