### ISSUE TITLE
Need support to make a dialog non-dismissible

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1760]
I want to ensure that a specific action must be performed when a dialog appears on the screen. The dialog should not be dismissible by clicking anywhere outside of it. Currently, clicking anywhere on the screen dismisses the dialog. I want to prevent this and enforce that the dialog remains visible until the required action is completed.

**Comment by mehsaandev** [comment]
Added new `dismissible` property. If `dismissible` is false, the dialog will not dismiss even after tapping outside the dialog space.
Example usage:
```
Button:
             label: Open Dialog
             onTap:
              showDialog:
                dismissible: false
                body:
                  Text:
                    text: This is a text
```
