### ISSUE TITLE
Dropdown label issue

### ISSUE THREAD

**Issue by Mohammad-Al-Refai** [EnsembleUI/ensemble#1766]
In `Dropdown` when enable `autoComplete` and search in the input and when select the result it show the value instead the label

code example:
```yaml
View:
  body:
    Column:
      children:
        - Dropdown:
            autoComplete: true
            id: dropdown
            items:
              - label: A
                value: 1
              - label: B
                value: 2
            onChange:
              showToast:
                message: ${dropdown.value}
```

https://github.com/user-attachments/assets/340ca9dc-b1c9-43f5-b91c-b1411d1babca
