### ISSUE TITLE
require option to disable hardware back button

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1767]
I need to disable the hardware back navigation button when the API is calling, so it will require some action to disable the device back navigation button.
And by extension, it will require an action to enable the hardware back button.

Proposed solution:
- We can make a new action called `disableDeviceActions` which will take the list of device actions like back navigation, etc and the action will enable them
- and the similar action called  `enableDeviceActions` which will also take the list of device actions and enable them.

CC: @kmahmood74

**Comment by kmahmood74** [comment]
do it yourself @mehsaandev

**Comment by kmahmood74** [comment]
how is this going @mehsaandev ?

**Comment by mehsaandev** [comment]
Example Usage:

```
#  To Disable Device Back Navigation
Button:
  label: Disable Back Navigation
  onTap:
    controlDeviceBackNavigation:
        disable: true
```

```
# To Enable Device Back Navigation
Button:
  label: Disable Back Navigation
  onTap:
    controlDeviceBackNavigation:
        disable: false
```
