### ISSUE TITLE
require an action to capture image/screenshot of the Container

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1771]
This is the sample screen in which on clicking `Take Screenshot` button, it should capture a screenshot of the whole Screen Container from success to bottom:

![image](https://github.com/user-attachments/assets/c3d7adf2-d7f6-4c2b-bdea-b4fa6b5db431)

Proposed Solution:
- There could be an action to take screenshot of the Widget (including children) which will take the widgetId and will convert the whole widget to image and return the image

**Comment by mehsaandev** [comment]
Example Usage:

```
- Button:
    label: Take Screenshot
    onTap:
      takeScreenshot:
         widgetId: #write widget id
         onSuccess:
             executeCode:
                  body: |
                      console.log(event.data.imageData)
                      console.log(event.data.size)
                      console.log(event.data.dimensions)
   
```
