### ISSUE TITLE
there should be an option to toggle remove cross icon on selected date in Date widget

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1784]
Currently, If we select any date from the Date widget, it shows the cross icon to remove the date, there is no option to toggle whether we want to show this cross icon or not. 

Example Screen:

<img  width: "250" src="https://github.com/user-attachments/assets/644d0f4a-fb82-4638-9aab-2f6bdb31e369" />

Add a new property to toggle remove selected date icon

**Comment by mehsaandev** [comment]
@amin-nas 
- Date Icon will not show:
```
- Date:
      label: Example 3 - onChange
      hintText: Select a date
      showClearIcon: false
```

- Date Icon will show:
```
- Date:
      label: Example 3 - onChange
      hintText: Select a date
      showClearIcon: true
```

- Date Icon will show:
```
- Date:
      label: Example 3 - onChange
      hintText: Select a date
```
