### ISSUE TITLE
When created with utc string, Date always returning day, hour etc in utc time 

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1786]
use this as an example - 

```yaml
View:
  styles:
    useSafeArea: true
    scrollableView: true

  # Optional - set the header for the screen
  header:
    titleText: Date Object

  # Specify the body of the screen
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:

        - Text:
            text: day case
        - Text:
            text: original 2024-12-22T04:49:07.521Z
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as toLocaleString " + date.toLocaleString();
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as getDay returns: " + date.getDay() + " exp: 6"; 
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as getUTCDay returns " + date.getUTCDay() + " exp: 0";
        - Spacer:
            styles:
              size: 10
        - Divider:
        - Text:
            text: hour case
        - Text:
            text: original 2024-12-22T04:49:07.521Z
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as toLocaleString " + date.toLocaleString();
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as getHours returns: " + date.getHours() + " exp: 20"; 
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521Z');
              "as getUTCHours returns " + date.getUTCHours() + " exp: 4";
        - Spacer:
            styles:
              size: 10
        - Divider:
        - Text:
            text: by month
        - Text:
            text: original input 2025-01-01T04:49:07.521Z
        - Text:
            text: |
              //@code
              var date = new Date('2025-01-01T04:49:07.521Z'); 
              "as toLocaleString " + date.toLocaleString();
        - Text:
            text: |
              //@code
              var date = new Date('2025-01-01T04:49:07.521Z');
              "as getMonth returns: " + date.getMonth() + " exp: 11"; 
        - Text:
            text: |
              //@code
              var date = new Date('2025-01-01T04:49:07.521Z');
              "as getUTCMonth returns " + date.getUTCMonth() + " exp: 0";
        - Spacer:
            styles:
              size: 10
        - Divider:
        - Text:
            text: test to see if offset changes behavior
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521+08:00');
              "as toLocaleString " + date.toLocaleString();
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521+08:00');
              //"as getHours " + date.toLocal().getHours();
              "as getHours " + date.getHours();
        - Text:
            text: |
              //@code
              var date = new Date('2024-12-22T04:49:07.521+08:00');
              "as getUTCHours " + date.getUTCHours();

```
