### ISSUE TITLE
require a new action to save images and documents in device

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1798]
I need an action to save my image and documents in my device storage given that the blob will be provided as an input.

Requirements:
- User should be able to pass blob input and file name and it should save in the default storage of the device.
- In case of Android the Images should be in `DCIM/Pictures` and the Documents should be in `Documents` folder. 

**Proposed Action Structure:**

- In case the Blob is passed as input:
1) For Image:
   In case the type is image, it'll be saved in `DCIM/Pictures` 
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: image
       blobData:  # blob string for image
```

2) For Document:
   In case the type is document, it'll be saved in `Documents` 
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: document # pdf, docx, txt
       blobData:  # blob string for document
```

- In case the URL is passed for the media:

In case of URL, it the action will get the file from the URL and convert it to image and then save it because in many cases we have to store the URL image to our phone storage.
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: document # pdf, docx, txt
       source:  # source-url for document
```

**Comment by kmahmood74** [comment]
how is it going? @mehsaandev

**Comment by mehsaandev** [comment]
I've pushed the latest, it's pending for review @kmahmood74

**Comment by mehsaandev** [comment]
Example Usage:


In case the Blob is passed as input:
For Image:
In case the type is image, it'll be saved in DCIM/Pictures
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: image
       blobData:  # blob string for image
```
For Document:
In case the type is document, it'll be saved in Documents
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: document # pdf, docx, txt
       blobData:  # blob string for document
```
In case the URL is passed for the media:
In case of URL, it the action will get the file from the URL and convert it to image and then save it because in many cases we have to store the URL image to our phone storage.
```
Button:
  onTap:
     saveFile:
       fileName: 'Test.png'
       type: document # pdf, docx, txt
       source:  # source-url for document
     ```
