### ISSUE TITLE
Camera frames for id card scanning

### ISSUE THREAD

**Issue by MHamzaAqeel** [EnsembleUI/ensemble#1803]
We need support for id card frames on back camera. Sample is attached.
![selfie](https://github.com/user-attachments/assets/e9267071-c3d1-49d5-aa54-4a6af61bb235)

**Comment by kmahmood74** [comment]
please close the tickets if the issue has been fixed and add EDL

**Comment by snehmehta** [comment]
![image](https://github.com/user-attachments/assets/61716e26-a98e-4a64-8939-92a36fad17ae)

```yaml
Button:
  label: Open Camera
  onTap:
    openCamera: 

      options:
        preview: true
        mode: photo
      
      overlayWidget:
        Column:
          styles:
            margin: 0 32
            crossAxis: stretch
            mainAxis: center
          children:
          
            - Text:
                text: Please ensure the card is in the frame
                styles:
                  textAlign: center

            - Image:
                source: https://i.imgur.com/rEYx444.png
```
