### ISSUE TITLE
require closeApp action to close the app

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1813]

**Comment by mehsaandev** [comment]
Example Usage:

```
Button
  label: Close App
  onTap:
      closeApp:
```
