### ISSUE TITLE
When handling the date in the API response, an error occurs. also we cant overwrite API response

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#182]
//@code
      var upcomingApp = [];
      var pastApp = [];
      //txtID.text= ensemble.formatter.now().getDate();
      response.body.map(function(doc) {  
      if (doc.appointment_date.getDate() >=  ensemble.formatter.now().getDate())
      {      
        upcomingApp.push(doc);
      }
      else
      {
        pastApp.push(doc);
      }
       });

       //response.body = null;

**Comment by kmahmood74** [comment]
@vusters is this the same issue that you just fixed? Should this be closed as well?

**Comment by amin-nas** [comment]
@gaurikalp - the date comparison in your code is the part that is not working. Also note that when overwriting the API response, you have to add data to the response object:

```yaml
API:
  myAPI:
     # uri and other params
    onResponse: |
      //@code
      var myNewData = ['some','data'];
      response.body.myNewData = myNewData;
```
