### ISSUE TITLE
Need support for Tagging users and to style it inside TextInput

### ISSUE THREAD

**Issue by ridsashabbir** [EnsembleUI/ensemble#1825]
so this is something like Instagram's comment section, where you can `reply` to other users' comments on a post, but it will use a different styling for it, also you can `tag` other users in that comment section using the `@` sign and style it accordingly

![image](https://github.com/user-attachments/assets/32334e35-e35a-4f1a-a838-e7d1f1fa86b1)

![image](https://github.com/user-attachments/assets/8479385d-62a9-4ccc-b1d8-8a61d5303f8c)

**Comment by mehsaandev** [comment]
Proposed EDL for Mentionable Input:

```yaml
MentionableTextInput:
            id: inputId
            styles:
                 mentionStyle: # text Style of default mention tag starting with @ sign
                     color: red # for example if my input is "Hi, how are you @ehsaan" in this @ehsaan will be colored red 
            triggers:
              - character: '#'
                 tagStyle: 
                     color: blue # for example if my input is "This is a #beutiful place" in this @beutiful will be colored blue 
            tags:
              - id: 1
                key: ehsaan
                label: Muhammad Ehsaan
                image: # profile picture
                labelWidget: # custom widget for tags list item in case you want to add custom view for the list
              - id: 2
                key: ridsa
                label: Ridsa Shabbir
                image: # profile picture
                labelWidget: # custom widget for tags list item
              - id: 3
                key: nouman
                label: Nouman Butt
                image: # profile picture
                labelWidget: # custom widget for tags list item
```
If we don't use labelWidget and use our default tag label, it will be displayed like this:

![Image](https://github.com/user-attachments/assets/1b7634ba-9555-4d5f-98b1-df357f230ee1)

Any suggestions 
CC: @ridsashabbir @amin-nas @sharjeelyunus

**Comment by kmahmood74** [comment]
you are not mentioning, you are tagging, fix the name.

**Comment by mehsaandev** [comment]
> you are not mentioning, you are tagging, fix the name.

Updated to `TagInput`

**Comment by sharjeelyunus** [comment]
`tags` should be here, and for each item defining a custom labelWidget will make it more complex
there should be a `tagSheet` or something like that, which accepts a widget, and users can define there own sheet and use any widget to item template the users

**Comment by amin-nas** [comment]
@mehsaandev we would need to be able to style the tag selection box. I also assume existing input styling can be set on this.

```yaml
TagInput:
      styles:
           tegStyle: # text Style of default mention tag starting with @ sign
           tagSelectionStyle:
```
