### ISSUE TITLE
Specifying visibilityTransitionDuration without opacity and visible errors out the app

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#1829]
it's actually an issue due to an implicit assumption in the code. The assumption is that whenever `visibilityTransitionDuration` is specified and `visible != false`, opacity has been specified as well. 

See this code as an example - 

```yaml
SearchBarPlaceholder:
  body:
    Column:
      onTap: |
        //@code
        logo.visible = false;
        searchToggle.showSecond();
      styles:
        padding: ${device.safeAreaTop} 12 4 12
      children:
        - Stack:
            styles:
              alignChildren: centerRight
            children:
              # disabled, use for styling only
              - TextInput:
                  id: search
                  enabled: false
                  styles:
                    borderRadius: 100
                    fillColor: white
                    contentPadding: 16 120 16 16
                    elevation: 6
                    elevationBorderRadius: 100
                  icon:
                    name: search
                  hintText: Search ...
              - Image:
                  id: logo
                  source: https://firebasestorage.googleapis.com/v0/b/ensemble-web-studio.appspot.com/o/pulsepoint%2Flogo%402x.png?alt=media&token=c6e986f7-27d9-4992-829c-9b9a89886f65
                  styles:
                    visibilityTransitionDuration: 300
                    width: 120
```
using this widget anywhere on the screen will throw an error and kill the screen.
