### ISSUE TITLE
Firebase Phone Authentication

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#1830]
I think these 3 actions will do the job

`sendPhoneVerificationCode` (to send the verification code)

`verifyPhoneCode` (to verify the otp)

`resendPhoneVerificationCode` (to resend the otp)

**Suggested EDL**

```yaml
sendPhoneVerificationCode:
   phoneNumber: "+92-----------"
   onSuccess:
      // to go to the next screen for otp, it should provide the verification id and resend token
      // for next screen e.g event.data.verificationId
    onError:
      // handle error state
 ```

```yaml
verifyPhoneCode:
   code:  // otp from the `ConfirmationInput` widget
   verificationId: // verification id from  `sendPhoneVerificationCode` action
   onSuccess:
      // return the authenticated user   
   onError:
      // handle the error state
```

```yaml
resendPhoneVerificationCode:
   phoneNumber: ${phoneNumber}
   resendToken: ${resendToken}
   onSuccess:
      // return the verificationId and resendToken
  onError:
     // handle error state
```

**Comment by kmahmood74** [comment]
1. do it in a way that there is an authentication provider. Firebase is an authentication provider but we may add more later. That way, dev would configure an authentication provider and then use it this way in the code. 

2. It's not just verifying the phone right, could be email as well. It's quite common to apps to verify the email address by sending a code to it. Also nowadays there are authenticator app and much else. We don't have to support these yet as I think firebase doesn't support them natively.

**Comment by sharjeelyunus** [comment]
good idea @kmahmood74, but firebase does not supports otp via email, for email they have verification link, which is not kinda what we want here. 
I found a workaround for that i.e creating a custom otp mechanism via leveraging firestore or real-time DB: https://stackoverflow.com/a/74706965

For now I will create an action with provider for phone otp in such a way that can be extended to email, and create separate ticket for email otp, and discuss the solutions for that there

**Comment by sharjeelyunus** [comment]
@kmahmood74 here is the updated EDL

```yaml
sendVerificationCode:
   provider: firebase
   type: phone
   phoneNumber: "+92-----------" (required if type is phone)
   onSuccess:
      // to go to the next screen for otp, it should provide the verification id and resend token
      // for next screen e.g event.data.verificationId
    onError:
      // handle error state
```

```yaml
verifyCode:
   provider: firebase
   type: phone
   code:  // otp from the `ConfirmationInput` widget
   verificationId: // verification id from  `sendPhoneVerificationCode` action
   onSuccess:
      // return the authenticated user   
   onError:
      // handle the error state
```

```yaml
resendVerificationCode:
   provider: firebase
   type: phone
   phoneNumber: ${phoneNumber} (required if type is phone)
   resendToken: ${resendToken}
   onSuccess:
      // return the verificationId and resendToken
  onError:
     // handle error state
```
