### ISSUE TITLE
onChange does not work when autoComplete is enabled

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#185]
In the following EDL, onChange does not work for 2nd dropdown which has autoComplete set to true. Also, I cannot access value of dropdown using `mydropdown.value` in code if autocomplete is enabled.

```yaml
View:
  Column:
    styles: { padding: 24, gap: 24 }
    children:
      - Dropdown:
          label: onChange without autocomplete
          hintText: Select something to see onChange action
          items:
            - { "label": "Red", "value": "red" }
            - { "label": "Blue", "value": "blue" }
            - { "label": "Green", "value": "green" }
          onChange: |
            //@code
            onChangeDemo.text = 'You selected: ' +this.value;
      - Text:
          id: onChangeDemo
      - Dropdown:
          label: onChange with autocomplete
          autoComplete: true
          hintText: Select something to see onChange action
          items:
            - { "label": "Red", "value": "red" }
            - { "label": "Blue", "value": "blue" }
            - { "label": "Green", "value": "green" }
          onChange: |
            //@code
            onChangeDemoAutoComplete.text = 'You selected: ' +this.value;
      - Text:
          id: onChangeDemoAutoComplete
```
