### ISSUE TITLE
BottomNavbar is not evaluating dynamic value of `switchScreen`

### ISSUE THREAD

**Issue by mehsaandev** [EnsembleUI/ensemble#1855]
I want to dynamically assign the value of `switchScreen` using ensemble.storage value but if I assign dynamic value it doesn't work fine.

Here's my EDL:
```
BottomNavBar:
    styles:
      selectedColor: 0xff50884f
      backgroundColor: 0xffe9e2dd
    items:
      - customItem:
          widget:
            CustomNavBarItem:
              inputs:
                icon: home_4_line
                library: remix
                label: Home
          selectedWidget:
            ActiveCustomNavBarItem:
              inputs:
                icon: home_4_fill
                library: remix
                label: Home
        page: dashboard

      - customItem:
          widget:
            CustomNavBarItem:
              inputs:
                icon: star_line
                library: remix
                label: Watchlist
          selectedWidget:
            ActiveCustomNavBarItem:
              inputs:
                icon: star_fill
                library: remix
                label: Watchlist
        switchScreen: "${ensemble.storage.userMode == null false : true}"
```

In the second item I am dynamically assigning the value and expected value should be false but it behaves as if the value is true. Seems like it is not evaluating the value.

I also tried using conditional styling and it is not evaluating and styling as well.
