### ISSUE TITLE
TabBar item label is not evaluating expressions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1876]
Using an expressions in tab bar's tab labels are not evaluated.

Example
```yaml
View:
  header:
    titleText: TaBBar Test
  onLoad: |
    ensemble.storage.activeOrders = [
      1,2,3,4,5
    ];
  body:
    TabBar:
      items:
        - label: Active ${ensemble.storage.activeOrders.length}
          widget:
            Text:
              text: ${ensemble.storage.activeOrders.length}

        - label: Completed ${ 1 + 2 }
          widget:
            Text:
              text: ${ 1 + 2 }
```
