### ISSUE TITLE
useBrowserUrl no longer works

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1921]
Steps to reproduce:

1. Clone ensemble repo and point to local app
2. Set appConfig.json to this

```json
{
    "baseUrl": "https://dummyurl.com",
    "useBrowserUrl": "true",
    "envVariables": {
        "apiURL": "https://dummyjson.com"
    }
}
```

3. Set Hello Home  to use the base URL in an API call

```yaml
Import:
  - utils
  - common

View:
  styles:
    scrollableView: true

  header:
    title: r@title

  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - Button:
            label: Call API
            onTap:
              invokeAPI:
                name: mockAPI

API:
  mockAPI:
    url: ${app.baseUrl}/users/1
    method: GET
    onResponse: |-
      saveName('Michael', 'Jordan');

```

4. Now run the app and test the API call. Instead of using the browser url, the app uses baseUrl value. This causes CORS error in customer app as there are multiple browser URLs that are supported, but the backend expects API calls to be from the same URL as the browser.
