### ISSUE TITLE
Enable DELETE API calls for Finicity

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#193]
```
API:
  getToken:
    uri: 'https://studio.ensembleui.com/finicity/api/demoAuthentication'
    method: 'GET'
    authorization: none
    onResponse: |
      //@code
      ensemble.storage.token = response.body.token;

  deleteAccount:
    inputs:
      - id
    uri: 'https://studio.ensembleui.com/finicity/api/proxy'
    method: 'GET'
    authorization: none
    parameters:
      uri: '/aggregation/v1/customers/6014135335'
      method: 'delete'
      token: '${ensemble.storage.token}'
```
