### ISSUE TITLE
Entire Studio frozen when Preview is frozen

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#194]
Background:
When Preview freezes the screen (e.g. expanded problem), the entire Studio also freezes and require browser refresh. Some time even that won't work as the problem will come back, preventing you from fixing the definition issue.

Task:
Figure out how to isolate the problem to Preview only so the user can fix the definition

**Comment by kmahmood74** [comment]
put this -
View:
  title: Home
  Column:
    children:
      - Row:
          children:
            - TextInput:
                value: abc
even after that you try -
View:
  title: Home
  Form:
    children:
      - TextInput:
          value: abc
it's game over, you don't get any messages other than the stack traces

**Comment by kmahmood74** [comment]
following definition freezes the whole browser and you can kill the browser and restart - 

```
View:
  header:
    title: WebView (native) / iFrame (web)
  styles:
    scrollableView: false

  Column: 
    styles: { gap: 16, padding: 24 0, expanded: true }

    children:
      - Column:
          styles: { padding: 0 24, gap: 16 }
          children:
            - Text:
                text: WebView widget appears as WebView (embedded browser) on native apps while it appears as an iFrame on webapps.
                
            - TextInput:
                label: URI
                id: uri
                value: https://ensembleui.com/
            - Button:
                label: Update
                onTap:
                  action: executeCode
                  body: |
                    //@code
                    webview.uri = uri.value;
      - WebView:
          id: webview
          uri: https://ensembleui.com/
          # styles:
          #   height: 400
```
