### ISSUE TITLE
Ability to logEvent from code

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1943]
```yaml
              - Button:
                  label: Log event from code
                  onTap:
                    executeCode:
                      body: |
                        ensemble.logEvent({
                          "name": "event from code",
                          "provider": "firebase",
                          "parameters": {
                            "timestamp": ensemble.formatter.now().getDateTime()
                          }
                        });
```
