### ISSUE TITLE
Open device wifi settings on ios

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1976]
This action only works on Android. We need to support it on iOS as well:

```yaml
        - Button:
            label: Open Settings
            onTap:
              openAppSettings:
                target: wifi
```

Original ticket:
https://github.com/EnsembleUI/ensemble/issues/709

Package that claims to support both iOS and Android:
https://pub.dev/packages/open_settings_plus
