### ISSUE TITLE
Ability to pass inputs to custom widget programmatically

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#199]
```yaml

View:
  onLoad: |-
    //@code
    myCustomWidget.inputs.data = "my data";

  Column:
    children:
      - CustomWidget:
          id: myCustomWidget


CustomWidget:
  inputs:
    - data
  Text:
     text: ${data}
```
