### ISSUE TITLE
Ability to call a Firebase Function

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#1994]
I want to be able to call a Firebase function directly so I can leverage app check. My org does not allow public endpoint so I cannot use REST API calls in this instance.

Acceptance criteria:

1. When app check is enabled on Firebase and also on my Ensemble app, all function calls should adhere to that.
2. App should reuse the Firebase configuration format already supported under ensemble.config
3. Proper error handling for scenarios such as 
  - missing firebase config
  - app check not enabled on the app but required on Firebase

```yaml
View:
  body:
    Button:
      onTap:
        label: invoke a firebase function
        invokeAPI:
          name: myFunction
          inputs:
            foo: bar
          onResponse:
          onError:

API:
  myFunction:
    inputs:
      - foo
    type: firebaseFunction
    name: myFirebaseFunctionName
    onResponse:
    onError:
```
