### ISSUE TITLE
onTap event for custom widgets

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#201]
```yaml
View:
  Column:
    children:
      - CustomWidget:
          onTap:
            action:

CustomWidget:
  Text:
     text: I am a custom widget
```
