### ISSUE TITLE
Carousel widget next and previous methods

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#202]
As an Ensemble app developer, I want to call `next()` and `previous()` on a carousel so I can use my own custom widgets for controlling the carousel.

```yaml

View:
  Column:
    children:
      - Carousel:
          id: myCarousel

      - Button:
          onTap: |
             //@code
             myCarousel.next();
```
