### ISSUE TITLE
Carousel widget indicators customization

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#203]
As an Ensemble app developer, I want to pass my own widgets for `indicatorWidget` and `selectedIndicatorWidget` to the Carousel widget so I can customize the UI to match my designs.

```yaml
View:
  Column:
    children:
      - Carousel:
          indicatorWidget: MyIndicator
          selectedIndicatorWidget: MySelectedIndicator


MyIndicator:
  # custom widget definition

MySelectedIndicator:
  # custom widget definition
```
