### ISSUE TITLE
Event callback for custom widget

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#204]
```yaml
View:
  Column:
    children:
      - CustomWidget:
           inputs:
             label: My Special Widget
           events:
             onDateSelected: 
                 invokeAPI:
                    name: getReservations
                    inputs:
                        date: ${event.date} #this.date should work too I think


CustomWidget:
  inputs:
    - label
  events:
    - onDateSelected:
          data: {date, month, year}
  body:
    Button:
      onTap:
        dispatchEvent:
           onDateSelected:
                 data:
                   date: ${cal.getDate()}
                   month: ${cal.getMonth()}
                   year: ${cal.getYear()}


```

**Comment by kmahmood74** [comment]
assigning to myself as Vu is busy. The Yaml is not right as it confuses inputs and callbacks. Those are two different concepts. 

There are 3 concepts in Custom Widgets (or any widget for that matter) that need to be clearly defined and documented - 

1. Inputs - this is data or configuration that the widget needs to display/act correctly. Think of specific styling or the label of a field being passed as input

2. Events - these are the events that the widget dispatches. For example - onDateSelected dispatched by a Calendar widget. UI components are asynchronous and UI is an event driven system, that's why widgets dispatch events to communicate changes. They don't have outputs i.e. return values that you expect from a synchronous method call

3. Event Callbacks - these are actions that the caller can attach to events. Ensemble actions are perfect for this. 

Here's the proposed YAML. This will also work well in the schema and allow us to auto-complete event handlers
```
View:
  Column:
    children:
      - CustomWidget:
           inputs:
             label: My Special Widget
           events: #I would love to call it eventHandlers or callBacks but events works better to keep consistent with what the custom widget is calling it
             onDateSelected: 
                 invokeAPI:
                    ....


CustomWidget:
  inputs:
    - label
  events:
    - onDateSelected:
          parameters: {date, month, year}
  Button:
    onTap:
      invokeEventHandler:
          onDateSelected:
               parameters:
                   date: ${cal.getDate()}
                   month: ${cal.getMonth()}
                   year: ${cal.getYear()}

```

**Comment by kmahmood74** [comment]
@vusters @amin-nas @snehmehta @evshi please review so I may get started on implementing it. See my comment above for proposed yaml

**Comment by evshi** [comment]
User is essentially defining custom events, but EDL has replaced `event` nomenclature with `actions`. For consistency and better developer experience, I would suggest renaming some keys: `eventHandlers` -> `actions`, `dispatchEvent` -> `dispatchAction`, `parameters` -> `inputs` and make it a list of strings.

**Comment by kmahmood74** [comment]
good suggestion, thanks @evshi will make the change

**Comment by kmahmood74** [comment]
@vusters what do you think?

**Comment by amin-nas** [comment]
The proposed yaml is confusing to me. I expect to pass in an action to a widget, and decide when to fire it inside the widget.

```yaml
View:
  Column:
    children:
      - CustomWidget:
           inputs:
             label: My Special Widget
             myAction: 
                 invokeAPI:
                    name: getReservations
                    inputs:
                        date: ${event.date}


CustomWidget:
  inputs:
    - label
    - myAction
  Button:
    onTap:
        myAction:
             inputs:
                 date: ${cal.getDate()}
```

I can also see an alternative where you define event handlers when instantiating the widget, and dispatch those events inside the widget definition:

```yaml
View:
  Column:
    children:
      - CustomWidget:
           inputs:
             label: My Special Widget
           events:
             onDateSelected: 
                 invokeAPI:
                    name: getReservations
                    inputs:
                        date: ${event.date}


CustomWidget:
  inputs:
    - label
  events:
    - onDateSelected
  Button:
    onTap:
        dispatchEvent:
             name: onDateSelected
             inputs:
                 date: ${cal.getDate()}
```

**Comment by vusters** [comment]
How about this?
```
View:
  body:
    MyWidget:
      inputs:
        name: Peter Parker
      eventHandlers:
        onMyTap:
          log (event.data.occupation);

MyWidget:
  inputs: [name]
  eventHandlers: [onMyTap]  # encourage prefix on* for consistency
  body:
    Button:
      onTap:
        dispatchEvent:
          handler: onMyTap    # 'name' is OK too for similar convention with others
          data:
            occupation: superhero
```

**Comment by vusters** [comment]
Alternatively to be more consistent:
```
View:
  body:
    MyWidget:
      inputs:
        name: Peter Parker
      actionHandlers:
        onMyTap:
          log (event.data.occupation);  

MyWidget:
  inputs: [name]
  actionHandlers: [onMyTap]  # encourage prefix on* for consistency
  body:
    Button:
      onTap:
        callActionHandler:
          handler: onMyTap    # 'name' is OK too for similar convention with others
          data:
            occupation: superhero
```
