### ISSUE TITLE
navigateBack action

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#207]
As an Ensemble app developer, I want to be able to navigate to previous screen using an action so I can navigate using any widget, not just the header's back button.

```yaml
  - Button:
      onTap:
        action: navigateBack
```
