### ISSUE TITLE
Toggle Buttons

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#209]
The button whose state can be controlled, like if the button is selected or not.

Reference: https://api.flutter.dev/flutter/material/ToggleButtons-class.html

At this moment I'm showing buttons like this:
![Screenshot (340)](https://user-images.githubusercontent.com/61178058/218117374-3ea76367-f6e8-4cfb-88e4-8bf1a6042d7e.jpg)

This is visually ok, but it would require a lot of code to make it functional, so we should have a toggle button

**Comment by kmahmood74** [comment]
good one, thanks @sharjeelyunus

**Comment by amin-nas** [comment]
Start by suggesting the YAML for this widget.

**Comment by kmahmood74** [comment]
@hamxa152 as Amin noted above, as the first step, please suggest the YAML for the widget and tag me in the comment. Once we approve the YAML, you can start implementing. When you are working on something, please put that in progress.

**Comment by vinothvino42** [comment]
@kmahmood74 

Can you check this YAML for ToggleButtons?

YAML:

```
View:
  styles:
    useSafeArea: true
  body:
    ToggleButtons:
      styles: { gap: 8, backgroundColor: yellow }
      direction: vertical
      selectedColor: orange
      selectedBorderColor: red
      onTap: 
        updateToggleButtons
      children:
        - Text:
            text: Apple
        - Text:
            text: Orange
        - Text:
            text: Banana
```
