### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#213]
As an Ensemble app developer, I want an action for copying a value to clipboard:

```yaml
Button:
  onTap:
    action: copyToClipboard
    value: copy this value

# also available as a JS function
Button:
  onTap:
    action: executeCode
    body: |
      //@code
      ensemble.copyToClipboard('copy this value');
```

**Comment by amin-nas** [comment]
@hamxa152 - please also provide an option for a user to include an action once the copy process is done

```yaml
Button:
  onTap:
    action: copyToClipboard
    value: copy this value
    onComplete:
       action: # any action could go here, like showToast
```
