### ISSUE TITLE
Cannot pass variable to charts data

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#217]
When using `addData` to add data points to ChartJS, I get an error when using a variable. 

Error:
```
Error :  Code Error: Exception: Error: Converting object to an encodable object failed: Instance of 'minified:kH' while executing var d1 = 50;
myChart.addLabels(['x']);
myChart.addData(0,[d1]);
myChart.update();
```

Sample screen
```yaml
View:
  styles:
    backgroundColor: black
  Column:
    children:
      - CustomChart


CustomChart:
  onLoad:
    action: startTimer
    options:
      repeat: true
      maxNumberOfTimes: 30
      repeatInterval: 3
      startAfter: 3
    onTimer:
      action: executeCode
      body: |
        //@code
        var d1 = 50;
        myChart.addLabels(['x']);
        myChart.addData(0,[d1]);
        myChart.update();
  Column:
    children:
      - ChartJs:
          id: myChart
          styles: 
            width: ${device.width}
            height: 200
          type: 'line'
          config: |
            {
              type: 'line',
              data: {
                labels: ['1','2','3','4','5','6','7','8','9','1','2','3','4','5','6','7','8','9','1','2','3','4','5','6','7','8','9'],
                datasets: [
                  {
                    backgroundColor: 'rgba(238, 166, 50, 0.3)',
                    borderColor: 'rgba(238, 166, 50, 1)',
                    borderWidth: 2,
                    data: [31, 33, 34, 35, 32, 34, 33, 32, 35, 33, 31, 35, 32, 34, 33, 35, 31, 33, 34, 32, 35, 31, 34, 33, 35, 32, 31],
                    fill: 'start'
                  }
                ]
              },
              options: {
                scales: {
                  x: { display: false},
                  y: { display: false, min: 20, max: 175},
                },
                elements: {
                  point: { radius: 0 }
                },
                plugins: {
                  "legend": {
                    "display": false
                  },
                  filler: {
                    propagate: false,
                  }
                },
                interaction: {
                  intersect: false,
                },
                tension: 0.4
              }
            }
```
