### ISSUE TITLE
TextArea widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#219]
Extend the current TextInput widget to allow multi-line

```yaml
TextInput:
  multiline: true | false //default is false. When true, this textinput allows user to type in multiple lines
  maxLines: null //its a number, default is null which means that user can keep typing and the textinput grows and wraps text
  minLines: 1 //default is 1. 
```
