### ISSUE TITLE
empty onresponse on API throws an error (ignorable error but still an error)

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#249]
example - 

```
API:
  getNames:
    uri: https://myuri.com
    method: 'POST'
    headers:      
      "Authorization": "Bearer ${token}"
    onResponse: |
```
parser should not be called on empty code blocks.
