### ISSUE TITLE
Inform user when triggering an API call in code to an API that is not defined

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#259]
When calling an API in code, if the API does not exist, the error message should tell me that the API does not exist.

```yaml
View:
  Column:
    children:
      - Button:
          label: test API
          onTap:
            action: executeCode
            body: |
              //@code
              ensemble.invokeAPI('wrongApiName');
```

Current error message:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/491202/220156705-f2330b25-4525-4d15-8cef-d97aa779fde9.png">
