### ISSUE TITLE
Markdown links color to match primary color

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#262]
Currently links in a markdown widget are blue. They should match the theme's primary color.

```yaml
View:
  Column:
    children:
      - Markdown:
          text: Here is an [inline links](https://ensembleui.com)
```
