### ISSUE TITLE
Visibility seems to break children's bindings

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#278]
When a container's visibility is bound and changes, there seems to be a race condition where children's bindable may not be bound correctly.
```
Column:
  visible: ${someBindable}
  children:
     Text:
        text: ${someBindable}
```
