### ISSUE TITLE
console.log(response.body) throws error

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#304]
Try the following:

```yaml
View:
  onLoad:
    action: invokeAPI
    name: getPeople
    onResponse: |
      //@code
      console.log(response.body);
  Column: 
    children:       
      - Text:
          text: ${getPeople.body.results.length}
API:
  getPeople:
    uri: https://randomuser.me/api/?results=6
    method: GET
```

Currently throws an error:
![image](https://user-images.githubusercontent.com/491202/222186411-ddcbf0c0-a3fe-4cc8-a312-6fc532e88afc.png)
