### ISSUE TITLE
Passing colors as inputs break API binding

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#305]
When I pass colors to a custom widget that also has API binding, the binding results in null.

![image](https://user-images.githubusercontent.com/491202/222196236-b90b97de-7d2c-491c-b18f-88ce4a98c39f.png)

```yaml
View:
  onLoad:
    action: invokeAPI
    name: getPeople

  Column: 
    children:
      - Text:
          text: Images ${getPeople.body.results.length}
      - CustomWidget:
          inputs: 
            txt: Images ${getPeople.body.results.length}
            bgColor: 0xFFDCE8E1
            borderColor: 0xFF141414


CustomWidget:
  inputs:
    - txt
    - bgColor
    - borderColor
  Column:
    styles:
      backgroundColor: ${bgColor}
      borderColor: ${borderColor}
    children:
      - Text:
          text: ${txt}

API:
  getPeople:
    uri: https://randomuser.me/api/?results=6
    method: GET
```
