### ISSUE TITLE
Large images causes app crash

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#314]
Sample yaml

```yaml
View:
  onLoad:
    action: invokeAPI
    name: getPhotos

  header:
    title: I NYC
    styles:
      backgroundColor: black
      shadowColor: 0x22000000
      elevation: 4
      color: white
  Column:
    styles: { mainAxis: center, padding: 24 0 }
    children:

      - GridView:
          styles:
            padding: 8
            separatorColor: white
            expanded: true
          item-template:
            data: ${getPhotos.body}
            name: p
            template:
              ImageCard:
                inputs:
                  p: ${p}

ImageCard:
  inputs:
    - p
  Column:
    children:
      - Row:
          styles:
            crossAxis: center
            padding: 8 16
          children:
            - Image:
                source: ${p.user.profile_image.large}
                styles:
                  width: 32
                  height: 32
                  borderRadius: 32
                  margin: 0 8 0 0
            - Text:
                text: ${p.user.name}
                styles:
                  fontSize: 15

            - Spacer
            - Text:
                text: ${p.likes}
            
            - Icon:
                icon: heart
                library: fontAwesome
                styles:
                  color: red
                  size: 18
                  margin: 0 0 0 8

      - Image:
          source: ${p.links.download}
          styles:
            fit: cover
            expanded: true



API:
  getPhotos:
    uri: https://api.unsplash.com/collections/349236/photos?client_id=lX_Rc6VKjjA-O7U9elOpsWHwXzDRWKZDOkenYrjLFig&orientation=landscape&per_page=50
    method: GET
```
