### ISSUE TITLE
Cannot access the value of a TextInput that is inside a custom widget

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#316]
When I place a TextInput inside a custom widget, I cannot access it's value from the parent View.

```yaml
View:
  Column: 
    styles: { gap: 16, padding: 24 }
    children:       
      - CustomForm
      - Button:
          label: Submit
          onTap: |
            //@code
            valueText.text = todoItem.value;
      - Text:
          id: valueText

CustomForm:
  Form:
    children:
      - TextInput:
          id: todoItem
          label: ToDo item

```
