### ISSUE TITLE
Passing background image as an input to a custom widget does not work

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#318]
```yaml
View:
  Column: 
    styles: { gap: 16, padding: 24 }  
    children:
      - BoldTag:
          inputs:
            label: Travel
            background: https://firebasestorage.googleapis.com/v0/b/ensemble-web-studio.appspot.com/o/demo_apps%2Fkitchen-sink%2Fflow_travel.png?alt=media&token=0f63b0d1-7353-4623-b1d5-1a2e73a95fb9

BoldTag:
  inputs:
    - label
    - background
  Column:
    styles:
      padding: 16
      height: 60
      backgroundImage:
        source: ${background}
    children:
      - Text:
          text: ${label}
          styles:
            color: white
            fontWeight: bold
```
