### ISSUE TITLE
Conditional UI

### ISSUE THREAD

**Issue by snehmehta** [EnsembleUI/ensemble#330]
Ability to render widget based on condition.

Sample EDL for conditional UI. 
```yaml
if: 
  condition: ${a == b} # hypothetical condition that returns bool 
  body: 
    Text:
      text: I'll render based on `condition`
```
_Side note : Syntax might change. Open for suggestions._

**Comment by kmahmood74** [comment]
how about - 

```
Conditional:
  - condition:
     if: ${isImage == true}
     then:
       Image:
         src: ${filePath}
  - condition:
     if: ${isVideo == true}
     then:
       Video:
        src: ....
  - default:
      Text:
        text: no match
```

**Comment by vusters** [comment]
latest:
```
Conditional:
  - if: ${isImage == true}
     then:
       Image:
         src: ${filePath}
  - if: ${isVideo == true}
     then:
       Video:
        src: ....
  - default:
      Text:
        text: no match
```
