### ISSUE TITLE
Page inputs need to be explicit

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#356]

**Comment by kmahmood74** [comment]
as long as we allow the inputs to be optional, it's all good.

**Comment by hemish11** [comment]
Didn't got on what exactly to do

**Comment by amin-nas** [comment]
> Didn't got on what exactly to do

@hemish11 In Ensemble, app builder can pass inputs to screens, widgets, and APIs. For Widgets and APIs, app builder explicitly declares the inputs. For Views, it is implicit. We need to make screen inputs also explicit, but for backward compatibility, it should be optional.

first view, linking to another one and passing inputs
```yaml
View:
  body:
    Button:
       onTap:
         navigateScreen:
           name: AnotherView
           inputs:
             foo: bar
```

second view, receiving inputs
```yaml
View:
  inputs:
    - foo
```

**Comment by kmahmood74** [comment]
lots of discussion and final YAML in the associated PR - https://github.com/EnsembleUI/ensemble/pull/965

```
View:
  inputs:
     # short-hand for just name only. This is how it works today
     - occupation
     
     # more details
     - name: age
       type: number
       required: true
       default: 20
```
