### ISSUE TITLE
Input widgets with side-by-side labels inside Form do not lay out properly

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#375]
Form container can display its widgets' labels on top or to the left. When displaying labels to the left, the input widgets no longer show up properly because of the recent change (wrapping them inside a LayoutBuilder).
Here's the YAML that used to work but no longer work
```
View:
  title: Home
  Column:
    children:
      - Form:
          styles:
            labelPosition: start
          children:
            - TextInput:
               
            - TextInput:
                label: short label

            - TextInput:
                label: This is a longer label but not too long
```
The real problem is because we use a 3rd party grid that tries to auto-size each widget's height, but we didn't need to. We can simply have each form widget wraps in a Row like this (ignore the syntax correctness - just a demonstration):
```
Row(
  Expanded(flex: 1, child: Text("my label")),
  Expanded(flex: 3, child: TextInput())),
```
This will give the label 1/3 the space and the input widget 2/3 of the space, such that each row will be aligned properly. To prevent the label from being too wide on the big screen, also add a `labelMaxWidth` setter.
