### ISSUE TITLE
setting dropdown's value to an invalid value does not clear the selected value

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#408]
this was reported by @gaurikalp 

Setting a dropdown's value to an invalid value (e.g. setting it to null or empty string) should clear out the selected value but that doesn't work when done in code. 

This is because the maybeValue is not a setter and is being directly set. As a result, there is no setState() being called. 

Inside dropdown.dart - 
```
class SelectOneController extends FormFieldController {
  List<SelectOneItem>? items;

  // this is our value but it can be in an invalid state.
  // Since user can set items/value in any order and at anytime, the value may
  // not be one of the items, hence it could be in an incorrect state
  dynamic maybeValue;
  int gap = 0;
  bool autoComplete = false;

  framework.EnsembleAction? onChange;
}
```
and it's set directly in the setters - 
```
  @override
  Map<String, Function> setters() {
    return {
      'value': (value) => _controller.maybeValue = value,
      'items': (values) => updateItems(values),
      'onChange': (definition) => _controller.onChange =
          framework.EnsembleAction.fromYaml(definition, initiator: this),
      'itemsFromString': (dynamic strValues) => setItemsFromString(strValues),
      'itemsFromArray': (dynamic arrValues) => setItemsFromArray(arrValues),
      'autoComplete': (value) =>
          _controller.autoComplete = Utils.getBool(value, fallback: false),
    };
  }
```
so there is no setState being called after it is set and thus no update

**Comment by vinothvino42** [comment]
@gaurikalp @kmahmood74 
Add an id to the Dropdown widget and change it from any widget by calling `dropdownId.value = '`' value to reset the dropdown value and the hint text will be shown.


https://user-images.githubusercontent.com/12869588/230012667-2069ce41-9bec-4591-9bbc-6281f7ed60b3.mp4

<details>
  <summary>YAML Code</summary>

  ### YAML Code
  ```yaml
View:
  header:
    title: Reset Dropdown
  Column:
    styles:
      gap: 24
      padding: 24

    children:
      - Markdown:
          text: |
            ## Reset Dropdown value example

      - Dropdown:
          id: dropDown
          label: 1 - array of strings
          hintText: Select something
          items:
            - Red
            - Blue
            - Green
          onChange: |
            //@code
            onChangeDemo.text = 'You selected: ' +this.value;

      - Text:
          id: onChangeDemo

      - Button:
          label: Reset
          onTap: |
            //@code
            dropDown.value = '';
            onChangeDemo.text = '';


  ```
</details>
