### ISSUE TITLE
Invoking an API after receiving location does not work

### ISSUE THREAD

**Issue by gaurikalp** [EnsembleUI/ensemble#410]
Is there a way to obtain a device's latitude and longitude without using a map widget or event?
As we only need to call once when the page loads and store those coordinates for subsequent use.

Also attempted to use the "nearby" button's onTap action to call getLocation as shown in the kitchen sink example. However, it takes time, sometimes an event does not get fired.

**Comment by amin-nas** [comment]
@gaurikalp - Try the following. It works as expected:
```yaml
View:
  onLoad:
    getLocation:
      options:
        recurring: false     
      onLocationReceived: |-
        //@code
        status.text = 'Lat: ' + latitude + ', Lng: ' + longitude;
                
  body:
    Column:
      styles: { margin: 12,padding: 12 ,gap: 12}
      children:
        - Text:
            id: status
```

If you're performing another action, e.g. executing code or firing an API that require the location details, you need to do so using `onLocationReceived`. This will ensure you have the location data.

**Comment by amin-nas** [comment]
Reopening this issue with updated title. Here's a yaml to test. The  invokeAPI in code does not trigger as expected:

```yaml
View:
  onLoad:
    getLocation:
      options:
        recurring: false     
      onLocationReceived: |-
        //@code
        status.text = 'Lat: ' + latitude + ', Lng: ' + longitude;      
        ensemble.storage.set('latitude', latitude);
        ensemble.storage.set('longitude', longitude);
        ensemble.invokeAPI("getToDos");
                
  body:
    Column:
      styles: { margin: 12,padding: 12 ,gap: 12}
      children:
        - Text:
            id: status

API:
  getToDos:
    uri: 'https://api.airtable.com/v0/appDbkGS4VOiPVQR5/ToDo?api_key=keyyWz426zsnMKavb'
    method: 'GET'
```
