### ISSUE TITLE
View:header:title has to be hardcoded as it doesn't evaluate expressions

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#414]
see the following yaml. The 'data' object is passed as input to this screen. It works everywhere else but not in View:header:title. 

```
View:
  header:
    title: ${(data.label != null)?data.label:Restaurant}
  body:
    FittedColumn:
      children:
        - RestaurantWidget:
            inputs:
              id: ${data.id}
              name: ${data.name}
              address: ${data.address}
              location: ${data.location}
              phone: ${data.phone}
              email: ${data.email}
              website: ${data.website}
              rating: ${data.rating}
              cuisines: ${data.cuisines}
              reviews: ${data.reviews}
              images: ${data.images}
              label: ${data.label}
RestaurantWidget:
  inputs:
    - id
    - name
    - address
    - location
    - phone
    - email
    - website
    - rating
    - cuisines
    - reviews
    - images
    - label
  body:
    Row:
      styles:
        gap: 12
        crossAxis: center
        padding: 8,0
      children:
        - Image:
            styles:
              width: 50
              height: 50
              borderRadius: 50
            source: ${images.length>0?images[0]:'https://source.unsplash.com/random/'}
        - Column:
            styles:
              gap: 2
            children:
              - Text:
                  styles:
                    fontWeight: bold
                  text: ${label}
              - Text:
                  text: ${rating}
        - Spacer
        - Icon:
            icon: chevron_right
            styles:
              size: 20
              color: black
```
