### ISSUE TITLE
Passing widgets as input

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#420]
I want to be able to pass widgets to a custom widget that would render the inputs as children.

Example:
```yaml

View:
  body:
    Column:
      children:
        - MyWrapperWidget:
            inputs:
              title: Some title
              footer:
                Button:
                  label: More details

MyWrapperWidget:
  inputs:
    - title
    - footer
  body:
    Column:
      children:
        - Text:
            text: ${title}
        - ${footer}
```
