### ISSUE TITLE
item-templates don't work when data is an array of primitives

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#422]
try this and nothing shows up and there is no error on console as well

```
View:
  onLoad:
    invokeAPI:
      name: dummy
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - ListView:
            item-template:
              data: ${dummy.body.data}
              name: myText
              template:
                MyText:
                  inputs:
                    text: ${myText}

MyText:
  inputs:
    - text
  body:
    Text:
      text: ${text}

API:
  dummy:
    uri: https://dummyjson.com/users/1
    method: GET
    onResponse:
      executeCode:
        body: |
          //@code
          response.body.data = ['abc','def']
      
  ```

**Comment by vinothvino42** [comment]
You're trying to add a list view inside the column widget without proper constraint (it's an unbounded height). So you've to add `expanded: true` in the styles of the ListView widget, this will take all the available height of the Column's widget.

```
ListView:
  styles:
    expanded: true
  item-template:
    data: ${dummy.body.data}
    name: myText
    template:
      MyText:
        inputs:
          text: ${myText}
```
