### ISSUE TITLE
Need a onItemTap for all itemTemplate widgets

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#423]
```
        - Column:
            item-template:
              data: ${getMockHomepage.body.data.homepage.mainImages}
              name: mainImages
              template:
                ImageWidget:
                  inputs:
                    source: ${mainImages}
            onItemTap:
              navigateScreen:
                name: Image
                inputs:
                  data: >-
                    ${getMockHomepage.body.data.homepage.mainImages[this.selectedItemIndex]}
```
doesn't work
