### ISSUE TITLE
ListView/expanded:true crashes the browser

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#428]
try this code, it will crash your browser tab. App must never crash no matter how wrong the yaml is. Please add a proper check and show the user a proper error to fix the yaml. 

```
View:
  onLoad:
    invokeAPI:
      name: dummy
  body:
    ListView:
      styles: 
        expanded: true
      item-template:
        data: ${dummy.body.data}
        name: myText
        template:
          MyText:
            inputs:
              text: ${myText}

MyText:
  inputs:
    - text
  body:
    Text:
      text: ${text}

API:
  dummy:
    uri: https://dummyjson.com/users/1
    method: GET
    onResponse:
      executeCode:
        body: |
          //@code
          response.body.data = ['abc','def']
```
