### ISSUE TITLE
Named styles

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#432]
I want to be able to define a group of styling, globally across the app, and apply them to widgets in my screens.

```yaml

# in theme
Colors: 
  ...
Widgets: 
  ...
Styles:
  myPersonCard:
    shadowColor: 0xFFCECECE
    shadowOffset: [ 0, 0 ]
    shadowRadius: 2
    backgroundColor: white
    borderRadius: 12


# in screen
View:
  body:
    Column:
      styleName: myPersonCard
      styles:
         # styles here will take precedent
```

**Comment by vinothvino42** [comment]
@amin-nas @vusters Is the theme needs to be in a separate file? or can it be placed in any files? It's supposed to be a single global theme right? All other widgets can use it. So how we're going to do this in the ensemble studio?

**Comment by amin-nas** [comment]
> @amin-nas @vusters Is the theme needs to be in a separate file? or can it be placed in any files? It's supposed to be a single global theme right? All other widgets can use it. So how we're going to do this in the ensemble studio?

In Studio, there's a theme section for each app. Styles defined in the theme would be available globally.
Styles defined as part of a screen would be available inside that screen only. If a style is defined in both the theme and the screen, the screen style would apply.

**Comment by vinothvino42** [comment]
```
# define your app theme here
Colors:
  primary: 0xFFF19D39
  
Widgets:
  Button:
    borderRadius: 100
    color: black
    padding: 20 24
    backgroundColor: 0xFFF1D05C
  Input:
    borderColor: 0xFFEDEDF0
  
Styles:
  myButtonTheme:
    type: Button
    color: white
    backgroundColor: green
    borderRadius: 12
```

@amin-nas Here, In this case which one will take precedent? Styles or Widgets?
