### ISSUE TITLE
Cannot changer value of global variable

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#447]
I want to have a global var, like a counter, that I can increment and reuse across my screen.

In this example, the value of `i` remains 0 even though I am incrementing it every 5 seconds.

```yaml
View:
  onLoad:
    startTimer:
      options:
        repeat: true
        repeatInterval: 5
        startAfter: 0
      onTimer:
        executeCode:
          body: |-
            //@code
            console.log("i = " + i);
            t.text = "i value is " + i;
            i = i + 1;
  body:
    Column:
      children:
        - Text:
            id: t

        
Global: |-
  //@code
  var i = 0;
```
