### ISSUE TITLE
Mock data framework

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#451]
This is need for app generation and also for users to easily test their apps.

Suggest the following - 

1. Users should have the ability to define one or more named datasets such as - 

authData = {.....}
sampleCustomerDataForConfDemo = {....}
sampleCustomerDataForConf2Demo = {....}

2. Editor should display a Data tab where people can see all their mockdata
3. APIs have a field named - mockData. It references one of the named mockdata defined for the app
```
API:
   getUsers:
      mockData: userMock
      uri: ...
```

5. An app has the mock mode either turned on or off. When on, mock data is used for all APIs that have mockData defined. The ones that don't just make regular calls.

**Comment by kmahmood74** [comment]
please discuss and re-assign

**Comment by kmahmood74** [comment]
an API without mockResponse should continue as-is and be treated like any other API. this will allow devs to progressively connect with the backend and is a really useful feature.

**Comment by kmahmood74** [comment]
Setting/unsetting `useMockResponse`
```javascript
app.useMockResponse = true
```

API Yaml variations - 

```yaml
  slowAPI:
    inputs:
      - uniqueId    
    mockResponse:
      #inline mock response
      body: 
        title: I am mock data
        list:
          - name: mock first
          - name: mock second
          - name: mock third
          - name: ${uniqueId}
      #can set response headers as well
      headers:
        - authToken: absbsbxssjjs
    url: https://openlibrary.org/search.json?q=the+lord+of+the+rings
    onResponse: |-
      console.log('slowAPI='+uniqueId);
      response.body.list.push({name: 'adding in onResponse - '+uniqueId});
```

Return mock data from a function
```yaml
  mockDataFromFunction:
    inputs:
      - uniqueId    
    mockResponse: ${getMockResponse()}
    url: https://openlibrary.org/search.json?q=the+lord+of+the+rings
    onResponse: |-
      console.log('mockDataFromFunction='+uniqueId);
      response.body.list.push({name: 'mockDataFromFunction adding in onResponse - '+uniqueId});
```

Mocking an error response, simply set `statusCode` to an error statusCode
```yaml
  mockError:
    inputs:
      - uniqueId    
    mockResponse:
      body:
      statusCode: 500
      reasonPhrase: mock bad request

    url: https://openlibrary.org/search.json?q=the+lord+of+the+rings
    onResponse: |-
      console.log('mockDataFromFunction='+uniqueId);
      response.body.list.push({name: 'mockDataFromFunction adding in onResponse - '+uniqueId});
    onError:
      showToast:
        message: error occurred ${response.statusCode} ${response.reasonPhrase}
        options:
          duration: 5
```
