### ISSUE TITLE
custom widgets inputs as values to backgroundGradient are not working as expected 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#456]
### What i am want to acheive

I am trying to build a card component so that each component can have its own backgroundGradient or backgroundImage

### What i have tried so far

Although it works well if a explicitly write colors hex values in the colors array

But not otherwise 
1. Have tried to pass colors array as inputs to custom widgets and use as value to colors prop in backgroundGradient but its not working, showing following error

2.  Also passed individual color  values as well but still not working 
```
        - CreditCard:
            body : 
              styles: 
                backgroundGradient: 
                  colors : [0xFF621464, 0xFFF583FF]
            inputs:
              bank: Wallet
              number: "**** **** **** 8869"
              cardHolderName: Card Holder Name
              name: Helena Smith
              expiryDate: Expiry Date
              date: 05/40
              colors : [0xFF621464, 0xFFF583FF]
              colorA : 0xFF621464
              colorB : 0xFFF583FF
              image : https://firebasestorage.googleapis.com/v0/b/imagesupload-987d3.appspot.com/o/profile_pictures%2FVisa_logo_blue.png?alt=media&token=5ce016fb-1a13-49b7-a2d6-311ecdb71919
              width: 40
              height : 50
              backgroundImg: https://firebasestorage.googleapis.com/v0/b/imagesupload-987d3.appspot.com/o/profile_pictures%2FGroup.png?alt=media&token=65cff6e1-9b20-41d1-90ba-c68504878582



CreditCard:
  inputs:
    - bank
    - number
    - cardHolderName
    - name
    - expiryDate
    - date
    - cardType
    - image
    - width
    - height
    - colorA
    - colorB
    - backgroundImg
  body:
    Column:
      styles:
        padding: 24
        borderRadius: 10
        height: 200
        crossAxis: stretch
        mainAxis: spaceAround
        backgroundGradient:
          colors : 
            - ${colorA}
            - ${colorB}
```
console log error
![image](https://user-images.githubusercontent.com/62849614/234648502-c097e52a-de95-4efd-9061-3aa99c335a83.png)

Any possible way around or fix would be helpful.

**Comment by kmahmood74** [comment]
@vusters this seems like yet another issue with the nested bindings not working. Is that a correct understanding? we need to fix that as I have come across 3+ bugs related to this and there are probably many more

**Comment by amin-nas** [comment]
Fixed. Here's an example:

```yaml
View:
  body:
    Column:
      children:
        - Test:
            inputs:
              colors: [ 0xFFFF0000, 0xFFFF00FF ]
Test:
  inputs:
    - colors
  body:
    Row:
      styles:
        backgroundGradient:
          colors: ${colors}
      children:
        - Spacer:
            styles:
              size: 100
```
