### ISSUE TITLE
Remove margin in Carousel

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#465]
There is an automatic margin on images on in Carousel

```
Carousel:
            styles: 
              height: 220
              layout: auto
              indicatorType: circle
              indicatorPosition: bottom
              indicatorWidth: 6
              indicatorHeight: 6
              singleItemWidthRatio: 1
            item-template:
              data: ${record.fields.photo}
              name: image
              template:
                Image:
                  source: ${image.url}
```

![Image](https://user-images.githubusercontent.com/61178058/235729592-a971793f-16ab-4d08-83b9-82883221250e.png)
