### ISSUE TITLE
onLoad does not execute when rendeing a widget as dialog

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#467]
In this example, the API is not called and the response is not available inside the dialog

```yaml
View:
  body:
    Column: 
      children:
        -  Button:
            label: Show Dialog
            onTap: 
              showDialog:
                widget: MyCustomView

MyCustomView:
  onLoad:
    invokeAPI:
      name: getPeople
  body:
    Column:
      children:
        - Text:
            text: ${getPeople.body.results.length} records were retrieved from API

API:
  getPeople:
    uri: https://randomuser.me/api/?results=6
    method: GET
```
