### ISSUE TITLE
Theming bugs

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#469]
1. Disabled input text is too light. Set default  to #878199

![image](https://user-images.githubusercontent.com/491202/235993838-f8376e69-4de7-4e7a-8f9f-2c69956a184f.png)

2. Divider's in DataGrid are too dark. Set default to #DAD7E0

3. Button labels are too small. Set default to 16 medium.

4. Setting button border color, fontSize, and fontWeight from Theme does not work.
```yaml
Widgets:
  Button:
    borderColor: 0xFF0077CC
    fontSize: 18
    fontWeight: bold
```
