### ISSUE TITLE
App only working in studio's preview, and not on iOS/Android/Web

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#471]
The following screen only works in Studio, but when run in preview app (any platform), it does not work. Perhaps an issue with  this flag:  instantPreview
```
https://studio.ensembleui.com/preview/index.html?appId=bMNDkXNXY4AaOFa3e4aG&screenId=awpeiQSHDXO6hzBLWdx1&showAction=false&devicePreview=true&instantPreview=false
```

```yaml
View:
  onLoad:
    executeCode:
      body: |
        //@code
        initializeGame();
  
  header:
    title: Tic-Tac-Toe
  body:
    Column:
      styles:
        padding: 24
        gap: 24
        crossAxis: center
      children:
        - Text:
            text: Current turn is ${ensemble.storage.currentTurn}

        - Column:
            children:
              - FittedRow:
                  children:
                    - Tile:
                        inputs:
                          position: 0
                    - Tile:
                        inputs:
                          position: 1
                    - Tile:
                        inputs:
                          position: 2
              - FittedRow:
                  children:
                    - Tile:
                        inputs:
                          position: 3
                    - Tile:
                        inputs:
                          position: 4
                    - Tile:
                        inputs:
                          position: 5
              - FittedRow:
                  children:
                    - Tile:
                        inputs:
                          position: 6
                    - Tile:
                        inputs:
                          position: 7
                    - Tile:
                        inputs:
                          position: 8
        - Text:
            text: ${ensemble.storage.winner}
            styles:
              fontWeight: bold
        - Spacer
        - Button:
            label: Start over
            onTap:
              executeCode:
                body: |
                  //@code
                  initializeGame();


Tile:
  inputs:
    - position
  body:
    Column:
      onTap:
        executeCode:
          body: |
            //@code
            setTileValue(position, ensemble.storage.currentTurn);
            switchTurn();
            calculateWinner();
      styles:
        padding: 24
        borderColor: 0x22000000
        crossAxis: center
      children:
        - Text:
            text: ${ensemble.storage.tiles[position]}
            styles:
              fontSize: 20


Global: |-
  //@code

  function initializeGame () {
    ensemble.storage.currentTurn = "X";
    ensemble.storage.winner = "";
    ensemble.storage.tiles = ["","","","","","","","",""];
  }
        
  function switchTurn () {
    if (ensemble.storage.currentTurn == "X")
      ensemble.storage.currentTurn = "O";
    else
      ensemble.storage.currentTurn = "X";
  }

  function setTileValue(position, value) {
    var tiles = ensemble.storage.tiles;
    tiles[position] = value;
    ensemble.storage.tiles = tiles;
  }

  function calculateWinner() {
    var tiles = ensemble.storage.tiles;
    var lines = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6]
    ];

    lines.map(function(line) {
      var first = tiles[line[0]];
      var second = tiles[line[1]];
      var third = tiles[line[2]];

      if ( first != "" && second == first && third == first) {
        ensemble.storage.winner = "The winner is " + first;
      } else if (tiles.indexOf("") == -1) {
        ensemble.storage.winner = "It's a tie!";
      }
    });
  }
```
