### ISSUE TITLE
Conditional widget support for custom widgets 

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#479]
Passing a custom widget to Conditional does not work:

Example from [this screen](https://studio.ensembleui.com/app/Oa2NZxdMRjgQoKfXXAxp/screen/fzRFxkFtiHugCzhhcr5n)

In this example, passing `Winner` custom widget does not work.

```yaml
        # Game state
        - Conditional:
            conditions:
              - if: ${ensemble.storage.gameState == "InProgress"}
                Text:
                  text: The game is on!
              - elseif: ${ensemble.storage.gameState == "Over"}
                Winner
              - elseif: ${ensemble.storage.gameState == "Tie"}
                Text:
                  text: It's a tie!
```
