### ISSUE TITLE
DataGrid: Kitchen sink - remove button on a row does not work

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#494]
Open Kitchen Sink
Tap on Layout Widgets
DataGrid
Load Dynamic Data

Now find the remove button next to a row and click on it. It doesn't do anything. 

also help improve the DataGrid styling a bit. Just go with the basic style [here](https://api.flutter.dev/flutter/material/DataTable-class.html)

**Comment by kmahmood74** [comment]
if you turn device preview off, you can scroll fine. It's yet another regression with device previews. Kindly turn off device preview until we have fixed all the issues related to it. @vinothvino42 are you working on fixing the device preview issues?

**Comment by vinothvino42** [comment]
@kmahmood74 Okay. There is one property [useInheritedMediaQuery](https://master-api.flutter.dev/flutter/material/MaterialApp/useInheritedMediaQuery.html) in the MaterialApp is deprecated, the device preview package uses it. I created an [issue 226](https://github.com/aloisdeniel/flutter_device_preview/issues/226) for that in the device preview. But I guess it's not related to that. I tried running the sample material app with `device_preview` and it works fine. I'm trying to figure out the issue, it's somewhere happening in our ensemble app. Please see the [video](https://drive.google.com/file/d/1i9tbPR-m77WS9lOekS4qwQoLC4U4E9RU/view?usp=share_link)

**Comment by vinothvino42** [comment]
@kmahmood74 Do we need to change the DataGrid to a basic style? I think it's added to show how we can style all the borders of the DataGrid view. Or we can convert it to the default basic style but anyway, the user needs to know all the capabilities of DataGrid styling via a proper documentation


```yaml
border:
  top:
    color: red
    width: 6
  bottom:
    color: blue
    width: 8
  left:
    color: amber
    width: 10
  right:
    color: yellow
    width: 10
  horizontalInside:
    color: grey
    width: 2
  verticalInside:
    color: blue
    width: 8
```

**Comment by kmahmood74** [comment]
> @kmahmood74 Okay. There is one property [useInheritedMediaQuery](https://master-api.flutter.dev/flutter/material/MaterialApp/useInheritedMediaQuery.html) in the MaterialApp is deprecated, the device preview package uses it. I created an issue for that in the device preview. But I guess it's not related to that. I tried running the sample material app with `device_preview` and it works fine. I'm trying to figure out the issue, it's somewhere happening in our ensemble app. Please see the [video](https://drive.google.com/file/d/1i9tbPR-m77WS9lOekS4qwQoLC4U4E9RU/view?usp=share_link)

this was the selectionArea issue you identified right?

**Comment by kmahmood74** [comment]
> @kmahmood74 Do we need to change the DataGrid to a basic style? I think it's added to show how we can style all the borders of the DataGrid view. Or we can convert it to the default basic style but anyway, the user needs to know all the capabilities of DataGrid styling via a proper documentation
> 
> ```yaml
> border:
>   top:
>     color: red
>     width: 6
>   bottom:
>     color: blue
>     width: 8
>   left:
>     color: amber
>     width: 10
>   right:
>     color: yellow
>     width: 10
>   horizontalInside:
>     color: grey
>     width: 2
>   verticalInside:
>     color: blue
>     width: 8
> ```

yes you are right. The style are pretty horrible. Please make the remove button work and @amin-nas or Andrew can give us the styles

**Comment by vinothvino42** [comment]
Yes. `SelectionArea` widget issue is related to device preview.

**Comment by vinothvino42** [comment]
I identified this remove button on tap issue too. It's happening due to the borderRadius. Try commenting on the borderRadius in the DataGrid and it will work. The borderRadius is not working in the DataGrid view

**Comment by kmahmood74** [comment]
yes, it used to work. I have tested it many times before. @amin-nas was probably using it inside a customer app as well. @amin-nas is the sah app broken because of this regression, can you please check.

**Comment by amin-nas** [comment]
Confirming no impact to the customer app as we use very few styling properties there:
```yaml
            - DataGrid:
                headingTextStyle: { font: heading, fontSize: 16, color: grey }
                horizontalMargin: 0
                headingRowHeight: 32
                columnSpacing: 60
```
