### ISSUE TITLE
Support staggered grid (like pinterest) for modern image layout

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#501]
See this - https://pub.dev/packages/flutter_staggered_grid_view

Start by proposing a ELD (yaml) for it. 

1. Grid must be able to take its data from either item-template or directly as children (not both). Just like all other templated widgets

cc @vusters @sibteali786 @amin-nas

**Comment by vinothvino42** [comment]
Proposal for Staggered Grid View

```yaml
View:
  header:
    title: Staggered Grid View
  body:
    StaggeredGrid: 
      styles: { horizontalGridCount: 4, verticalGridCount: 4, horizontalGap: 5, verticalGap: 5, dynamicTileCount: true }
      children:
        - GridTile:
            styles: { horizontalTileCount: 2, verticalTileCount: 2 }
            widget:
              Image:
                styles: { borderColor: green, borderWidth: 1, fit: fitWidth}
                source: https://i.imgur.com/Tf67Bu6.png
      item-template:
        data: ${getPlaces.body.places}
        name: place
        template:
          GridTile:
          styles: { horizontalTileCount: place.horizontalTileCount, verticalTileCount: place.verticalTileCount }
          widget:
            Image:
              styles: { borderColor: green, borderWidth: 1, fit: fitWidth}
              source: place.image
```

Here, You need to pass the horizontalTileCount and verticalTileCount with different numbers for each Grid Item. So that the Staggered grid will have different items in different size

<img src="https://github.com/EnsembleUI/ensemble/assets/12869588/89a3cec5-5014-4e7f-be0e-03fa0135f764" width="350" />
