### ISSUE TITLE
Setting button fontSize ignores theme's font family

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#502]
See weather app as example:
https://studio.ensembleui.com/app/IjZZeDQTaAvDgnHWVPs7/screen/gBrOpcu3gOxW9v35LLKm

App's theme include font family. Button widget uses the theme's font, but when setting `fontSize`, the font family is ignored.

**Comment by kmahmood74** [comment]
still an issue, @amin-nas ? please assign

**Comment by amin-nas** [comment]
Yes, assigning to @snehmehta :)

**Comment by amin-nas** [comment]
Supported through theming now:

```
Styles:
  Button:
    labelStyle:
      fontFamily: Fira Code
```
