### ISSUE TITLE
TextInput should be customizable  

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#514]
Currenlty the TextInput has few limitations in terms of how much we can customize it.
Suggestions 
- Fill color of the input should be customizable like in this design where both icon and fill color can be modified along with text color 
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/b0689711-1e29-43de-ba6d-a45e168e9e34)
-   When we select TextInput the outline color should also be customizable like yellow in my given example 
- Also better if we can apply styles to icon as well ( size, color etc )

**Comment by snehmehta** [comment]
@sibteali786 you can customize outline border and icon like following.
```yaml
        - TextInput:
            styles: {fillColor: black, focusedBorderColor: yellow }
            hintText: Search
            icon:
              name: search
              color: yellow
```

**Comment by snehmehta** [comment]
and for textStyle and hintStyle I have created PR, soon you'll be able to following.
```yaml
        - TextInput:
            styles: {fillColor: black, focusedBorderColor: yellow }
            textStyle: { color: yellow, fontSize: 24 }
            hintStyle: { color: grey }
            hintText: Search
            icon:
              name: search
              color: yellow
```
