### ISSUE TITLE
Support dynamically generated screens inside navigateScreen/navigateModal 

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#523]
use cases: 
1. generating screen from server side dynamically based on context i.e. screen does not exist statically on the server
2. multiple screens exist and server needs to determine the best one based on context and return that (tailor UI for context)

Problem:
Currently navigateScreen and naivgateModal calls require a hardcoded screen name

Proposed Solution:
provide the ability to call an API to get the screen definition. Something like - 

```
              invokeAPI:
                name: createToDo
                inputs:
                  name: 'some value'
                onResponse:
                     navigateScreen:
                          content: ${response.body.screenContent}
```
same for navigateModal. Also this should inside js code as well
