### ISSUE TITLE
Metadata for inputs

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#533]
As an Ensemble app developer, I want to optionally be able to set type and description for a View or Widgets inputs so other users of my widgets/views know what to pass to it.

```yaml
Widget:
  inputs:
    - id
    - age:
        required: false
        type: integer
        description: Users age
        default: 18
        testValue: 18
```

`testValue` is only passed when viewing the app in debug mode or studio's preview.
