### ISSUE TITLE
Undefined id inside Global Function

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#536]
## UseCase:
I want to manipulate some styles of a button using its ID inside a global function.

### Code which shows error:
```
View:
  # Optional - style the screen
  styles:
    scrollableView: true

  # Optional - set the header for the screen
  header:
    title: Header

  # Specify the body of the screen
  body:
    Calendar:

Calendar:
  body:
    Button:
      id: liveButton
      styles: { color: 0xFFc61088, borderColor: 0xFFc61088, backgroundColor: white, borderRadius: 30, borderWidth: 2, outline: true, fontSize: 12, fontWeight: bold }
      label: LIVE
      onTap: |-
        resetCalendarColors()
                
Global: |-
  function resetCalendarColors() {
    liveButton.backgroundColor = "blue"
    liveButton.color = 0xFFc61088
  }
```

### Error:
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/e4257fb9-6c56-4750-87e7-b5fa27b19f95)

### Code which works fine:
```
View:
  # Optional - style the screen
  styles:
    scrollableView: true

  # Optional - set the header for the screen
  header:
    title: Header

  # Specify the body of the screen
  body:
    Button:
      id: liveButton
      styles: { color: 0xFFc61088, borderColor: 0xFFc61088, backgroundColor: white, borderRadius: 30, borderWidth: 2, outline: true, fontSize: 12, fontWeight: bold }
      label: LIVE
      onTap: |-
        resetCalendarColors()
        
Global: |-
  function resetCalendarColors() {
    liveButton.backgroundColor = "blue"
    liveButton.color = 0xFFc61088
  }
```

ScoreZone App screen link: https://studio.ensembleui.com/app/TQP5125dbdMgNdDpKzWz/screen/9deTnsGX2cBFWqlbzgwc
