### ISSUE TITLE
ShowToast does not work on custom widget's onLoad

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#553]
When executing a ShowToast on a custom widget's onLoad, the toast does not render.

```yaml
View:
  body:
    Column: 
      styles: { mainAxis: center }
      children:
        - ToastTest

ToastTest:
  onLoad:
    showToast:
      message: Success! by default at screen's top right
      options:
        dismissable: true
        type: success
        duration: 3
      styles:
        backgroundColor: 0xFFEDEDED
        padding: 16 24
  body:
    Text:
      text: This widget shows a toast message on load
```
