### ISSUE TITLE
Want to set FittedRow's childrenFits array or its values programmatically

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#555]
Can we programmatically set FittedRow's childrenFits array?

## Goal:
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/1573845d-7863-4aa0-b974-12e34c04ef61)

## Results after using Existing approaches
result when used with Row rather than FittedRow:
```
- Row:
      styles: { margin: 0 20 0 0}
      children:
        - Text:
            styles: { backgroundColor: 0xFFe80f88, borderRadius: 10, width: 15 }
        - Text:
            styles: { backgroundColor: 0xFFe0e0e0, borderRadius: 10, width: 8 }
        - Text:
            styles: { backgroundColor: 0xFF35383f, borderRadius: 10, width: 10 }
```
![Screenshot 2023-06-01 215353](https://github.com/EnsembleUI/ensemble/assets/32386713/4eac6097-609b-4008-9a1b-d28b4599cd3d)

result when FittedRow is used with each child's width is set:
```
- FittedRow:
      styles: { margin: 0 20 0 0}
      children:
        - Text:
            styles: { backgroundColor: 0xFFe80f88, borderRadius: 10, width: 15 }
        - Text:
            styles: { backgroundColor: 0xFFe0e0e0, borderRadius: 10, width: 8 }
        - Text:
            styles: { backgroundColor: 0xFF35383f, borderRadius: 10, width: 10 }
```
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/7cbb4aa4-3669-4e18-a3b7-b0b748033d1e)

## Requirement
I want something like this

either inline like:
```
- FittedRow:
      styles:
         childrenFits: ${[Math.floor(device.width / 50), 10, ensemble.storage.thirdChild]}
```

or in js like:
```
onLoad: |-
    fr.childrenFits = [Math.floor(device.width / 50), 10, 4]
- FittedRow:
            id: fr
```

using this in this screen of scorezone app https://studio.ensembleui.com/app/TQP5125dbdMgNdDpKzWz/screen/AMD1aig82aKoeJLSbqHm
