### ISSUE TITLE
View's footer prop is inconsistent with body and does not allow for transparent or gradient background

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#564]
Footer syntax should be consistent with body syntax, and allow me to set a transparent or gradient background:

```yaml
View:
  body:
    Column:
  footer:
    Column:
      styles:
        backgroundColor: 0x00FFFFFF
      children:
```
