### ISSUE TITLE
Device width not returned when using device preview

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#573]
When I enable device preview in studio, I expect `device.width` to return according to selected device. But it always return the browser's iframe width.

```yaml
View:
  body:
    Column:
      styles:
        padding: 24
      children:
        - Text:
            id: test
        - Button:
            label: Print device width
            onTap: |
              //@code
              test.text = device.width;
```
