### ISSUE TITLE
Not being able to use Tilda ~ in jsonPath expression

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#575]
## Use Case
I want to be able to get all the keys of from within my json data, and for that jsonPath expression is **$.*~** It works fine on an [online evaluator](https://jsonpath.com/) 
![image](https://github.com/EnsembleUI/ensemble/assets/32386713/cd0e9a11-398a-4435-915c-73dd1ea9271c)

## Issue
Here is how im using it to prepare some data for chartjs in my [screen](https://studio.ensembleui.com/app/Q1Qbffit5MH6lFfo50nh/screen/2OGD0CfrBWIhZKFcXQ0n) but it doesn't work. Maybe because limited functionality of jsonPath in js !!

```yaml
View:
  # Optional - style the screen
  styles:
    scrollableView: true

  # Optional - set the header for the screen
  header:
    title: Home
    
  onLoad:
    invokeAPI:
      name: getTeamStats
      inputs:
        season: 2022
        leagueId: 39
        teamId: 50

  # Specify the body of the screen
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - MinuteChart:
            inputs:
              label: Minute wise Total Goals
              data: ${getTeamStats.body.response.goals.for.minute}

MinuteChart:
  inputs:
    - label
    - data
  onLoad: |
    //@code
    // $.*~
    console.log("data is "+data) 
  body:
    ChartJs:
      styles: { width: 400 }
      config: |
            {
              type: "line",
              data: {
                labels: ${data.path('$.*~', null)}, 
                datasets: [{
                  label: "${label}",
                  backgroundColor: "rgb(255, 99, 132)",
                  borderColor: "rgb(255, 99, 132)",
                  data: ${data.path('$..total', null)}
                }]
              }
            }

API:
  getTeamStats:
    inputs: [ season, leagueId, teamId ]
    uri: https://v3.football.api-sports.io/teams/statistics?league=${leagueId}&team=${teamId}&season=${season}
    method: GET
    headers:
      x-apisports-key: c944082bd6659f77f42b3f80ce4e2a92
    # onResponse: |
    #   console.log(response.body.response)
```
