### ISSUE TITLE
FittedRow's onTap does not work

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#593]
```yaml
View:
  body:
    Column:
      styles:
        padding: 24
        gap: 24
      children:
        - FittedRow:
            children:
              - Text:
                  text: Fitted row
            onTap:
              openUrl:
                url: 'https://studio.ensembleui.com/preview/index.html?appId=e24402cb-75e2-404c-866c-29e6c3dd7992'
        - Row:
            children:
              - Text:
                  text: Row
            onTap:
              openUrl:
                url: 'https://studio.ensembleui.com/preview/index.html?appId=e24402cb-75e2-404c-866c-29e6c3dd7992'
```
