### ISSUE TITLE
Sound Effects/Haptics

### ISSUE THREAD

**Issue by RuthLHanan** [EnsembleUI/ensemble#595]
Adding sound effects and other haptics that involve playing with your sense of touch

**Comment by hemish11** [comment]
For the yaml part, I would say that we create a wrapper widget like Haptic and only pass the id to it, and maybe one or two parameters as in haptic type (for iOS, not sure for that tho), and then the user would be able to control haptic using the methods for the given id. How does that sound?

Here's the exact yaml:
```yaml
View:
  header:
    title: Haptic
  Haptic:
    id: MyHaptic
    child:
      Column:
        styles: { gap: 16, padding: 24 }
        children:
          - Button:
              label: Short Haptic
              onTap: |
                MyHaptic.short();
          - Button:
              label: Long Haptic
              onTap: |
                MyHaptic.long();
          - Button:
              label: Double Haptic
              onTap: |
                MyHaptic.double();
```
