### ISSUE TITLE
Inputs clear r @

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#597]
Steps:

1. Use below yaml
2. type this to into the text field `r@something`
3. press tab
4. the input value is changed to `something`

```yaml
View:
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - TextInput:
            label: type r@something and press tab
        - TextInput:
            label: some other field
```
