### ISSUE TITLE
Copy to Clipboard is broken

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#599]
I tried this but copyToClipboard doesn't seem to work

```yaml
- Button:
            startingIcon:
              name: copy
              library: fontAwesome
              color: 0xFF04EAB9
            label: Copy
            onTap:
              copyToClipboard:
                value: ${code}
            styles:
              padding: 10
```
