### ISSUE TITLE
Not uniformity for usage of Icon widget

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#618]
The way examples for using Icon with different widgets like Button, Icon itself, menu etc defined in ensemble kitchen sink is not uniform. It should be consistent or at least each example should contain all the possible ways to use icons.
Example:
```yaml
- Button:
      label: More on this 
      endingIcon:
        name: solidStar
        library: fontAwesome
        size: 10
        color: 0xFFFECF15  
```
here i have mentioned the library separately using the library property but ig it if we only provide icon name and library name in same line it works as well as mentioned by @vusters in the builder support query i asked earlier for a custom font Icon example.
