### ISSUE TITLE
ability to define re-usable code libraries and import them where needed

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#62]
1. Defining re-usable code
Just like we define screens and widgets as re-usable, code itself is defined as another artifact except this artifact contains javascript code. 
Re-usable code contains - 
- functions such as
```js
function add(a,b) { return a+b;}
```
- vars such as 
```js
var counter = 0;
```
2. Scope of imports
Each import is resolved at the screen level. Code libraries cannot be used to share state across screens or widgets. 
Example
myLib
```js
var counter = 0;
```
Let's say myLib is imported in `Home` and `Profile` screens. The code in the `Home` screen updates the `counter` to 10. The `Profile` screen or any other screen that imported myLib will still get their own independent `counter` as 0. 

3. How are the variables and functions in re-usable libraries resolved in case of naming conflicts
We apply the rules that ES5/HTML uses i.e. the last one wins except when the same library has been included multiple times. 
Example - 
commonUtils
```js
var counter = 0;
function add(a,b) {return a + b;}
```
apiUtils
```js
var counter = 10;
function add(a,b,c) {return a+b+c;}
```

Let's say the screen imports commonUtils and then apiUtils. Value of the counter will be 10 and the add function from apiUtils will be one invoked when anyone calls add in the page. 

Same applies to re-usable widgets as well. Code libraries at the screen level are automatically inherited by all the widgets in the page. Widgets can have their own libraries as well. If widget imports the same library that is already imported in the screen it resides in, it is *not* imported again. Any new libraries are imported in the order defined.

5. Importing code is supported in both Screens and Widgets as follows. Currently importing code within a code library is not supported. It is being tracked here - #1142 

Importing Code in a screen - 

```
Import:
  - apiUtils
  - common

View:
    # Optional - style the screen
    styles:
      scrollableView: true

    # Optional - set the header for the screen
    header:
      title: Home
    onLoad: |
      saveName('Khurram','Mahmood');
      console.log('name is ='+storageName);

    # Specify the body of the screen
    body:
      Column:
        styles:
          padding: 24
          gap: 8
        children:
          - Text:
              text: Hello ${ensemble.storage.jslibtest.name.first} ${ensemble.storage.jslibtest.name.last}
```
Importing in a re-usable widget - 

```
Import:
  - common
  - apiUtils
Widget:
    inputs:
      - inputName
    body:
      Column:
        children:
          - Text:
              text: ${inputName.first} ${inputName.last}
          - Button:
              text: ${storageName.name.first} ${storageName.name.last}
              onTap: |-
                sayHello();
                console.log('name:'+getName());
                callAPI('mockAPI',{});
```
