### ISSUE TITLE
Ability to set focus to an input

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#624]
```yaml
View:

  onLoad: |
    //@code
    email.focus();

  body:
    Column:
      children:
        - TextInput:
            id: email
```
