### ISSUE TITLE
TabBar indicator and styling bug

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#628]
1. When I define tabPadding, the indicator line shrinks
2. Setting indicatorThickness to 0 does not work
3. I cannot style the bottom border (thickness, color)

```yaml
View:
  body:
    Column:
      children:
        - TabBar:
            styles:
              tabPadding: 0 24 0 0
              indicatorThickness: 0
            items:
              - label: First Tab
                widget: 
                  Column:
                    styles: { padding: 30, crossAxis: center}
                    children:
                      - Text:
                          text: First Tab content
              - label: Second Tab
                widget: 
                  Column:
                    styles: { padding: 30, crossAxis: center}
                    children:
                      - Text:
                          text: Second Tab content
```
