### ISSUE TITLE
Masking of text input for phone number

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#629]
When entering a phone number, I want the input to be masked as user types in.

```yaml
TextInput:
  inputType: phone
  maskValue: true
```

https://github.com/EnsembleUI/ensemble/assets/491202/2281dc2a-b623-4e20-8334-bbc149ac10ac
