### ISSUE TITLE
Ability to have an expression for invokeAPI's name

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#630]
```yaml
View:
  onLoad:
    invokeAPI:
      name: "${ condition ? apiA : apiB }"
```
