### ISSUE TITLE
Emojis in Markdown breaking

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#637]
In Markdown you can add emojis BUT ⚠️ this emoji work and 💻 this doesn't

In kitchen sink example all are working because top Column has the `scrollable: true` property, but I've Emoji in a external widget so it not working even if I try to add `scrollable: true` anywhere

**Comment by vusters** [comment]
I"m not clear on what the ask is. @sharjeelyunus  please attach a picture of some sort. Scrollable should not be breaking emoji, plus the fact that some work and some don't make me think this is not a regression.

**Comment by sharjeelyunus** [comment]
See the emoji on line 19 (⚠️) it works

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/6c3e20f1-e7a1-4734-97b4-41bdcb1e2cc6)

Now see the emoji on line 19 again (💻). this doesn't work

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/6f69fb9f-0228-45bb-b205-03a3008441aa)

**Comment by vinothvino42** [comment]
@sharjeelyunus @vusters I tried the Markdown issue

Here's my code:

This is not working. I got an exception in the YAML parser, it couldn't parse this emoji.
```yaml
CustomMarkdown:
  inputs:
    emoji: 💻
```

When I wrapped the emoji into a string literal, then it's working
```yaml
CustomMarkdown:
  inputs:
    emoji: "💻"
```

Custom Widget:
```yaml
CustomMarkdown:
  inputs:
    - emoji
  body:
    Column:
      styles:
        gap: 16
      children:
        - Markdown:
            text: |
              ${emoji}
```
