### ISSUE TITLE
Setting visible property of DataRow in code is not working as expected

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#640]
## Issue
Setting visible property of DataRow in code is not working as expected. Kindly run the given code to reproduce this issue.

## Example Code
```yaml
View:
  body:
    Column:
      children:
        - Button:
            label: Make row visible
            onTap:
              executeCode:
                body: |
                  //@code
                  myRow.visible = true;

        - Column:
            children:
              - DataGrid:
                  DataColumns:
                    - label: Hotel Name
                      type: text
                    - label: Location
                      type: text
                  children:
                    - DataRow:
                        children: 
                          - Text:
                              text: Hello
                          - Text:
                              text: Hello
                    - DataRow:
                        visible: false
                        id: myRow
                        children:
                          - Text:
                              text: Test
                          - Text:
                              text: Test
```
