### ISSUE TITLE
Need a way to validate multiple Forms using a single button

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#641]
## Use Case
I want to validate 2 forms using a single button, i have some widgets (including custom ones) in between those 2 forms, so it would be helpful to have this feature. Below is my code. 

## My code
```yaml
View:
  Column:
    children:
      - Form:
          styles: { labelPosition: start, gap: 16 }
          children:
            - TextInput:
                label: text1
                required: true
            - TextInput:
                label: text2
                required: true
      - Spacer:
          styles:
            size: 1
      - Text: # Custom widget
          text: blaa blaa
      - Form:
          styles: { labelPosition: start, gap: 16 }
          children:
            - TextInput:
                label: text3
                required: true
            - TextInput:
                label: text4
                required: true
      - Button:
          label: save
          validateForm: true
``` 

## Idea
Maybe we can pass an id to each Form widget and then accept an array of form ids instead of a boolean on validateForm property of Button widget.
