### ISSUE TITLE
conditional expression returning strings even for cases where hex values or number might be needed

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#658]
### Issue 
- The inline conditional expression typically works when we wrap it in double or single quotes.
like 
``` 
- Row:
    id: rowId
    styles:
      borderColor: 0xFFDEDED4
      crossAxis: center
      mainAxis: center
      borderRadius: "${borderRadius === null ? 8 : borderRadius}"
      height: 50
    children:
      - Text:
          id: providerText
          styles: 
            textStyle:
              fontSize: 12
``` 
here this inline expression returns an error 
![image](https://github.com/EnsembleUI/ensemble/assets/62849614/c496c6f5-759e-4c38-8d06-c728542aaab3)

- This error might be related to issue #657 but i am not sure of it. 
- Way around is to use if condition in js code block using an id ( providing id to widget ) to assign a value conditionally. 

In simple words Inline expression works fine for cases where property accepts strings otherwise if it accept integers like in above cases then expression evaluates to false. 

cc: @vusters @amin-nas
