### ISSUE TITLE
Integrate Plaid Link

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#659]
https://plaid.com/docs/link/

See if we can use this - https://pub.dev/packages/plaid_flutter

Please start by proposing the YAML for it.

**Comment by kmahmood74** [comment]
cc @vusters 

This is needed by two customers so a bit urgent

**Comment by vinothvino42** [comment]
@kmahmood74 @vusters 
Only the ITEM (a bank account) linking can be done from the client side. Other products (balance, transaction, auth, identity verification), etc can be done from the backend side. Need to send requests from the client side to the server, then server requests for the product-related API to the plaid service.

**EDL**
```yaml
View:
  header:
    title: Plaid Link Integration
  styles:
    scrollableView: true
  onLoad:
    invokeAPI:
      name: getLinkTokenFromServer
  body:
    Column:
      styles:
        gap: 24
        padding: 24
      children:
        - Button:
            label: Link Account
            onTap:
              openPlaidLink:
                id: plaidId
                options:
                  linkToken: ${getLinkTokenFromServer.body.linkToken}
                onSuccess:
                  invokeAPI:
                    name: sendPublicTokenToServer
                    inputs:
                      name: ${plaidId.publicToken}
                onEvent: |
                  //@code
                  console.log("All Plaid Events")
                onExit: |
                  //@code
                  console.log("Something went wrong!")

API:
  getLinkTokenFromServer:
    uri: https://ensembleui.com/api/plaid/get_link_token
    method: GET
    onResponse: |
      //@code
      console.log('Link Token' + response.body.linkToken);

  sendPublicTokenToServer:
    inputs:
      - publicToken
    uri: https://ensembleui.com/api/plaid/send_public_token
    method: POST
    body:
      records:
        - fields:
            publicToken: "${publicToken}"
```

Here, 
Once the openPlaidLink is triggered with linkToken, it will open a webview with plaid onboarding, bank selection, etc. Once we logged-in with any of the bank then the account is linked to our app, we'll get the public_token in the onSuccess callback. The onSuccess callback will be called only after the ITEM added (meaning bank account linked). We'll need to pass this public_token to our server, then the server needs to exchange the public_token to plaid service to get the actual token. Only with this access_token we can able to interact to their products like auth, transaction, balance, identity verification etc.
