### ISSUE TITLE
Need the (ascii) value of key pressed when onKeyPress event is fired

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#668]
In Tin app, I need the (ascii) value or actual string representation of key itself which was pressed inside **onKeyPress** event!

Why?

When user presses backspace key on keyboard, I want to be able to delete the current textfield's value and move the focus to previous textfield.

![image](https://github.com/EnsembleUI/ensemble/assets/32386713/9b0031c5-d090-4bf2-a6d4-0265476ddc52)

Sample Code:

```yaml
TextInput:
    id: verificationDigit6
    required: true
    maxWidth: 40
    expanded: true
    onKeyPress:
      invokeAPI:
        name: confirmPhone
        inputs:
          userId: ${userId}
          phoneNumber: ${phoneNumber}
          onboardingTicket: ${onboardingTicket}
          code: ${verificationCode.value
```
