### ISSUE TITLE
Need a builtin widget for OTP code

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#670]
Need a builtin widget for verifying the OTP code

![image](https://github.com/EnsembleUI/ensemble/assets/32386713/533930b3-8b1e-499e-8b0d-f0866afb2107)

### Current Custom Implementation:
- Tin app
- Onboarding_ConfirmAccount screen
- https://studio.ensembleui.com/app/Oq9d5Zy3Mky2XvyDx3HI/screen/Zs3TIEy8EsVkAHM8gT1d?propertyPanelEnabled=true&instantPreviewDisabled=false&editorV2Enabled=true
```yaml
Form:
  children:
    - Row:
        styles:
          margin: 0 5
          gap: 10
        children:
          - TextInput:
              id: verificationDigit1
              required: true
              maxWidth: 40
              expanded: true
              onKeyPress: 
                executeCode:
                  body: |
                    verificationDigit2.focus()
                    if (this.value == '') {
                      disabledButton.visible = true;
                      enabledButton.visible = false;
                    } else {
                      disabledButton.visible = false;
                      enabledButton.visible = true;
                    }
          - TextInput:
              id: verificationDigit2
              required: true
              maxWidth: 40
              expanded: true
              inputType: 
              onKeyPress: 
                executeCode:
                  body: |
                    verificationDigit3.focus()
          - TextInput:
              id: verificationDigit3
              required: true
              maxWidth: 40
              expanded: true
              onKeyPress: 
                executeCode:
                  body: |
                    verificationDigit4.focus()
          - TextInput:
              id: verificationDigit4
              required: true
              maxWidth: 40
              expanded: true
              onKeyPress: 
                executeCode:
                  body: |
                    verificationDigit5.focus()
          - TextInput:
              id: verificationDigit5
              required: true
              maxWidth: 40
              expanded: true
              onKeyPress: 
                executeCode:
                  body: |
                    verificationDigit6.focus()
          - TextInput:
              id: verificationDigit6
              required: true
              maxWidth: 40
              expanded: true
              onKeyPress:
                invokeAPI:
                  name: confirmPhone
                  inputs:
                    userId: ${userId}
                    phoneNumber: ${phoneNumber}
                    onboardingTicket: ${onboardingTicket}
                    code: ${verificationCode.value
```

**Comment by vusters** [comment]
Please propose the YAML to start out.

**Comment by anserwaseem** [comment]
@vusters  
```yaml
OtpWidget:
  id: String
  digits: Integer
  inputType: Alphabetic | Alphanumeric | Numeric | Boolean | Uppercase Alphabetic | Lowercase Alphabetic | Uppercase Alphanumeric | Lowercase Alphanumeric
  onInputStarted: Action # fire when a key is pressed for the first input
  onInputCompleted: Action # fire when a key is pressed in last input 
  shouldWait: Boolean # IF(true) then onInputFilled would not be fired until user explicitly presses 'Enter' ELSE onInputFilled will be fired as soon as last a key is pressed for last input
  enableFocus: Boolean # IF(true) then first input will automatically be focused ELSE it won't

# should automatically handle going to previous field when 'backspace' is pressed

```
