### ISSUE TITLE
User should be able to use voice instead of typing text

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#675]
Use case - 

1. Search using voice
2. Prompt using voice
3. enter text in a text area using voice

this could be a good candidate - https://pub.dev/packages/speech_to_text I have not tested this myself so please test it first. 

Suggestion: 

on TextField (single and multiline), it should be a configuration property such as allowVoiceInput with default = false
Otherwise it should be an action - listen with two callbacks:

unavailable: called if the user denies speech recognition
onComplete: speech is complete. With event.recognizedWords
  
Needed by multiple customers

cc @vusters

**Comment by hemish11** [comment]
@kmahmood74 I would suggest creating an action so that it's easier to access throughout the app and not limited to text field.

**Comment by kmahmood74** [comment]
> @kmahmood74 I would suggest creating an action so that it's easier to access throughout the app and not limited to text field.

I agree, good point. Let's do an action. Actions are incredibly powerful and useful

**Comment by kmahmood74** [comment]
proposed EDL - 

```
Button:
    onTap:
        startListening: #initializes the speechToText if needed
            id: #optional. needed to reference it
            onStatus:  #optional, invoke any action. status is accessed as this.status or use id instead of this 
            onError: #invoke any action. if not specified, we should have a default one to show the error as toast
            onResult: #could be any action. 
            isListening: #boolean
                 
#recognized works from speechToText are always available as lastWords and you should be able to bind to that. Recognized words from the last run are available as this.result or <id>.result. The result object has the following properties - recognizedWords, confidence, hasConfidenceRating
          
```
@vusters ?
