### ISSUE TITLE
Ability to open any url in js code

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#707]
i want to execute openUrl action in js code!

```yaml
openUrl:
  url: https://docs.ensembleui.com/#/build/make-it-interactive/actions-and-events/4-openUrl
  openInExternalApp: true
```
