### ISSUE TITLE
Open Native App's settings via Action and Javascript

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#709]
https://discord.com/channels/1031982848485359626/1138532496619864184/1138532496619864184
https://pub.dev/packages/app_settings

Make sure this can be used as an Action, as well as Javascript (i.e. `device.openAppSettings()` )
```
Button:
  onTap:
    openAppSettings:
      target: <AppSettingType>
```
