### ISSUE TITLE
Ability to re-render the screen on NavigateBack action

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#711]
Need to re-render the screen on NavigateBack action! (required in Tin app for now)

## UseCase

I have a screen A which contains some grid showing data (item-templated from local storage). User navigates from screen A to screen X, does some work (updates the data). When user taps on back button and `navigateBack` action is triggered, user arrives back to screen A **BUT** the updated data is not shown (because navigateBack action doesn't re-render the screen so bindings never get triggered).

Workaround? just use `navigateScreen: screen A` when navigating back from screen X!! Works fine for this case.

but now let's assume we have screen B, C and D from which user can navigate to screen X, now `navigateScreen` action cannot be used on tapping back button because nobody knows from which screen user arrived at screen X!

## Possible Solution

Having a prop in `naviagteBack` action that forces a re-render of previous screen

**Comment by vusters** [comment]
Re-render the screen is problematic (the main screen may requires the input from its previous screen) and probably not the right thing to do. Here's a better approach:
1. Add a callback to navigateScreen/navigateModalScreen:
```
...
## main screen
Button:
  onTap:
    navigateScreen:
      name: nextScreen
      onNavigateBack: |-   # Action called when dismissing (modal) or navigating back from the "nextScreen"
        //@code
        var dataReturned = event.data;      # nextScreen can optionally pass back any data
```
2. Screen can pass data upon navigated back, or upon dismissed (if modal screen)
```
## nextScreen
Button:
  onTap:
    navigateBack
      data: #  optional, can be simple or complex
        var1: ${something}
        var2: ${something else}
```

**Comment by anserwaseem** [comment]
@vusters hey! it doesn't seem to work. Tried with this code:

### main screen
```yaml
View:
  header:
    title: Home
  body:
    Button:
      label: Checkout Ensemble Kitchen Sink
      onTap:
        navigateScreen:
          name: nextScreen
          onNavigateBack: |-
            //@code
            console.log("navigated back to main screen");
            console.log(event.data);
```

### next screen

```yaml
View:
  header:
    title: Home
  body:
    Button:
      label: Checkout Ensemble Kitchen Sink
      onTap:
        navigateBack:
          data: #  optional, can be simple or complex
            var1: 1
            var2: "s t r i n g"
```
