### ISSUE TITLE
Ability to toggle microphone access when using camera

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#720]
As an app developer, when I use the camera actions, I want to be able to avoid requesting microphone access unless I need it.

```yaml
openCamera:
  options:
    enableMicrophone: ture | false
```
