### ISSUE TITLE
Conditional widget's else clause should be optional

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#755]
The `else` clause should be optional for Conditional widget. If missing it can simply resolve to a SizedBox.shrink(). Currently without the else clause the entire Conditional widget doesn't render.

**Comment by vinothvino42** [comment]
I tested it and it's already working @vusters 

```yaml
View:
  title: Conditional

  body:
    Column:
      styles: { gap: 16, padding: 24 }
      children:
        - Text:
            text: Example 1

        - Conditional:
            conditions:
              - if: ${getValue() == 1}
                Text:
                  text: If Condition Block
              - elseif: ${getValue() == 2}
                Text:
                  text: Else If Statement
              - else:
                Text:
                  text: Else Statement

Global: |-
  //@code

  function getValue() {
    return 3;
  }

```

**Comment by vusters** [comment]
Try the below. The empty Chart should be rendered but it won't work without the irrelevant `else`
```
View:
  onLoad: |
    myChart.config = {}
  body:
    Column:
      styles:
        margin: 24 0
      children:

        - Conditional:
            conditions:
              - if: ${false}
                Text:
                  text: not here
              - elseif: ${true}
                ChartJs:
                  id: myChart
              # - else:
              #   Text:
              #     text: else
              ```
