### ISSUE TITLE
Support Radio Group widget

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#759]
This is a variation of the Dropdown, so it ideally use the same model/controller/widgetState. The difference is each Radio widget can be put inside other widgets but still link to its siblings (meaning all the radio buttons are not necessarily wrapped inside a RadioGroup parent.
```
Column:
  children:
    - RadioButton
         groupId: myGroup
         ....

Column:
  children:
     - RadioButton
          groupId: myGroup
```
