### ISSUE TITLE
Need support for changing styles of whole View conditionally

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#763]
need to change the background color of whole View based on a condition like this:
```yaml
View:
  styles:
    backgroundColor: "${ensemble.storage.isAnyEmailEnabled == false ? yellow : blue}" 
```
