### ISSUE TITLE
r@ gets cleared when passed as string

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#766]
In the following example, UI should render this text:
`peter@ensembleui.com`

But it renders:
`peteensembleui.com`

```yaml
View:
  onLoad: |
    //@code
    ensemble.storage.testEmail = "peter@ensembleui.com";
  body:
    Column:
      styles:
        padding: 24
      children:
        - Text:
            text: ${ensemble.storage.testEmail}
```
