### ISSUE TITLE
Support infinite scrolling for GridView

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#772]
Customer requirement - 

1. User sees n number of cards on the dashboard. API returns not only the cards but also the token to get the next n cards
2. As the user scrolls down to the last card, new cards are fetched from the server. Meanwhile, a loading indicator shows up at the bottom of the page
3. New cards are added to the bottom of the list

Not urgent and can come in later if too much work: to avoid too many images in memory, GridView supports pageSize for number of widgets before server is called and also a maxBufferCount that dictates max number of child widgets that are kept in the buffer. As more are added, some are removed from the start. As user scrolls back up, the removed images are fetched from the server

**Comment by evshi** [comment]
Proposal to extend `item-template` for infinite scrolling

```yaml
item-template:
   #API name
   api: 
   # Flexible query string key-value map
   pageParams:
      limit:
      offset:
```

Alternatively add new `onScrollEnd` event

```
GridView:
    ....
    onScrollEnd:
       # invoke API with params as usual, bind to stored data value
       invokeApi:
           ....
```

@vusters @vinothvino42 WDYT?

**Comment by kmahmood74** [comment]
I think the GridView/onScrollEnd makes more sense and is more flexible as I can call any action to handle onScrollEnd. The item-template one is too limiting as it assumes that all I would do is to call an api on page end. 

Besides the above, we need the ability to specify the loading container when user reaches the end, this is critical as different customers would want different types of loading containers. Other stuff like maxItemsInMemory etc can be added later as I wrote in the description.

**Comment by vinothvino42** [comment]
@evshi 
Yeah, The second one looks good. User can have their own control when the ListView or GridView or any scrollable widget reach the end.

@kmahmood74 
```yaml
LoadingContainer:
  id: userGrid
  isLoading: ${getPeople.isLoading}
  useShimmer: true
  loadingWidget:
    OurCustomListViewLoaderWithShimmerAndShapeWidget:
  widget:
    GridView:
      onScrollEnd:
        invokeAPI:
          name: getPeople

API:
  getPeople:
    uri: https://randomuser.me/api/?results=6
    method: GET

```

**Comment by kmahmood74** [comment]
@vinothvino42 I am assuming that in the response of invokeAPI that is called onScrollEnd, user will update the array that is bound to item-template with the new data. Updating that array should automatically show the new items. 

Will that work?

**Comment by evshi** [comment]
@vinothvino42 that conditional would replace the entire GridView. The loading state has to be a part of the GridView. The data that has already been fetched still needs to be visible. We'll probably need to add the conditional loading view as part of the item-template.

```yaml
GridView:
  item-template:
    Conditional:
       conditions:
          - if: ${getPeople.isLoading && index > storage.getData().length}
             LoadingWidget:
                ....
          - else:
             RowWidget:
                ....
```
