### ISSUE TITLE
Action: dropdown onTap icon or button

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#773]
Need an action to show dropdown like this when I click on an icon

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/90c6f9b3-3c17-421a-95da-0734ce2240af)

**Comment by vusters** [comment]
Enhance PopupMenu. It was half done.

**Comment by kmahmood74** [comment]
it's in progress but not assigned to anyone? @vusters ?

**Comment by sharjeelyunus** [comment]
see this use case, in header, we have a row, onTap of the row we're opening a drowdown, there should be a dropdown action, which can be called with action (onTap) and its items should be customizable (i.e we can pass the ui to the item)

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/f3c1d011-cc3f-4fb5-90ab-fcdc7f282d1b)

**Comment by sharjeelyunus** [comment]
Suggested EDL

```yaml

Row:
  onTap:
      openDropdown:
          items: ${getProperties.body}
          name: property
          widget: DropDownItem
  children:
     - Image
     - Text
     - Icon
     
 DropDownItem:
    inputs:
       - property
    body:
       Row:
          onTap:
              # store selected item in storage
          children:
              - Image
              - Text
              - Icon
```
