### ISSUE TITLE
Sidebar's menu item icons do not appear

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#775]
See kitchen sink:
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/QZyoRkHHrHEAkGJMwoNU

## details
Since the YAML for menu's items have changed, the icons do not appear anymore.

Before:
```yaml
View:
  menu:
    Sidebar:
      items:
        - label: Home
          icon: home
          page: Home
```

New format:
```yaml
View:
  menu:
    Sidebar:
      items:
        - label: Home
          icon: 
            name: home
          page: Home
```

bug:
<img width="285" alt="image" src="https://github.com/EnsembleUI/ensemble/assets/491202/99325ae1-9dea-49e5-8f25-5cbbdc2443ef">
