### ISSUE TITLE
uploadFiles not giving any response

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#780]
when I use uploadFiles it gives a response in network tab, but not in yaml i.e onComplete or onResponse, need that response to call another api

see this

```yaml
openCamera:
                id: profilePhoto
                options:
                  allowGalleryPicker: true
                  allowCameraRotate: false
                  allowFlashControl: true
                  enableMicrophone: false
                  preview: true
                  maxCount: 1
                  mode: photo
                onComplete:
                  uploadFiles:
                    id: imageUploader
                    uploadApi: uploadProfilePicture
                    files: ${profilePhoto.files[0]}
                    fieldName: image
                    onComplete:
                      executeCode:
                        body: |
                          //@code
                          console.log('profile picture uploaded');
                          personProfile.source = profilePhoto.files[0].path;
                          ensemble.storage.image = response.body;
```

API Definition

```yaml
uploadProfilePicture:
    method: POST
    uri: https://api.dev.myplace.co/api/v2/profile-picture
    headers:
      Authorization: Bearer ${ensemble.storage.token.access_token}
    onResponse:
      executeCode:
        body: |
          //@code
          console.log(response.body);
          ensemble.storage.image = response.body;
```
