### ISSUE TITLE
Support for websockets for chat/inbox use case

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble#787]
please start by suggesting EDL

**Comment by kmahmood74** [comment]
Since @snehmehta built this already for his chat widget, assigning to him to expose it in EDL.
cc @vusters

**Comment by snehmehta** [comment]
```yaml
View:
  onLoad: |
    //@code 
    // javascript functions

    ensemble.socket.connect();
    ensemble.socket.disconnect();
    ensemble.socket.reconnect();
    ensemble.socket.send({'name': 'ensemble'});

        

SOCKET:
  uri: wss://ensemble.forever.com/socket/
  connect:
    onSuccess:
      executeAction
    onFailure:
      executeAction
  onDisconnect:
    executeAction
  onReconnecting:
    executeAction
  onReceive:
    executeAction
  options:
    disconnectOnPageClose: true | false, default true.
    autoReconnect: true | false, default true.
    reconnectOptions: # It's BinaryExponentialBackoff
        initial: 1, seconds
        maxStep: 3, stop after 3 steps

 
```

Please check the above EDL and share your inputs. 
@vusters @kmahmood74 @amin-nas @evshi

**Comment by kmahmood74** [comment]
Looks good, thanks @snehmehta please continue with the changes

**Comment by kmahmood74** [comment]
Adding @sharjeelyunus Sharjeel, please have a look as well

**Comment by sharjeelyunus** [comment]
Looks good to me, thanks @snehmehta

**Comment by amin-nas** [comment]
@kmahmood74 @snehmehta @vusters 

IMO, the EDL here can be similar to APIs and ensure support across YAML and code. Also, we need to ensure consistency in our nomenclature. It gets confusing and hard to learn the EDL when one action uses `onError` and another uses `onFailure`.

Here's how:

```yaml
View:
  onLoad:
    connectSocket:
      inputs: []
      name: mySocketName
      onSuccess: <executeAction>
      onError: <executeAction>
      onDisconnect: <executeAction>
      onReconnectAttempt: <executeAction>
      onReceive: <executeAction # data available in response.data or mySocketName.data>

View:
  onLoad: |
    //@code 

    ensemble.connectSocket({
      name: "mySocketName"
    });
    
Socket:
  mySocketName:
    uri: wss://ensemble.forever.com/socket/
    onSuccess: <executeAction>
    onError: <executeAction>
    onDisconnect: <executeAction>
    onReconnectAttempt: <executeAction>
    onReceive: <executeAction # data available in response.data>
   
    options:
      disconnectOnPageClose: true | false, default true.
      autoReconnect: true | false, default true.
      reconnectOptions: # It's BinaryExponentialBackoff
          initial: 1, seconds
          maxStep: 3, stop after 3 steps
```

Other related actions are:
- `disconnectSocket`
- `reconnectSocket`
- `messageSocket`

Stretch goal:
- support mySocketName.state as a bindable variable, matching these states: CONNECTING | OPEN | CLOSING | CLOSED

**Comment by snehmehta** [comment]
> @kmahmood74 @snehmehta @vusters
> 
> IMO, the EDL here can be similar to APIs and ensure support across YAML and code. Also, we need to ensure consistency in our nomenclature. It gets confusing and hard to learn the EDL when one action uses `onError` and another uses `onFailure`.
> 
> Here's how:
> 
> ```yaml
> View:
>   onLoad:
>     connectSocket:
>       inputs: []
>       name: mySocketName
>       onSuccess: <executeAction>
>       onError: <executeAction>
>       onDisconnect: <executeAction>
>       onReconnectAttempt: <executeAction>
>       onReceive: <executeAction # data available in response.data or mySocketName.data>
> 
> View:
>   onLoad: |
>     //@code 
> 
>     ensemble.connectSocket({
>       name: "mySocketName"
>     });
>     
> Socket:
>   mySocketName:
>     uri: wss://ensemble.forever.com/socket/
>     onSuccess: <executeAction>
>     onError: <executeAction>
>     onDisconnect: <executeAction>
>     onReconnectAttempt: <executeAction>
>     onReceive: <executeAction # data available in response.data>
>    
>     options:
>       disconnectOnPageClose: true | false, default true.
>       autoReconnect: true | false, default true.
>       reconnectOptions: # It's BinaryExponentialBackoff
>           initial: 1, seconds
>           maxStep: 3, stop after 3 steps
> ```
> 
> Other related actions are:
> 
> * `disconnectSocket`
> * `reconnectSocket`
> * `messageSocket`
> 
> Stretch goal:
> 
> * support mySocketName.state as a bindable variable, matching these states: CONNECTING | OPEN | CLOSING | CLOSED

I realised with inconsistency of nomenclature while implementing, my bad. Thanks for pointing out. 
I liked the similarity with API as well, I make the necessary changes.

**Comment by snehmehta** [comment]
Hey @amin-nas 
Here is 
```yaml
View:
  onLoad: |
    //@code 

    ensemble.connectSocket("mySocketName");
    
Socket:
  mySocketName:
    uri: wss://ensemble.forever.com/socket/
    onSuccess: <executeAction>
    onError: <executeAction>
    onDisconnect: <executeAction>
    onReconnectAttempt: <executeAction>
    onReceive: <executeAction # data available in mySocketName.data>
   
    options:
      disconnectOnPageClose: true | false, default true.
      autoReconnect: true | false, default true.
      reconnectOptions: # It's BinaryExponentialBackoff
          initial: 1, seconds
          maxStep: 3, stop after 3 steps
```
