### ISSUE TITLE
Show BottomNavBar when navigated to any of its item page

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#794]
## Issue
I'm using `BottomNavBar` as such, when Next label in `BottomNavBar` is clicked, app navigates to `NextScreen` and `BottomNavBar` stays visible.
<img width="1280" alt="Screenshot 2023-09-06 at 7 25 31 PM" src="https://github.com/EnsembleUI/ensemble/assets/32386713/693fdbfe-b5cb-485b-8ba2-bc7d5f419b80">

I want same behavior when i click somewhere else, like in `MainScreen` page, there's a Button which navigates to `NextScreen`. It's achievable by doing this BUT **`selectedColor`** doesn't change upon navigation
<img width="1280" alt="Screenshot 2023-09-06 at 7 26 36 PM" src="https://github.com/EnsembleUI/ensemble/assets/32386713/c447f50f-a4d9-49d5-94fb-760844bb2387">

### ViewGroup
```yaml
ViewGroup:
  BottomNavBar:
    styles:
      color: grey
      selectedColor: black
    items:
      - label: Main
        icon:
          name: person
        page: MainScreen
        selected: "${selectedIndex == 1}"

      - label: Next
        icon:
          name: more
        page: NextScreen
        selected: "${selectedIndex == 2}"
      
      - label: Test
        icon: 
          name: more_horiz
        page: Image
        selected: "${selectedIndex == 3}"
```

### MainScreen
```yaml
View:
  header:
    title: Home
  body:
    Column:
      children:
        - Button:
            label: Go to next screen
            onTap:
              navigateScreen:
                name: BottomNavBar
                inputs:
                  selectedIndex: 2
```

### NextScreen
```yaml
View:
  header:
    title: Home
  body:
    Button:
      label: Go back to main screen
      onTap: navigateBack
```
