### ISSUE TITLE
Fallback widget for backgroundImage

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#798]
backgroundImage should have a fallback widget when we can't load the images via URL. Make sure to do this for both SVG and non SVG. If straightforward we can do this for asset image as well (though these ideally should never happen as an asset).

Please prioritize Column's backgroundImage, but we should do this everywhere backgroundImage is used.

**Comment by vusters** [comment]
If backgroundImage cannot be loaded, this widget will be displayed in its place instead.

**Comment by vinothvino42** [comment]
@vusters PR - 804

**Comment by vusters** [comment]
@vinothvino42 We need the DecorationImage working. Please work on this first thing.

**Comment by vinothvino42** [comment]
Here's the new PR - https://github.com/EnsembleUI/ensemble/pull/806

**Comment by vinothvino42** [comment]
@vusters The fallback style is working fine. Can you check the following code?

```yaml
View:
  styles:
    useSafeArea: true
    backgroundImage:
      source: https://dummyurl.com
      fallback: CustomFallbackWidget

  body:
    Column:
      styles:
        padding: 20
      children:
        - Text:
            text: Flutter
        - Column:
            styles:
              padding: 20
              height: 150
              width: 150
              backgroundColor: green
              backgroundImage:
                source: https://dummyurl.com
                # source: https://firebasestorage.googleapis.com/v0/b/ensembled-web-studio.appspot.com/o/demo_apps%2Fkitchen-sink%2Fbeach_sunset.jpg?alt=media&token=a197bdb1-7b8f-479a-9fee-722ec7857c97
                fallback: SmallWidget
            children:
              - Text:
                  text: SwiftUI Developer
                  styles:
                    backgroundColor: blue
                  textStyle:
                    color: white

SmallWidget:
  Image:
    styles: { fit: cover, height: 100, width: 100 }
    source: https://akm-img-a-in.tosshub.com/indiatoday/images/media_bank/202309/iphone-15-084541573-16x9_3.png?VersionId=7f2lrBsIJhGzRKO6ZdWIqNTf2Tjcfhz7&size=690:388

CustomFallbackWidget:
  Image:
    styles: { fit: cover, height: 700, width: 300 }
    source: https://phoenixcellular.com/wp-content/uploads/2022/09/overview__bcphzsdb4fpu_og.png

```
