### ISSUE TITLE
Need ability to specify fallback widget for Image

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble#810]
I want to be able to show a fallback image, or a custom widget when provided source of `Image` does not resolve to a valid url

```yaml
View:
  styles:
    scrollableView: true
    useSafeArea: true
  body:
    Column:
      children:
        - Image:
            source: https://images.pexels.com/photos/15447298/pexels-photo-15447298/free-photo-of-retro-cassette-records-in-stacks.jpeg
            styles:
              width: 100
              height: 100
        - Image:
            source: https://images.pexels.com/photos/15447298/pexels-photo-15447298/h.jpeg
            styles:
              width: 100
              height: 100
```
<img width="883" alt="Screenshot 2023-09-14 at 5 47 17 PM" src="https://github.com/EnsembleUI/ensemble/assets/32386713/cc82449e-b924-4e0d-b86c-417365f6881b">
