### ISSUE TITLE
Inputs passed to ViewGroup are not recognized

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#820]
I have a view group defined named App, and using `selectedIndex` to select the nav item.

```yaml
ViewGroup:
  BottomNavBar:
    styles:
      color: grey
      selectedColor: black
    items:
      - customItem:
          widget:
            NavBarItem:
              inputs:
                icon: 0xe803
                label: Home
          selectedWidget:
            ActiveNavBarItem:
              inputs:
                icon: 0xe803
                label: Home
        page: Home
        selected: "${selectedIndex == 0 ? true : false}"
```

On another page, I navigate using:

```yaml
            onTap:
              navigateScreen:
                name: App
                inputs:
                  selectedIndex: 2
```
