### ISSUE TITLE
BottomNavBar's selected no longer works

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#824]
This doesn't work anymore, most likely cause by the recent change of making BottomNavBar not reload after the first time.
```
ViewGroup:
  BottomNavBar:
    items:
      - label: Home
        icon: home
        page: Home
      - label: Profile
        icon: person
        page: Profile
        selected: true
```
