### ISSUE TITLE
Widgets inside Conditional can't be modified

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#829]
It looks like once a widget has been laid out inside a Conditional, any setters run on it won't be reflected. This is a serious issue as Conditional is the most used widget in our system

**Comment by snehmehta** [comment]
Hey @vusters , please share EDL to reproduce the issue.

From what I understand, following the EDLs I tried to recreate the issue.

```yaml
      - Conditional:
          conditions:
            - if: ${1 == 1}
              Text:
                id: test
                text: is 1 == 1?

      - Button:
          label: Test 1 == 1
          onTap: |
            //@code

            test.text = 1 == 1;
```

The above yaml works as expected i.e when I press Test 1 == 1, the text inside if condition should set to true.
