### ISSUE TITLE
Issues with WebSockets

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#831]
1. `messageSocket` action doesn't work properly with YAML, you have to use executeCode and then `ensemble.messageSocket` to make it work

2. `onReceive` action isn't available in `connectSocket`, in Socket Definition you have `onReceive, onSuccess, onError` etc, but when you use it e.g onLoad => `connectSocket` you have only 2 options `onSuccess` and `onError`, that way I have to add same uri with different SocketNames to get and store data

3. you cannot use `[socketName].data` to get the data, you have to store the data in local storage to use it e.g `onRecieve => executeCode => ensemble.storage.allMessages = JSON.parse(getAllMessages.data);`

4. I tried to use `onPullToRefresh` and then `messageSocket`, this updates the newly received messages with the latest ones i.e it removes the previous data and shows only the newly received data

```yaml
onPullToRefresh:
        executeCode:
          body: |
            //@code
            var convoId = "8f890614-0586-4cc6-ab04-df74aa8c054f";
            var next = ensemble.storage.allMessages.next;
            ensemble.messageSocket(
              'getAllMessages',
              {
                  command: "conversation-messages",
                  conversation: convoId,
                  cursor: next
              }
            );
```

Socket Definition

```
getAllMessages:
    uri: wss://api.dev.myplace.co/ws/messages?token=${ensemble.storage.token.access_token}
    onReceive:
      executeCode:
        body: |
          //@code
          ensemble.storage.allMessages = JSON.parse(getAllMessages.data);
```

How it should really work
```
onLoad
  connectSocket:
      name: getAllMessages
      onSuccess:
         messageSocket: 
           name: getAllMessages
           message:
               command: "conversation-messages"
               conversation: ${conversationId}
      onReceive:
           executeCode:
                body: |
                  //@code
                  ensemble.storage.allMessages = JSON.parse(getAllMessages.data);

Column:
   onPullToRefresh:
       messageSocket: 
           name: getAllMessages
           message:
               command: "conversation-messages"
               conversation: ${conversationId}
               cursor: ${ensemble.storage.allMessages.next}
         // a way to receive data and call an action to bind the new data with previous data
```
