### ISSUE TITLE
TabBar enhancement

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#844]
I have 2 items in TabBar and for both of the items there is a different button at the footer, I want to get the selectedIndex property from the TabBar to conditionally render each button in the footer, right now selectedIndex always stays 0

See these buttons (Preview Post, Post), I want to show them in the footer, and for that I have to conditionally render each button with TabBar selectedIndex
![image](https://github.com/EnsembleUI/ensemble/assets/61178058/847b4efc-37b6-481b-94bc-a250b865aa53)

![image](https://github.com/EnsembleUI/ensemble/assets/61178058/422d396b-5efa-4bc3-bc37-df12e75557fa)

**Comment by vinothvino42** [comment]
@sharjeelyunus Now I tested it and it looks like it's working fine. Try the following code

```yaml
View:
  styles:
    useSafeArea: true
  body:
    Column:
      children:
        - TabBar:
            id: tabbarId
            styles:
              tabPadding: 10 20 0 20
              indicatorThickness: 4
              indicatorColor: green
              activeTabColor: blue
              tabBackgroundColor: white
              dividerColor: white
            items:
              - label: First Tab
                widget:
                  Column:
                    styles: { padding: 30, crossAxis: center }
                    children:
                      - Text:
                          text: First Tab content
                      - ContentView:
                          inputs:
                            selectedIndex: ${tabbarId.selectedIndex}
              - label: Second Tab
                widget:
                  Column:
                    styles: { padding: 30, crossAxis: center }
                    children:
                      - Text:
                          text: Second Tab content
                      - ContentView:
                          inputs:
                            selectedIndex: ${tabbarId.selectedIndex}

ContentView:
  inputs:
    - selectedIndex
  body:
    Column:
      styles: { gap: 30, crossAxis: center }
      children:
        - Text:
            text: Tab content ${selectedIndex}
        - Conditional:
            conditions:
              - if: ${selectedIndex == 0}
                Button:
                  label: Preview Post
                  onTap: |
                    //@code
                    console.log(tabbarId.selectedIndex);
              - else:
                Button:
                  label: Post
                  onTap: |
                    //@code
                    console.log(tabbarId.selectedIndex);

```

**Comment by sharjeelyunus** [comment]
I need to use these buttons/condition inside the footer (outside TabBar), inside the tab bar you don't even need conditions, you can just dynamically render 2 widgets for each item

see this here, even though I'm changing the item, the selectedIndex stays 0 in footer and always shows the `Preview Post` button:

```yaml
View:
  styles:
    useSafeArea: true

  footer:
    styles:
      height: 100
      padding: 24
    children:
      - Column:
          styles:
            crossAxis: stretch
          children:
            - Conditional:
                conditions:
                  - if: ${tabbarId.selectedIndex == 0}
                    Button:
                      label: Preview Post
                  - else:
                    Button:
                      label: Post
  body:
    Column:
      children:
        - TabBar:
            id: tabbarId
            styles:
              tabPadding: 10 20 0 20
              indicatorThickness: 4
              indicatorColor: green
              activeTabColor: blue
              tabBackgroundColor: white
              dividerColor: white
            items:
              - label: First Tab
                widget:
                  Column:
                    styles: { padding: 30, crossAxis: center }
                    children:
                      - Text:
                          text: First Tab content
                      - ContentView:
                          inputs:
                            selectedIndex: ${tabbarId.selectedIndex}
              - label: Second Tab
                widget:
                  Column:
                    styles: { padding: 30, crossAxis: center }
                    children:
                      - Text:
                          text: Second Tab content
                      - ContentView:
                          inputs:
                            selectedIndex: ${tabbarId.selectedIndex}

ContentView:
  inputs:
    - selectedIndex
  body:
    Column:
      styles: { gap: 30, crossAxis: center }
      children:
        - Text:
            text: Tab content ${selectedIndex}
        - Conditional:
            conditions:
              - if: ${selectedIndex == 0}
                Button:
                  label: Preview Post
                  onTap: |
                    //@code
                    console.log(tabbarId.selectedIndex);
              - else:
                Button:
                  label: Post
                  onTap: |
                    //@code
                    console.log(tabbarId.selectedIndex);
```

**Comment by vinothvino42** [comment]
@vusters 
Currently, we can't able to access any of the widget's properties with the widget id from the footer right?

```
View:
  styles:
    useSafeArea: true
  body:
    Column:
      children:
        - Text:
            id: myTextId
            text: Second

  footer:
    styles:
      height: 100
      padding: 24
    children:
      - Text:
          text: ${myTextId.text}
```

Do we need to create footer as an invokable widget in order to get other widget's properties?

OR 

Can we create the whole page or page group widget as a invokable one?
