### ISSUE TITLE
Evaluate expressions passed header, footer, and view's styles

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#847]
I want to be able to set properties dynamically across:

1. View style props (e.g. backgroundColor, scrollableView)
2. Header props
3. Footer props

```yaml
View:
  styles:
    backgroundColor: '${flag == true ? "green" : "red"}'
  header:
    title: Home
    styles:
      backgroundColor: '${flag == true ? "green" : "red"}'
  body:
    Column:
      styles:
        backgroundColor: '${flag == true ? "green" : "red"}'
      children:
        - Content
  footer:
    styles:
      backgroundColor: '${flag == true ? "green" : "red"}'
    children:
      - Content

Global: |-
  //@code
  var flag = true;

Content:
  body:
    Spacer:
      styles:
        size: 100
```
