### ISSUE TITLE
Tabbar - Content Don't scroll inside the Tabs

### ISSUE THREAD

**Issue by reubensjohn** [EnsembleUI/ensemble#849]
I have a TabBar with two tabs inside it. Each tab is a custom widget with Column as the Parent. The column is set to scrollable, but when I put it inside my Tab(s) it's not scrolling. If I add the custom widget under the View its scrolling. What could be the Problem?

Here is the Discord thread
https://discord.com/channels/1031982848485359626/1157375258056196116

Code Below.
```
View:
  styles:
    backgroundImage:
      source: 'https://r1.ilikewallpaper.net/iphone-wallpapers/download/17922/Leather-background-iphone-wallpaper-ilikewallpaper_com.jpg'

  onLoad:
    invokeAPI:
      name: getNowPlaying

  header:
    styles:
      backgroundColor: transparent
    title: ApplicationHeader


  body:
    Stack:
      styles:
        alignChildren: topCenter
      children: 
        - PageBody:



PageBody:
  body:
    TabBar:
      selectedIndex: 0
      styles:
        tabPosition: stretch
        tabFontSize: 18
        activeTabColor: 0xFFFFC300
        inactiveTabColor: grey
        indicatorColor: 0xFFFFC300

      items:
        - label: M O V I E S
          widget:
            MovieTab:
        - label: T V
          widget: 
            TVTab:             
            


MovieTab:
  body:
    Column:
      scrollable: true

      children:
        - Heading3:
            inputs:
              text: N O W  P L A Y I N G
              color: white
```

**Comment by amin-nas** [comment]
Hi @reubensjohn - Try the following. Just adding `expanded: true` to the column so it scrolls.
@vusters - chime in if there's a better way

```yaml
View:
  styles:
    backgroundImage:
      source: 'https://r1.ilikewallpaper.net/iphone-wallpapers/download/17922/Leather-background-iphone-wallpaper-ilikewallpaper_com.jpg'

  header:
    styles:
      backgroundColor: transparent
      surfaceTintColor: transparent
      color: white
    title: test
  body:
    Stack:
      styles:
        alignChildren: topCenter
      children: 
        - PageBody:

PageBody:
  body:
    TabBar:
      selectedIndex: 0
      styles:
        tabPosition: stretch
        tabFontSize: 18
        activeTabColor: 0xFFFFC300
        inactiveTabColor: grey
        indicatorColor: 0xFFFFC300
      items:
        - label: M O V I E S
          widget:
            MovieTab:
        - label: T V
          widget: 
            TVTab:             
            
MovieTab:
  body:
    Column:
      styles:
        scrollable: true
        gap: 20
        padding: 20
        expanded: true
      children:
        - Shape:
            styles:
              height: 500
              backgroundColor: white
        - Shape:
            styles:
              height: 500
              backgroundColor: white
```
