### ISSUE TITLE
Default value in a drop down rather than Hint text

### ISSUE THREAD

**Issue by DonalRafferty** [EnsembleUI/ensemble#85]
It doesn't look like it is possible to have one of the values in a dropdown appear as a default, already selected, value. This would be rather than the Hint text parameter.

For example:

```
      - Dropdown:
          label: Select a payment card
          default: 0 #<-- the index of the default value in the items list
          items:
            - 5186***************
            - 5120***************
            - 2223***************
          required: true
```

This would then show the value (5186***************) rather than any hint text or an empty dropdown. In addition, any sort of code or selection logic would pick up this selected value even if the user never interacts with the dropdown.

**Comment by amin-nas** [comment]
@DonalRafferty We currently don't support using index, but you can use the `value` prop to set the default.
```
      - Dropdown:
          label: Select a payment card
          value: 5186***************
          items:
            - 5186***************
            - 5120***************
            - 2223***************
          required: true
```
