### ISSUE TITLE
Ability to dismiss a custom toast

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#856]
Provide an action to dismiss toast.
I have a custom toast, but I dont have a way to dismiss it except using the duration property.

```yaml
View:
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:

        - Button:
            label: r@test
            onTap:
              showToast:
                widget:
                  ErrorToast:
                    inputs:
                      message: Wrong code. Re-enter the code.
                styles: 
                  padding: 0
                  borderRadius: 50
                options:
                  duration: 15
                  dismissible: true
                  alignment: 'topCenter'



ErrorToast:
  inputs:
    - message
  body:
    Row:
      styles:
        padding: 16
        backgroundColor: white
        borderColor: 0x99FF0000
        borderWidth: 2
        borderRadius: 4
        elevation: 5
        gap: 16
        mainAxis: spaceBetween
      children:
        - Text:
            text: "${message}"
            styles:
              textStyle:
                color: red
                fontWeight: bold
        - Icon:
            name: close
            onTap: dismissToast   ## new action
```
