### ISSUE TITLE
Allow adding TextInput Label styling

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble#864]
## Use Case
- I have a client design requirement to have labels like this inside the the TextInput. 

please add this feature and mention the usage example yaml as well.

![image](https://github.com/EnsembleUI/ensemble/assets/62849614/ab671930-7a3f-4264-ade2-3dac7424f700)

CC: @vinothvino42

**Comment by vinothvino42** [comment]
@vusters PR - #868

**Comment by vinothvino42** [comment]
@sibteali786 You can achieve it something like below once the PR got merged.

```yaml
TextInput:
  id: emailId
  onDelayedKeyDuration: 0
  onDelayedKeyPress: |
    //@code
    emailId.value = emailId.value;
  styles:
    {
      enabled: true,
      labelText: '${emailId.value.length == 0 ? "" : "Name"}',
      hintText: Enter your name,
      enabledBorderColor: grey,
      focusedBorderColor: blue,
    }
```

**Comment by vinothvino42** [comment]
@vusters @sibteali786  New PR - https://github.com/EnsembleUI/ensemble/pull/888

```yaml
TextInput:
  id: emailId
  styles:
    {
      label: Email,
      floatLabel: true,
      variant: box,
      floatingLabelStyle:
        { fontWeight: semibold, fontSize: 34, color: green },
      hintText: Enter your email,
      focusedBorderColor: green,
      enabledBorderColor: gray,
    }
```
