### ISSUE TITLE
Concurrent actions

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#87]
I want to be able to fire multiple actions for an event.

```
View:
  onLoad:
    - action:
      name:
      onResponse:
    - action:
      name:
      onResponse:
```
