### ISSUE TITLE
Setting fontSize in theme breaks Text color in iOS

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#874]
Steps to recreate:

1. Create a new app
2. Update the theme with:

```yaml
Text:
  bodyMedium:
    fontSize: 17
```

3. The text widget appears fine on web but is not visible on iOS. Setting `color` prop in theme fixes the issue.
