### ISSUE TITLE
Dropdown onChange fires when value does NOT change

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#877]
1. Dropdown value is `b`
2. Click the dropdown and select `b`
3. onChange fires even though the value did not change. This causes unnecessary actions such as API calls.

```yaml
View:
  body:
    Dropdown:
      id: dropdown
      value: b
      items:
        - a
        - b
        - c
      onChange:
        showToast:
          message: value changed to ${dropdown.value}
          options:
            alignment: center
            dismissible: true
            type: info
            duration: 10
```
