### ISSUE TITLE
Unable to store object in storage

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#878]
```yaml
View:
  onLoad:
    invokeAPI:
      name: getProducts
      onResponse: |
        //@code
        var someObj = {};
        response.body.products.map(function(p){
          someObj[p.brand] = p.title;
        });
        console.log(someObj);
        ensemble.storage.set("myObj",someObj);
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - Text:
            text: |
              getProducts.body.products.length
              ${getProducts.body.products.length}

        - Text:
            text: |
              ensemble.storage.myObj.length
              ${ensemble.storage.myObj.length}

API:
  getProducts:
    method: GET
    uri: https://dummyjson.com/products?limit=3
```
