### ISSUE TITLE
SVG doesn't respect initial width/height

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#890]
While the svg is being load it does not respect the width/height assigned to it. The non-svg works properly. Please fix for svg.
```
View:
  styles:
    useSafeArea: true
  body:
    Column:
      children:
        - Image:
            styles:
              borderColor: red
              width: 50
              height: 50
            source: https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/USStates.svg
            ```
