### ISSUE TITLE
Lottie widget events

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#914]
As an app developer, I want to control when Lottie animation plays, and have access to events when it starts, ends, ...

```yaml
Lottie:
  autoPlay: # true | false, default to true
  
  #events
  onStart:
  onPause:
  onComplete:
```

I should be able to control the Lottie using code:

```yaml:
Button:
  onTap: |
    myLottie.start();
    myLottie.pause();
    myLottie.restart();
```

**Comment by hemish11** [comment]
Should we have any callback values to be passed down the line?

**Comment by amin-nas** [comment]
> Should we have any callback values to be passed down the line?

Please share your suggestions for any addition or improvement to the requirements.

**Comment by hemish11** [comment]
I will add a new callback and a new method of onReverse and .reverse()

**Comment by hemish11** [comment]
Ahh also ill be adding a bool like shouldRepeat

**Comment by amin-nas** [comment]
> Ahh also ill be adding a bool like shouldRepeat

That sounds great! Please call it `autoRepeat` and with default value of `true`.

**Comment by hemish11** [comment]
Also here's the yaml that I used for testing:
```yaml
View:
  header:
    title: Lottie
  styles:
    scrollableView: true
  Column:
    styles: { gap: 16, padding: 24 }

    children:
      - Row:
          styles: { gap: 8, crossAxis: center }
          children:
            - Icon:
                icon: warning
                styles: { color: orange }
            - Text:
                text: Lottie widget must have explicit width and height for web (this includes the preview in the editor). You do not need to specify width or height for native apps. If width or height is not specified for webapp (html renderer), it defaults to 250 for both
                styles: { overflow: wrap, expanded: true }
      - Lottie:
          id: MyLottie
          autoPlay: false
          repeat: false
          onForward: |
            //@code
            console.log("Forward");
          onReverse: |
            //@code
            console.log("Reverse");
          onPause: |
            //@code
            console.log("Pause");
          onComplete: |
            //@code
            console.log("Completed");
          source: https://assets6.lottiefiles.com/private_files/lf30_rnpgzd17.json
          styles:
            width: 400
            height: 100
      - Lottie:
          source: https://assets3.lottiefiles.com/packages/lf20_lzpnnin5.json
          repeat: true
          styles:
            width: 200
            height: 200
      - Button:
          styles:
            outline: true
            borderColor: 0xffed5742
            labelStyle:
              color: 0xffed5742
          label: Forward
          onTap: |
            //@code
            console.log("Forward");
            MyLottie.forward();
      - Button:
          styles:
            outline: true
            borderColor: 0xffed5742
            labelStyle:
              color: 0xffed5742
          label: Reverse
          onTap: |
            //@code
            console.log("Reverse");
            MyLottie.reverse();
      - Button:
          styles:
            outline: true
            borderColor: 0xffed5742
            labelStyle:
              color: 0xffed5742
          label: Reset
          onTap: |
            //@code
            console.log("Reset");
            MyLottie.reset();
      - Button:
          styles:
            outline: true
            borderColor: 0xffed5742
            labelStyle:
              color: 0xffed5742
          label: Stop
          onTap: |
            //@code
            console.log("Stop");
            MyLottie.stop();

```
