### ISSUE TITLE
DataRow's visible prop does not work

### ISSUE THREAD

**Issue by amin-nas** [EnsembleUI/ensemble#96]
Setting `visible: false` on DataRow does not work.

example
```
View:
  title: DataGrid
  Column:
    styles: { gap: 12, padding: 24, scrollable: true }
    children:
      - DataGrid: 
          DataColumns:
            - label: Hotel Name
              type: text
              tooltip: Hotel Name
            - label: Location
              type: text
              tooltip: Location
          children:
            - DataRow:
                children:
                  - Text:
                      text: My Hotel
                  - Text:
                      style: {font: subtitle}
                      text: Location
            - DataRow:
                visible: false
                styles: {font: subtitle}
                children:
                  - Text:
                      text: My Hotel - hidden row
                  - Text:
                      style: {font: subtitle}
                      text: Location
```
