### ISSUE TITLE
Studio freezes with this definition

### ISSUE THREAD

**Issue by vusters** [EnsembleUI/ensemble#962]
1. Studio will hang with this definition:
```
View:
  body:
    Text:
      text: hello
      styles:
        stackPositionTop: 0
```
stackPositionTop/Bottom/Left/Right should only be used if the widget is inside a Stack. It is not in this case so an error should be shown, instead of the page hung indefinitely. In debug mode Flutter will probably throw and error, but not release mode.

2. It'll also hang with this:
```
View:
  styles:
    useSafeArea: true
  body:
    Text:
      text: hhello
      styles:
        expanded: true
```

The ask is to show a proper error so the user know to fix it. See what we have in StudioDebugger to see how we catch similar issues.
