### ISSUE TITLE
BUG: Change switch color

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#964]
in Switch widget we have styles property, but nothing works here

I tried this

```yaml
fillColor: 0xFFD6D6CE
borderColor: amber
focusedBorderColor: blue
disabledBorderColor: grey
```
