### ISSUE TITLE
HTML widget should have maxLines option

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble#979]
Need maxLines in HTML widget, and overflow should be ellipsis, also the text color, font size and font weight.

**Comment by kmahmood74** [comment]
@hemish11 please treat this as high priority as a customer needs it

**Comment by hemish11** [comment]
@kmahmood74 @vusters @snehmehta Hows this EDL looks like:
```yaml
View:
  styles:
    scrollableView: true
  header:
    title: Home
  body:
    Column:
      children:
        - Html:
            cssStyles: # List of styles similar to CSS
              - style:
                  selector: "#Hello" # or ".Hello" or "div"
                  properties:
                    # All the CSS properties, it will be entered as key value pair just as in CSS
                    color: red
                    borderWidth: 10 # The naming can be of camelCase. Code would convert the camelCase to param-case
              - style:
                  selector: "#tag2"
                  properties:
                    color: blue
                    borderRadius: 10
            styles:
              borderRadius: 20
              borderColor: red
              borderWidth: 2
            text: |
              <div id="hello">
              Until recently, the prevailing view assumed lorem ipsum was born as a nonsense text. “It's not Latin, though it looks like it, and it actually says nothing,” Before & After magazine answered a curious reader, “Its ‘words’ loosely approximate the frequency with which letters occur in English, which is why at a glance it looks pretty real.”

              As Cicero would put it, “Um, not so fast.”

              The placeholder text, beginning with the line “Lorem ipsum dolor sit amet, consectetur adipiscing elit”, looks like Latin because in its youth, centuries ago, it was Latin.

              Richard McClintock, a Latin scholar from Hampden-Sydney College, is credited with discovering the source behind the ubiquitous filler text. In seeing a sample of lorem ipsum, his interest was piqued by consectetur—a genuine, albeit rare, Latin word. Consulting a Latin dictionary led McClintock to a passage from De Finibus Bonorum et Malorum (“On the Extremes of Good and Evil”), a first-century B.C. text from the Roman philosopher Cicero.
              </div>
```

I thought to include support for both css tags and also for the box wrapper. Also flutter has these tags supported in the styles parameter so will be adding suppport for all of them:
- background-color
- color
- counter-increment
- counter-reset
- direction
- display
- font-family
- font-feature-settings
- font-size
- font-style
- font-weight
- height
- letter-spacing
- list-style-image
- list-style-type
- list-style-position
- margin
- padding
- text-align
- text-decoration
- text-decoration-color
- text-decoration-style
- text-decoration-thickness
- text-shadow
- vertical-align
- white-space
- width
- word-spacing
- line-height
